const partTimeFaculty = [
	{
		"userName": "Oby Allsepp",
		"userEmail": "oallsepp@guptauni.edu",
		"userPassword": "Mq7I1VR",
		"userPhone": "+31 (283) 184-7197",
		"userAddress": "3 Norway Maple Drive",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5000
	},
	{
		"userName": "Catrina Yve",
		"userEmail": "cyve@guptauni.edu",
		"userPassword": "85KaUoHH2",
		"userPhone": "+20 (409) 326-7766",
		"userAddress": "8232 Monument Place",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Teach",
		"userID": 5001
	},
	{
		"userName": "Tyrone Hardage",
		"userEmail": "thardage@guptauni.edu",
		"userPassword": "TyvqgE",
		"userPhone": "+1 (820) 515-9347",
		"userAddress": "104 Badeau Plaza",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Teach",
		"userID": 5002
	},
	{
		"userName": "Antoni McClymont",
		"userEmail": "amcclymo@guptauni.edu",
		"userPassword": "C5WkvpTQ7uxt",
		"userPhone": "+993 (357) 352-4124",
		"userAddress": "73512 Summer Ridge Way",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Research",
		"userID": 5003
	},
	{
		"userName": "Sela Ricco",
		"userEmail": "sricco@guptauni.edu",
		"userPassword": "0ejN5YJ",
		"userPhone": "+385 (599) 173-7027",
		"userAddress": "3 Pleasure Terrace",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5004
	},
	{
		"userName": "Saidee Josefsson",
		"userEmail": "sjosefss@guptauni.edu",
		"userPassword": "KkYUhd1G",
		"userPhone": "+504 (123) 469-4771",
		"userAddress": "08 Del Sol Avenue",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5005
	},
	{
		"userName": "Lynn La Croce",
		"userEmail": "lla croc@guptauni.edu",
		"userPassword": "pptNfz8HB",
		"userPhone": "+234 (840) 632-5917",
		"userAddress": "48442 Rowland Avenue",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5006
	},
	{
		"userName": "Niki Maffeo",
		"userEmail": "nmaffeo@guptauni.edu",
		"userPassword": "UGuA7AF",
		"userPhone": "+992 (593) 410-6150",
		"userAddress": "89603 Grayhawk Circle",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Teach",
		"userID": 5007
	},
	{
		"userName": "Luella Parken",
		"userEmail": "lparken@guptauni.edu",
		"userPassword": "FOzaXVUat",
		"userPhone": "+86 (817) 890-7280",
		"userAddress": "2567 Annamark Pass",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Teach",
		"userID": 5008
	},
	{
		"userName": "Ryan Westmore",
		"userEmail": "rwestmor@guptauni.edu",
		"userPassword": "QYW33a2",
		"userPhone": "+1 (155) 771-1582",
		"userAddress": "4602 Reinke Point",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Research",
		"userID": 5009
	},
	{
		"userName": "Petey Unworth",
		"userEmail": "punworth@guptauni.edu",
		"userPassword": "Sthj4YCtJd",
		"userPhone": "+1 (314) 728-0439",
		"userAddress": "7014 Stone Corner Lane",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5010
	},
	{
		"userName": "Odie Cabell",
		"userEmail": "ocabell@guptauni.edu",
		"userPassword": "xMeSdEenSy",
		"userPhone": "+251 (843) 228-8179",
		"userAddress": "16544 Express Plaza",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5011
	},
	{
		"userName": "Hall Gunthorp",
		"userEmail": "hgunthor@guptauni.edu",
		"userPassword": "dTjZPjs3tN",
		"userPhone": "+52 (908) 725-6204",
		"userAddress": "112 Bluestem Avenue",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Research",
		"userID": 5012
	},
	{
		"userName": "Valentin Grigore",
		"userEmail": "vgrigore@guptauni.edu",
		"userPassword": "qRoI8yhBlNL2",
		"userPhone": "+7 (494) 474-6495",
		"userAddress": "0049 Vera Avenue",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5013
	},
	{
		"userName": "Alejoa Gomme",
		"userEmail": "agomme@guptauni.edu",
		"userPassword": "eH0vAP",
		"userPhone": "+358 (861) 349-2843",
		"userAddress": "01 Lerdahl Point",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5014
	},
	{
		"userName": "Minor Spincke",
		"userEmail": "mspincke@guptauni.edu",
		"userPassword": "9QCEf76",
		"userPhone": "+48 (407) 550-4457",
		"userAddress": "100 Mosinee Place",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5015
	},
	{
		"userName": "Mada Santoro",
		"userEmail": "msantoro@guptauni.edu",
		"userPassword": "6UwYlbbxX8Kd",
		"userPhone": "+7 (992) 592-8826",
		"userAddress": "764 Drewry Lane",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5016
	},
	{
		"userName": "Clarine Grenter",
		"userEmail": "cgrenter@guptauni.edu",
		"userPassword": "7z1PjVqu7",
		"userPhone": "+63 (730) 933-8550",
		"userAddress": "8702 Service Alley",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5017
	},
	{
		"userName": "Abram Beddall",
		"userEmail": "abeddall@guptauni.edu",
		"userPassword": "slVOP9A54Rxy",
		"userPhone": "+235 (618) 826-1962",
		"userAddress": "102 Fordem Center",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Research",
		"userID": 5018
	},
	{
		"userName": "Jobye Knotte",
		"userEmail": "jknotte@guptauni.edu",
		"userPassword": "ta6QLH",
		"userPhone": "+7 (798) 501-5000",
		"userAddress": "856 Westend Hill",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Teach",
		"userID": 5019
	},
	{
		"userName": "Olav Curton",
		"userEmail": "ocurton@guptauni.edu",
		"userPassword": "Qbnqt3iHcwg1",
		"userPhone": "+54 (475) 198-5456",
		"userAddress": "75 Del Sol Terrace",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Research",
		"userID": 5020
	},
	{
		"userName": "Jolene Samet",
		"userEmail": "jsamet@guptauni.edu",
		"userPassword": "CxvZcm26VZ6",
		"userPhone": "+48 (579) 730-8335",
		"userAddress": "34170 Morningstar Terrace",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5021
	},
	{
		"userName": "Caralie Cammomile",
		"userEmail": "ccammomi@guptauni.edu",
		"userPassword": "Q2wRcRK",
		"userPhone": "+7 (755) 260-4736",
		"userAddress": "4 Debra Street",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5022
	},
	{
		"userName": "Carolynn Pennicott",
		"userEmail": "cpennico@guptauni.edu",
		"userPassword": "72WOTx",
		"userPhone": "+62 (666) 502-2824",
		"userAddress": "6 Killdeer Hill",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5023
	},
	{
		"userName": "Cassius Gethings",
		"userEmail": "cgething@guptauni.edu",
		"userPassword": "2T4NMZe3g",
		"userPhone": "+46 (943) 914-6404",
		"userAddress": "10415 Sloan Drive",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5024
	},
	{
		"userName": "Maurene Manion",
		"userEmail": "mmanion@guptauni.edu",
		"userPassword": "VelrAU8UhBy",
		"userPhone": "+62 (432) 642-0729",
		"userAddress": "9321 Clemons Pass",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Teach",
		"userID": 5025
	},
	{
		"userName": "Zackariah Lillecrop",
		"userEmail": "zlillecr@guptauni.edu",
		"userPassword": "ZUPOnEK",
		"userPhone": "+963 (183) 477-8087",
		"userAddress": "5478 Algoma Trail",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5026
	},
	{
		"userName": "Britte Antunez",
		"userEmail": "bantunez@guptauni.edu",
		"userPassword": "A9shFf",
		"userPhone": "+380 (989) 326-5351",
		"userAddress": "62 Westridge Center",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Teach",
		"userID": 5027
	},
	{
		"userName": "Hubert Batterbee",
		"userEmail": "hbatterb@guptauni.edu",
		"userPassword": "5312kmb",
		"userPhone": "+86 (554) 744-9027",
		"userAddress": "82 Ludington Park",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Teach",
		"userID": 5028
	},
	{
		"userName": "Cristian Merryfield",
		"userEmail": "cmerryfi@guptauni.edu",
		"userPassword": "fOnqNCAK",
		"userPhone": "+351 (193) 452-4424",
		"userAddress": "3 Waywood Trail",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5029
	},
	{
		"userName": "Ramonda Mundell",
		"userEmail": "rmundell@guptauni.edu",
		"userPassword": "9KdzOZ0hKe",
		"userPhone": "+674 (457) 386-9690",
		"userAddress": "12 Sunfield Road",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5030
	},
	{
		"userName": "Devy Brabin",
		"userEmail": "dbrabin@guptauni.edu",
		"userPassword": "1vzWX0E6h",
		"userPhone": "+86 (689) 166-3785",
		"userAddress": "323 Oak Circle",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5031
	},
	{
		"userName": "Sinclair Toplis",
		"userEmail": "stoplis@guptauni.edu",
		"userPassword": "90sCADbm5",
		"userPhone": "+62 (717) 150-2842",
		"userAddress": "5059 Glacier Hill Pass",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Teach",
		"userID": 5032
	},
	{
		"userName": "Sophronia Hissett",
		"userEmail": "shissett@guptauni.edu",
		"userPassword": "GO5Bg93E0Y",
		"userPhone": "+7 (541) 724-1966",
		"userAddress": "0 Gale Lane",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5033
	},
	{
		"userName": "Leonid Thames",
		"userEmail": "lthames@guptauni.edu",
		"userPassword": "aWl9L5yr3WV",
		"userPhone": "+55 (359) 971-6364",
		"userAddress": "82940 Cottonwood Terrace",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5034
	},
	{
		"userName": "Vick Grimstead",
		"userEmail": "vgrimste@guptauni.edu",
		"userPassword": "TycMS6qCRzJ",
		"userPhone": "+7 (205) 539-0465",
		"userAddress": "40536 Kingsford Street",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5035
	},
	{
		"userName": "Gale Frazer",
		"userEmail": "gfrazer@guptauni.edu",
		"userPassword": "6eASaFzm",
		"userPhone": "+389 (340) 926-1301",
		"userAddress": "434 Utah Alley",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5036
	},
	{
		"userName": "Shea Dake",
		"userEmail": "sdake@guptauni.edu",
		"userPassword": "hXkmxH",
		"userPhone": "+358 (535) 540-5824",
		"userAddress": "2095 Stephen Terrace",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5037
	},
	{
		"userName": "Carolus Pesterfield",
		"userEmail": "cpesterf@guptauni.edu",
		"userPassword": "hRLnYg",
		"userPhone": "+63 (159) 105-9841",
		"userAddress": "7074 Comanche Crossing",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5038
	},
	{
		"userName": "Winny Cawkwell",
		"userEmail": "wcawkwel@guptauni.edu",
		"userPassword": "GffuAcNIwPmH",
		"userPhone": "+351 (476) 673-7394",
		"userAddress": "36 Sachs Parkway",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5039
	},
	{
		"userName": "Eberto Berrill",
		"userEmail": "eberrill@guptauni.edu",
		"userPassword": "evEACo",
		"userPhone": "+973 (944) 107-6011",
		"userAddress": "7 Morningstar Park",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Teach",
		"userID": 5040
	},
	{
		"userName": "Anthiathia Gabler",
		"userEmail": "agabler@guptauni.edu",
		"userPassword": "HfZHmb",
		"userPhone": "+86 (762) 378-0199",
		"userAddress": "13 Prentice Junction",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5041
	},
	{
		"userName": "Lev Morefield",
		"userEmail": "lmorefie@guptauni.edu",
		"userPassword": "YY1g88Oupr",
		"userPhone": "+86 (695) 610-4772",
		"userAddress": "1931 Banding Point",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Research",
		"userID": 5042
	},
	{
		"userName": "Glendon Megarrell",
		"userEmail": "gmegarre@guptauni.edu",
		"userPassword": "uDz9W06V6G",
		"userPhone": "+86 (465) 275-2011",
		"userAddress": "4 Alpine Place",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5043
	},
	{
		"userName": "Kessiah Weavers",
		"userEmail": "kweavers@guptauni.edu",
		"userPassword": "rQoWYp",
		"userPhone": "+62 (541) 646-6760",
		"userAddress": "54755 Packers Road",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5044
	},
	{
		"userName": "Werner Twine",
		"userEmail": "wtwine@guptauni.edu",
		"userPassword": "Oe1rs96q",
		"userPhone": "+375 (143) 599-2269",
		"userAddress": "70 Oakridge Hill",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Teach",
		"userID": 5045
	},
	{
		"userName": "Godfry Melloi",
		"userEmail": "gmelloi@guptauni.edu",
		"userPassword": "3XKz5F9LC",
		"userPhone": "+60 (397) 332-2841",
		"userAddress": "58406 Bobwhite Point",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5046
	},
	{
		"userName": "Catlin Waryk",
		"userEmail": "cwaryk@guptauni.edu",
		"userPassword": "atQBNEUWxQc",
		"userPhone": "+48 (586) 702-8493",
		"userAddress": "4 Calypso Road",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5047
	},
	{
		"userName": "Nye Lawrenson",
		"userEmail": "nlawrens@guptauni.edu",
		"userPassword": "Ftn5DXc",
		"userPhone": "+33 (383) 953-2024",
		"userAddress": "7 Garrison Alley",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5048
	},
	{
		"userName": "Consolata Giacopini",
		"userEmail": "cgiacopi@guptauni.edu",
		"userPassword": "3bL4lffh",
		"userPhone": "+591 (704) 259-5162",
		"userAddress": "31958 Macpherson Court",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5049
	},
	{
		"userName": "Celle Eisikowitch",
		"userEmail": "ceisikow@guptauni.edu",
		"userPassword": "rZkLbq",
		"userPhone": "+86 (979) 947-1111",
		"userAddress": "626 Monterey Drive",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5050
	},
	{
		"userName": "Bobette Greig",
		"userEmail": "bgreig@guptauni.edu",
		"userPassword": "DK0pTPMX",
		"userPhone": "+86 (238) 241-8335",
		"userAddress": "12 Stoughton Court",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Teach",
		"userID": 5051
	},
	{
		"userName": "Kennie Smalls",
		"userEmail": "ksmalls@guptauni.edu",
		"userPassword": "s34yynGCzN",
		"userPhone": "+66 (178) 372-6766",
		"userAddress": "2181 Clyde Gallagher Pass",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Teach",
		"userID": 5052
	},
	{
		"userName": "Adriane Goodread",
		"userEmail": "agoodrea@guptauni.edu",
		"userPassword": "SYpAdVdQkBi",
		"userPhone": "+62 (854) 663-9787",
		"userAddress": "92264 Graedel Point",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Research",
		"userID": 5053
	},
	{
		"userName": "Morissa Czajka",
		"userEmail": "mczajka@guptauni.edu",
		"userPassword": "q4Wj09Yba",
		"userPhone": "+86 (157) 869-2717",
		"userAddress": "85 Weeping Birch Place",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5054
	},
	{
		"userName": "Blakelee Tomek",
		"userEmail": "btomek@guptauni.edu",
		"userPassword": "DpeBbYK",
		"userPhone": "+62 (961) 412-3426",
		"userAddress": "3445 Kim Plaza",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5055
	},
	{
		"userName": "Judas Henniger",
		"userEmail": "jhennige@guptauni.edu",
		"userPassword": "FQPJQ650dUG",
		"userPhone": "+54 (881) 451-3882",
		"userAddress": "11 Springview Court",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5056
	},
	{
		"userName": "Erhart Hukins",
		"userEmail": "ehukins@guptauni.edu",
		"userPassword": "7LV7FrP",
		"userPhone": "+7 (712) 204-5331",
		"userAddress": "54855 Brentwood Crossing",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5057
	},
	{
		"userName": "Davida McKnockiter",
		"userEmail": "dmcknock@guptauni.edu",
		"userPassword": "yt1ztcbpqh2",
		"userPhone": "+27 (299) 342-3992",
		"userAddress": "7176 Shoshone Plaza",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Research",
		"userID": 5058
	},
	{
		"userName": "Kristy Burnapp",
		"userEmail": "kburnapp@guptauni.edu",
		"userPassword": "GENNtwi7d",
		"userPhone": "+380 (201) 990-0216",
		"userAddress": "06 Esker Plaza",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5059
	},
	{
		"userName": "Marne Drackford",
		"userEmail": "mdrackfo@guptauni.edu",
		"userPassword": "LpOWSa",
		"userPhone": "+48 (679) 662-9597",
		"userAddress": "2 Old Shore Place",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5060
	},
	{
		"userName": "Matty Gai",
		"userEmail": "mgai@guptauni.edu",
		"userPassword": "ZKlJpIirh4",
		"userPhone": "+27 (375) 336-8514",
		"userAddress": "1135 6th Place",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5061
	},
	{
		"userName": "Viki Totterdell",
		"userEmail": "vtotterd@guptauni.edu",
		"userPassword": "PWuQwttnlg5",
		"userPhone": "+358 (507) 161-3475",
		"userAddress": "83567 Spenser Point",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5062
	},
	{
		"userName": "Sander Devonish",
		"userEmail": "sdevonis@guptauni.edu",
		"userPassword": "6FnTuBwouVW",
		"userPhone": "+359 (836) 156-6386",
		"userAddress": "2625 Mosinee Terrace",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5063
	},
	{
		"userName": "Sigismond Kinnett",
		"userEmail": "skinnett@guptauni.edu",
		"userPassword": "XjF2Xto",
		"userPhone": "+355 (935) 955-6923",
		"userAddress": "0097 Schiller Street",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5064
	},
	{
		"userName": "Diane-marie Gillbee",
		"userEmail": "dgillbee@guptauni.edu",
		"userPassword": "3Y5ydNQp",
		"userPhone": "+966 (117) 750-6566",
		"userAddress": "4402 Thompson Circle",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Teach",
		"userID": 5065
	},
	{
		"userName": "Lucille Barbary",
		"userEmail": "lbarbary@guptauni.edu",
		"userPassword": "IPQ4BvzcO6x2",
		"userPhone": "+62 (994) 207-9679",
		"userAddress": "802 Sunfield Lane",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Research",
		"userID": 5066
	},
	{
		"userName": "Uriel McAuslan",
		"userEmail": "umcausla@guptauni.edu",
		"userPassword": "s6DHkw7C",
		"userPhone": "+33 (445) 157-1152",
		"userAddress": "9728 Walton Pass",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5067
	},
	{
		"userName": "Fletch Fernandez",
		"userEmail": "ffernand@guptauni.edu",
		"userPassword": "vT8MLPUHY",
		"userPhone": "+352 (100) 719-3098",
		"userAddress": "5 Southridge Alley",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5068
	},
	{
		"userName": "Margy Worssam",
		"userEmail": "mworssam@guptauni.edu",
		"userPassword": "iJCxTAblFU",
		"userPhone": "+1 (864) 763-7118",
		"userAddress": "31998 Schiller Hill",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5069
	},
	{
		"userName": "Dori Flacknoe",
		"userEmail": "dflackno@guptauni.edu",
		"userPassword": "DCLcQBPJj9",
		"userPhone": "+86 (697) 662-5804",
		"userAddress": "066 Westport Hill",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Teach",
		"userID": 5070
	},
	{
		"userName": "Rosalynd Punshon",
		"userEmail": "rpunshon@guptauni.edu",
		"userPassword": "Xn1E7YFOY",
		"userPhone": "+371 (522) 781-0162",
		"userAddress": "7299 Crowley Circle",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5071
	},
	{
		"userName": "Rheta Trounce",
		"userEmail": "rtrounce@guptauni.edu",
		"userPassword": "bZ72kopvjc",
		"userPhone": "+351 (736) 267-7190",
		"userAddress": "79921 Red Cloud Trail",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Teach",
		"userID": 5072
	},
	{
		"userName": "Cletus Liggins",
		"userEmail": "cliggins@guptauni.edu",
		"userPassword": "Hc3iB5I",
		"userPhone": "+62 (529) 507-2421",
		"userAddress": "2 Loftsgordon Trail",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5073
	},
	{
		"userName": "Lola Rennock",
		"userEmail": "lrennock@guptauni.edu",
		"userPassword": "4rmQdbr",
		"userPhone": "+33 (537) 107-7261",
		"userAddress": "3755 Red Cloud Alley",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Teach",
		"userID": 5074
	},
	{
		"userName": "Tomas Sibbson",
		"userEmail": "tsibbson@guptauni.edu",
		"userPassword": "TT8jWpLokSW",
		"userPhone": "+86 (931) 397-9181",
		"userAddress": "17702 Warner Court",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5075
	},
	{
		"userName": "Tildie Clementet",
		"userEmail": "tclement@guptauni.edu",
		"userPassword": "ymAsRZ0cJu",
		"userPhone": "+237 (820) 118-8675",
		"userAddress": "75483 Roxbury Parkway",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Research",
		"userID": 5076
	},
	{
		"userName": "Gianni Vedekhin",
		"userEmail": "gvedekhi@guptauni.edu",
		"userPassword": "EGbj9G5",
		"userPhone": "+357 (675) 369-1701",
		"userAddress": "9333 Tony Road",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Research",
		"userID": 5077
	},
	{
		"userName": "Leia Gant",
		"userEmail": "lgant@guptauni.edu",
		"userPassword": "QEgjhh",
		"userPhone": "+963 (969) 803-6024",
		"userAddress": "596 Fisk Plaza",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Teach",
		"userID": 5078
	},
	{
		"userName": "Codie Doberer",
		"userEmail": "cdoberer@guptauni.edu",
		"userPassword": "H2hH1up1J5QD",
		"userPhone": "+86 (328) 329-2198",
		"userAddress": "0 Hollow Ridge Center",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Teach",
		"userID": 5079
	}
];
export default partTimeFaculty;
