const administrator = [
	{
		"userName": "Fredericka Bratty",
		"userEmail": "fbratty0@blogspot.com",
		"userPassword": "sIIgEtMllw",
		"userPhone": "(343) 1331573",
		"userAddress": "7974 Old Shore Pass",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 30,
		"userID": 9000
	},
	{
		"userName": "Minni Ugoletti",
		"userEmail": "mugoletti1@tripadvisor.com",
		"userPassword": "PRRTjpS",
		"userPhone": "(337) 8728835",
		"userAddress": "77 7th Pass",
		"userType": "Administrator",
		"adminSalary": "$75,000 ",
		"adminOfficeNum": 31,
		"userID": 9001
	},
	{
		"userName": "Emera Ruddick",
		"userEmail": "eruddick2@homestead.com",
		"userPassword": "akz8lPXTjC",
		"userPhone": "(320) 2549191",
		"userAddress": "78659 Independence Alley",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 32,
		"userID": 9002
	},
	{
		"userName": "Jacklyn Caughan",
		"userEmail": "jcaughan3@tmall.com",
		"userPassword": "kELEZeS8yxiT",
		"userPhone": "(956) 9376995",
		"userAddress": "31 Arapahoe Parkway",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 33,
		"userID": 9003
	},
	{
		"userName": "Ewart Haborn",
		"userEmail": "ehaborn4@ucoz.com",
		"userPassword": "ICd0rW",
		"userPhone": "(162) 4067467",
		"userAddress": "382 Sloan Center",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 34,
		"userID": 9004
	},
	{
		"userName": "Theodor Fominov",
		"userEmail": "tfominov5@chronoengine.com",
		"userPassword": "meX3bj0Pe9C",
		"userPhone": "(785) 1259475",
		"userAddress": "8273 Burning Wood Terrace",
		"userType": "Administrator",
		"adminSalary": "$75,000 ",
		"adminOfficeNum": 35,
		"userID": 9005
	},
	{
		"userName": "Perri Fynan",
		"userEmail": "pfynan6@boston.com",
		"userPassword": "jSdciDI",
		"userPhone": "(319) 4702519",
		"userAddress": "3 Anderson Alley",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 36,
		"userID": 9006
	},
	{
		"userName": "Washington Gilfoyle",
		"userEmail": "wgilfoyle7@weebly.com",
		"userPassword": "4wMicCPJm",
		"userPhone": "(654) 7886979",
		"userAddress": "980 Elgar Point",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 37,
		"userID": 9007
	},
	{
		"userName": "Araldo Banghe",
		"userEmail": "abanghe8@weibo.com",
		"userPassword": "7BGxI6076CHh",
		"userPhone": "(902) 7508484",
		"userAddress": "3 Commercial Lane",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 38,
		"userID": 9008
	},
	{
		"userName": "Ivan Acedo",
		"userEmail": "iacedo9@cbsnews.com",
		"userPassword": "4Lqia5FhZ",
		"userPhone": "(387) 8895733",
		"userAddress": "06329 Spenser Avenue",
		"userType": "Administrator",
		"adminSalary": "$75,000 ",
		"adminOfficeNum": 39,
		"userID": 9009
	},
	{
		"userName": "Padraic Puxley",
		"userEmail": "ppuxleya@ca.gov",
		"userPassword": "mjkidhPxo",
		"userPhone": "(854) 6237306",
		"userAddress": "75586 Browning Road",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 40,
		"userID": 9010
	},
	{
		"userName": "Stanford Ashcroft",
		"userEmail": "sashcroftb@ameblo.jp",
		"userPassword": "UQb3Dt",
		"userPhone": "(899) 3744387",
		"userAddress": "1 Memorial Road",
		"userType": "Administrator",
		"adminSalary": "$75,000 ",
		"adminOfficeNum": 41,
		"userID": 9011
	},
	{
		"userName": "Dougy Ditzel",
		"userEmail": "dditzelc@loc.gov",
		"userPassword": "5FBBvi4Ru",
		"userPhone": "(725) 8208085",
		"userAddress": "0841 Golf Crossing",
		"userType": "Administrator",
		"adminSalary": "$75,000 ",
		"adminOfficeNum": 42,
		"userID": 9012
	},
	{
		"userName": "Babs Wingrove",
		"userEmail": "bwingroved@imageshack.us",
		"userPassword": "AXScm2sHUV",
		"userPhone": "(206) 7566145",
		"userAddress": "7 Fisk Road",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 43,
		"userID": 9013
	},
	{
		"userName": "Georgeanna Gniewosz",
		"userEmail": "ggniewosze@oakley.com",
		"userPassword": "QV6O9EjM9ACK",
		"userPhone": "(295) 9371791",
		"userAddress": "80981 Macpherson Road",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 44,
		"userID": 9014
	},
	{
		"userName": "Marlane Shade",
		"userEmail": "mshadef@slashdot.org",
		"userPassword": "vtsYJQ7H",
		"userPhone": "(886) 6024874",
		"userAddress": "95 Springview Street",
		"userType": "Administrator",
		"adminSalary": "$75,000 ",
		"adminOfficeNum": 45,
		"userID": 9015
	},
	{
		"userName": "Karita Sellens",
		"userEmail": "ksellensg@abc.net.au",
		"userPassword": "qQZmam2",
		"userPhone": "(902) 4603066",
		"userAddress": "153 Ilene Street",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 46,
		"userID": 9016
	},
	{
		"userName": "Shandy Rust",
		"userEmail": "srusth@cafepress.com",
		"userPassword": "5zFnjcM9JEf",
		"userPhone": "(467) 7889913",
		"userAddress": "441 Norway Maple Trail",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 47,
		"userID": 9017
	},
	{
		"userName": "Violetta Sarfass",
		"userEmail": "vsarfassi@sun.com",
		"userPassword": "u2A1YAbMwv1I",
		"userPhone": "(666) 3954419",
		"userAddress": "56 Cody Pass",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 48,
		"userID": 9018
	},
	{
		"userName": "Doyle Bendtsen",
		"userEmail": "dbendtsenj@free.fr",
		"userPassword": "bIIEGrNRx9",
		"userPhone": "(382) 6963105",
		"userAddress": "4959 Scott Pass",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 49,
		"userID": 9019
	},
	{
		"userName": "Marion Twinning",
		"userEmail": "mtwinningk@nymag.com",
		"userPassword": "gV4Ea62PGnu",
		"userPhone": "(549) 7536369",
		"userAddress": "92 Northview Avenue",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 50,
		"userID": 9020
	},
	{
		"userName": "Dyanne Duchenne",
		"userEmail": "dduchennel@so-net.ne.jp",
		"userPassword": "xP5jhLRI1Rt",
		"userPhone": "(915) 4750998",
		"userAddress": "849 Di Loreto Avenue",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 51,
		"userID": 9021
	},
	{
		"userName": "Port Cobbledick",
		"userEmail": "pcobbledickm@dmoz.org",
		"userPassword": "ilzMjQN",
		"userPhone": "(785) 3656944",
		"userAddress": "2 Meadow Ridge Parkway",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 52,
		"userID": 9022
	},
	{
		"userName": "Hamnet Sharman",
		"userEmail": "hsharmann@theatlantic.com",
		"userPassword": "VxbqzeY",
		"userPhone": "(731) 2484630",
		"userAddress": "70 Butterfield Lane",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 53,
		"userID": 9023
	},
	{
		"userName": "Evvy Darco",
		"userEmail": "edarcoo@jiathis.com",
		"userPassword": "OeAKD8pR",
		"userPhone": "(634) 8798297",
		"userAddress": "092 Oak Drive",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 54,
		"userID": 9024
	},
	{
		"userName": "Konstance Ranyell",
		"userEmail": "kranyellp@discuz.net",
		"userPassword": "E6IXvF",
		"userPhone": "(178) 4680632",
		"userAddress": "1368 Magdeline Trail",
		"userType": "Administrator",
		"adminSalary": "$75,000 ",
		"adminOfficeNum": 55,
		"userID": 9025
	},
	{
		"userName": "Marne Woollends",
		"userEmail": "mwoollendsq@google.nl",
		"userPassword": "dmL47xmIg",
		"userPhone": "(801) 5920109",
		"userAddress": "14559 Melvin Pass",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 56,
		"userID": 9026
	},
	{
		"userName": "Danila Tourot",
		"userEmail": "dtourotr@taobao.com",
		"userPassword": "IJBKuo",
		"userPhone": "(647) 6786662",
		"userAddress": "626 Bluejay Drive",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 57,
		"userID": 9027
	},
	{
		"userName": "Marijo Hurworth",
		"userEmail": "mhurworths@ocn.ne.jp",
		"userPassword": "JpRHrhr6pOq",
		"userPhone": "(976) 3597956",
		"userAddress": "9492 Raven Point",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 58,
		"userID": 9028
	},
	{
		"userName": "Karly Astie",
		"userEmail": "kastiet@bluehost.com",
		"userPassword": "0D8UhysJ",
		"userPhone": "(626) 5828500",
		"userAddress": "7438 Golden Leaf Plaza",
		"userType": "Administrator",
		"adminSalary": "$75,000 ",
		"adminOfficeNum": 59,
		"userID": 9029
	},
	{
		"userName": "Tyler Heinsohn",
		"userEmail": "tjheinzo@gmail.com",
		"userPassword": "7Jc9P1xzP2B",
		"userPhone": "(289) 2660886",
		"userAddress": "408 Northwestern Point",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 60,
		"userID": 9030
	},
	{
		"userName": "Sagar Vadalia",
		"userEmail": "svadalia@oldwestbury.edu",
		"userPassword": "pGTR8m",
		"userPhone": "(862) 5325183",
		"userAddress": "82 Lighthouse Bay Parkway",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 61,
		"userID": 9031
	},
	{
		"userName": "Erich Heiseler",
		"userEmail": "eheisele@oldwestbury.edu",
		"userPassword": "xvlXBn5y3V",
		"userPhone": "(782) 1568899",
		"userAddress": "934 Orin Drive",
		"userType": "Administrator",
		"adminSalary": "$125,000 ",
		"adminOfficeNum": 62,
		"userID": 9032
	}
];
export default administrator;
