const fullTimeFaculty = [
	{
		userName: 'Ansell Puddin',
		userEmail: 'apuddin0@edublogs.org',
		userPassword: 'P5gaT9Ac9dr',
		userPhone: '+62 (437) 631-2654',
		userAddress: '2 Red Cloud Road',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Olx681',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 7,
	},
	{
		userName: 'Xena Boother',
		userEmail: 'xboother1@de.vu',
		userPassword: '25ndtd',
		userPhone: '+46 (256) 119-8262',
		userAddress: '8 Randy Way',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'NMQ123',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 8,
	},
	{
		userName: 'Marita Paraman',
		userEmail: 'mparaman2@yellowbook.com',
		userPassword: 'Wbep9wEY2',
		userPhone: '+51 (870) 786-0727',
		userAddress: '872 Express Circle',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'LXl963',
		isFullTime: true,
		fSalary: '$100000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 7,
	},
	{
		userName: 'Yolane Liggons',
		userEmail: 'yliggons3@gnu.org',
		userPassword: 'm6sAqDsOQRxR',
		userPhone: '+86 (856) 103-4044',
		userAddress: '005 Bay Center',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'NeU074',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 1,
	},
	{
		userName: 'Byrom Adran',
		userEmail: 'badran4@pinterest.com',
		userPassword: 'gw1PuLEcG4qa',
		userPhone: '+33 (841) 111-5590',
		userAddress: '6210 Eagle Crest Junction',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'uPl172',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 9,
	},
	{
		userName: 'Carrissa Iron',
		userEmail: 'ciron5@sogou.com',
		userPassword: '9jSbO28PPN',
		userPhone: '+234 (639) 689-9573',
		userAddress: '563 Randy Court',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'Ntz915',
		isFullTime: true,
		fSalary: '$100000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 2,
	},
	{
		userName: 'Cornelius Brightwell',
		userEmail: 'cbrightwell6@netlog.com',
		userPassword: 'Fmu2CfwbHVgz',
		userPhone: '+86 (716) 437-8184',
		userAddress: '099 Lerdahl Place',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'ERk432',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 9,
	},
	{
		userName: 'Kerianne Paramor',
		userEmail: 'kparamor7@jimdo.com',
		userPassword: 'jYbekG',
		userPhone: '+62 (137) 201-9941',
		userAddress: '46 Schlimgen Drive',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Gmg767',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 8,
	},
	{
		userName: 'Darius Kilty',
		userEmail: 'dkilty8@latimes.com',
		userPassword: '5QvdL16p6ZG',
		userPhone: '+84 (530) 404-2595',
		userAddress: '6557 Becker Junction',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'OLl935',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 10,
	},
	{
		userName: 'Imogene Kilgallon',
		userEmail: 'ikilgallon9@trellian.com',
		userPassword: '5domoRZ8',
		userPhone: '+224 (210) 856-7995',
		userAddress: '4861 Golf View Point',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'SqR569',
		isFullTime: true,
		fSalary: '$130000',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 3,
	},
	{
		userName: 'Bertrando Ivons',
		userEmail: 'bivonsa@hp.com',
		userPassword: 'rVlq67O11uDi',
		userPhone: '+505 (295) 655-2107',
		userAddress: '3380 Marquette Point',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'fmF311',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 3,
	},
	{
		userName: 'Avrit Osmond',
		userEmail: 'aosmondb@yellowbook.com',
		userPassword: 'F8X7dd',
		userPhone: '+86 (693) 888-9287',
		userAddress: '54 6th Park',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'qbB642',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 7,
	},
	{
		userName: 'Belva McEnteggart',
		userEmail: 'bmcenteggartc@youtube.com',
		userPassword: 'cpdd92n6',
		userPhone: '+595 (479) 364-2804',
		userAddress: '9 4th Street',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'vYl456',
		isFullTime: true,
		fSalary: '$100000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 11,
	},
	{
		userName: 'Celie Sally',
		userEmail: 'csallyd@fastcompany.com',
		userPassword: 'OmiLsiO',
		userPhone: '+86 (798) 553-7076',
		userAddress: '184 Monica Trail',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Shv456',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 3,
	},
	{
		userName: 'Rahel Harmes',
		userEmail: 'rharmese@wikia.com',
		userPassword: 'UPXSBO',
		userPhone: '+86 (257) 153-7939',
		userAddress: '8 Lillian Trail',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'ygB589',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 2,
	},
	{
		userName: 'Andy Braunstein',
		userEmail: 'abraunsteinf@51.la',
		userPassword: 'W98056',
		userPhone: '+1 (121) 658-6752',
		userAddress: '8 Cambridge Plaza',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'Szl966',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 8,
	},
	{
		userName: 'Christoph Phlipon',
		userEmail: 'cphlipong@redcross.org',
		userPassword: 'KcmMThPJY',
		userPhone: '+62 (215) 207-8474',
		userAddress: '1 Northview Avenue',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'NJl902',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 11,
	},
	{
		userName: 'Dulsea Slite',
		userEmail: 'dsliteh@globo.com',
		userPassword: 't3Xymft',
		userPhone: '+62 (337) 335-4601',
		userAddress: '322 Del Sol Court',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'hrz457',
		isFullTime: true,
		fSalary: '$130000',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 11,
	},
	{
		userName: 'Edita Guidera',
		userEmail: 'eguiderai@themeforest.net',
		userPassword: 'UxAGIbKl',
		userPhone: '+994 (959) 508-1546',
		userAddress: '1 Canary Pass',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'QYU431',
		isFullTime: true,
		fSalary: '$100000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 11,
	},
	{
		userName: 'Ailbert Chuney',
		userEmail: 'achuneyj@etsy.com',
		userPassword: 'NXgvJemCySa',
		userPhone: '+81 (179) 467-2721',
		userAddress: '40 Basil Parkway',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'Rky267',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 1,
	},
	{
		userName: 'Tasha Coppenhall',
		userEmail: 'tcoppenhallk@g.co',
		userPassword: 'LmpQ6i12',
		userPhone: '+27 (188) 889-4980',
		userAddress: '8072 Paget Way',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Dvt925',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 13,
	},
	{
		userName: 'Bengt Mowles',
		userEmail: 'bmowlesl@scientificamerican.com',
		userPassword: 'OjUlOg',
		userPhone: '+970 (132) 583-0809',
		userAddress: '0 Scoville Point',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'rGd816',
		isFullTime: true,
		fSalary: '$130000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 3,
	},
	{
		userName: 'Tabor Duddan',
		userEmail: 'tduddanm@hexun.com',
		userPassword: 'W6MCOgCZAZa',
		userPhone: '+62 (799) 989-3952',
		userAddress: '360 Sherman Terrace',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Xtk134',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 5,
	},
	{
		userName: 'Nichole Shorland',
		userEmail: 'nshorlandn@foxnews.com',
		userPassword: 'ktTTQLeTEv',
		userPhone: '+389 (301) 843-9351',
		userAddress: '301 Forest Dale Road',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'fJs678',
		isFullTime: true,
		fSalary: '$100000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 9,
	},
	{
		userName: 'Hakim Henrichsen',
		userEmail: 'hhenrichseno@house.gov',
		userPassword: 'c3YKpIEO2n',
		userPhone: '+234 (501) 647-0576',
		userAddress: '4 Ronald Regan Crossing',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Itb962',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 8,
	},
	{
		userName: 'Janetta Kimmons',
		userEmail: 'jkimmonsp@go.com',
		userPassword: 'x6Jecni',
		userPhone: '+62 (189) 262-4211',
		userAddress: '8085 Lien Hill',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'hpY504',
		isFullTime: true,
		fSalary: '$100000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 14,
	},
	{
		userName: 'Ferrell Matelyunas',
		userEmail: 'fmatelyunasq@quantcast.com',
		userPassword: 'vhN5QvoBK',
		userPhone: '+81 (104) 823-4796',
		userAddress: '757 Bartillon Road',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'iDX673',
		isFullTime: true,
		fSalary: '$130000',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 5,
	},
	{
		userName: 'Adelaida Holdren',
		userEmail: 'aholdrenr@studiopress.com',
		userPassword: 'rgQ9okNyn',
		userPhone: '+351 (760) 838-8683',
		userAddress: '50 Hanover Lane',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'bLI529',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 12,
	},
	{
		userName: 'Haslett Donaway',
		userEmail: 'hdonaways@state.gov',
		userPassword: 'aVxoSGt8X26',
		userPhone: '+56 (407) 891-0308',
		userAddress: '92 Independence Court',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'lEX344',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 7,
	},
	{
		userName: 'Darbee Bahlmann',
		userEmail: 'dbahlmannt@dot.gov',
		userPassword: 'EJOs33AHLqME',
		userPhone: '+351 (517) 917-9655',
		userAddress: '30341 Hanover Parkway',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'ajh669',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 13,
	},
	{
		userName: 'Cherise Baildon',
		userEmail: 'cbaildonu@umn.edu',
		userPassword: 'w9l5bKzswDp',
		userPhone: '+55 (960) 348-4744',
		userAddress: '6007 Arrowood Way',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'Kbg065',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 2,
	},
	{
		userName: 'Cirstoforo Dovidaitis',
		userEmail: 'cdovidaitisv@quantcast.com',
		userPassword: 'ohNnkVmZer',
		userPhone: '+375 (572) 734-4595',
		userAddress: '7 Main Road',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'hBN629',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 14,
	},
	{
		userName: 'Cymbre Casini',
		userEmail: 'ccasiniw@multiply.com',
		userPassword: 'lkLWjxbdpYcb',
		userPhone: '+380 (191) 919-6437',
		userAddress: '27786 Northfield Point',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'CQu431',
		isFullTime: true,
		fSalary: '$130000',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 3,
	},
	{
		userName: 'Meir Colton',
		userEmail: 'mcoltonx@businessweek.com',
		userPassword: '2c8kCOi5',
		userPhone: '+20 (183) 249-8700',
		userAddress: '7056 Ridgeview Place',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'Ksr486',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 9,
	},
	{
		userName: 'Spencer Syncke',
		userEmail: 'ssynckey@mayoclinic.com',
		userPassword: 'Y8x4330',
		userPhone: '+692 (788) 712-8716',
		userAddress: '72889 Calypso Lane',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'Piv773',
		isFullTime: true,
		fSalary: '$100000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 13,
	},
	{
		userName: 'Gayleen Aveline',
		userEmail: 'gavelinez@senate.gov',
		userPassword: 'k3QdCzv2',
		userPhone: '+249 (543) 470-8674',
		userAddress: '56 Harbort Avenue',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'RCo310',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 4,
	},
	{
		userName: 'Gilles Baldelli',
		userEmail: 'gbaldelli10@photobucket.com',
		userPassword: 'EEaLe6s731',
		userPhone: '+86 (944) 935-4667',
		userAddress: '6 Little Fleur Street',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'GOF561',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 14,
	},
	{
		userName: 'Rube Abramamovh',
		userEmail: 'rabramamovh11@google.nl',
		userPassword: '66RgDXfNh6Z',
		userPhone: '+62 (683) 110-9516',
		userAddress: '9047 Loeprich Drive',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'oiS666',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 3,
	},
	{
		userName: 'Friedrick Tough',
		userEmail: 'ftough12@bluehost.com',
		userPassword: 'ngeYKCnnLrKl',
		userPhone: '+51 (110) 966-4968',
		userAddress: '6 Karstens Lane',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'wQF447',
		isFullTime: true,
		fSalary: '$130000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 14,
	},
	{
		userName: 'Bliss Caukill',
		userEmail: 'bcaukill13@wordpress.com',
		userPassword: 'fxFKzS78rd',
		userPhone: '+48 (560) 705-5549',
		userAddress: '4881 Sundown Parkway',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'iNL216',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 2,
	},
	{
		userName: 'Rose Geaves',
		userEmail: 'rgeaves14@mayoclinic.com',
		userPassword: 'KsOsKYDnqV',
		userPhone: '+33 (290) 828-7113',
		userAddress: '689 Columbus Avenue',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'ftZ971',
		isFullTime: true,
		fSalary: '$100000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 15,
	},
	{
		userName: 'Skyler Sickert',
		userEmail: 'ssickert15@oaic.gov.au',
		userPassword: 'unS9gwK',
		userPhone: '+31 (189) 205-1330',
		userAddress: '030 Scoville Place',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'nQD438',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 15,
	},
	{
		userName: 'Timothea Dutch',
		userEmail: 'tdutch16@digg.com',
		userPassword: '5r0ghCC',
		userPhone: '+221 (990) 746-3805',
		userAddress: '2 Northwestern Street',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'xqB009',
		isFullTime: true,
		fSalary: '$100000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 9,
	},
	{
		userName: 'Joellen Lassen',
		userEmail: 'jlassen17@upenn.edu',
		userPassword: 'qG3IKiyMkuNB',
		userPhone: '+48 (871) 310-5363',
		userAddress: '5 Carioca Center',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'ihC792',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 4,
	},
	{
		userName: 'Grove Spehr',
		userEmail: 'gspehr18@naver.com',
		userPassword: 'Z3C2Ws9Z1P8',
		userPhone: '+81 (655) 600-7793',
		userAddress: '8594 Dahle Trail',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'Yzb431',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 6,
	},
	{
		userName: 'Dedie Kenwright',
		userEmail: 'dkenwright19@google.fr',
		userPassword: '3HbQ49',
		userPhone: '+7 (133) 170-2651',
		userAddress: '826 Rutledge Crossing',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'nLs668',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 13,
	},
	{
		userName: 'Nolly Boldero',
		userEmail: 'nboldero1a@fastcompany.com',
		userPassword: 'GDm1i0',
		userPhone: '+63 (600) 173-6871',
		userAddress: '6177 Russell Terrace',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'Epj529',
		isFullTime: true,
		fSalary: '$100000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 3,
	},
	{
		userName: 'Tarra Paye',
		userEmail: 'tpaye1b@cnn.com',
		userPassword: 'RfcRHkq',
		userPhone: '+62 (456) 631-0922',
		userAddress: '46 Marquette Place',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'SJw552',
		isFullTime: true,
		fSalary: '$130000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 6,
	},
	{
		userName: 'Gayel Govenlock',
		userEmail: 'ggovenlock1c@webs.com',
		userPassword: 'HLjltaRj',
		userPhone: '+507 (635) 769-9696',
		userAddress: '30 2nd Lane',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'VOa630',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 8,
	},
	{
		userName: 'Pegeen Saunder',
		userEmail: 'psaunder1d@bloglines.com',
		userPassword: 'Xxvx8PoLAyN3',
		userPhone: '+62 (532) 956-9968',
		userAddress: '2215 Oriole Court',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'hbp758',
		isFullTime: true,
		fSalary: '$100000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 1,
	},
	{
		userName: 'Adah Yakovlev',
		userEmail: 'ayakovlev1e@g.co',
		userPassword: 'HtYCMA',
		userPhone: '+92 (312) 939-8558',
		userAddress: '02 Grim Park',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'ISL325',
		isFullTime: true,
		fSalary: '$130000',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 1,
	},
	{
		userName: 'Leigha Blofield',
		userEmail: 'lblofield1f@lulu.com',
		userPassword: 'JwvK6P9sZIX',
		userPhone: '+237 (823) 278-0078',
		userAddress: '416 Union Point',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Yrv276',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 2,
	},
	{
		userName: 'Shelba Liddell',
		userEmail: 'sliddell1g@chicagotribune.com',
		userPassword: 'iiiGsuTx0B47',
		userPhone: '+33 (811) 423-7119',
		userAddress: '09460 Truax Street',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'VvI602',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 7,
	},
	{
		userName: 'Nolly Sone',
		userEmail: 'nsone1h@g.co',
		userPassword: '954FwZ7x',
		userPhone: '+86 (990) 633-8236',
		userAddress: '6 Sundown Parkway',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'FoL791',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 9,
	},
	{
		userName: 'Othella Trass',
		userEmail: 'otrass1i@dedecms.com',
		userPassword: 'C3yHZiWkw',
		userPhone: '+86 (995) 645-3266',
		userAddress: '2 Raven Park',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'gnp492',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 5,
	},
	{
		userName: 'Devan Guislin',
		userEmail: 'dguislin1j@shinystat.com',
		userPassword: 'r4yZtFZKC',
		userPhone: '+86 (779) 881-5953',
		userAddress: '2791 Cambridge Street',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'YJQ762',
		isFullTime: true,
		fSalary: '$100000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 2,
	},
	{
		userName: 'Burnaby Flintuff',
		userEmail: 'bflintuff1k@guardian.co.uk',
		userPassword: 'Biryav',
		userPhone: '+55 (246) 579-5319',
		userAddress: '49 Annamark Hill',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'fSB518',
		isFullTime: true,
		fSalary: '$100000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 12,
	},
	{
		userName: 'Budd Eliaz',
		userEmail: 'beliaz1l@icio.us',
		userPassword: 'JL9KZzd48b',
		userPhone: '+86 (865) 985-1320',
		userAddress: '14 Loomis Point',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'eqp118',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 12,
	},
	{
		userName: 'Eda Petroff',
		userEmail: 'epetroff1m@oakley.com',
		userPassword: 'T7amKlH4Fq9',
		userPhone: '+506 (788) 314-7558',
		userAddress: '2326 Scott Pass',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'TDK421',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 9,
	},
	{
		userName: 'Elberta Trase',
		userEmail: 'etrase1n@imdb.com',
		userPassword: 'b82B6yMCRWLp',
		userPhone: '+595 (596) 560-4617',
		userAddress: '9237 Monterey Place',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'saC687',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 8,
	},
	{
		userName: 'Morley Myhill',
		userEmail: 'mmyhill1o@sbwire.com',
		userPassword: 'L2K03ckJk',
		userPhone: '+62 (175) 549-9830',
		userAddress: '19 Bultman Avenue',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'HoB928',
		isFullTime: true,
		fSalary: '$100000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 2,
	},
	{
		userName: 'Norry Sissel',
		userEmail: 'nsissel1p@ask.com',
		userPassword: 'uv1RH8alv',
		userPhone: '+33 (453) 914-2509',
		userAddress: '5243 Clarendon Pass',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'wRC410',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 5,
	},
	{
		userName: 'Pooh Crathorne',
		userEmail: 'pcrathorne1q@cisco.com',
		userPassword: 'aWYIbrM',
		userPhone: '+355 (745) 720-1698',
		userAddress: '21037 Charing Cross Avenue',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'cEJ977',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 12,
	},
	{
		userName: 'Edsel Romayn',
		userEmail: 'eromayn1r@mit.edu',
		userPassword: 'fFRFLZE',
		userPhone: '+86 (439) 807-2877',
		userAddress: '73 Chive Park',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'DXV837',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 11,
	},
	{
		userName: 'Danyelle Whinney',
		userEmail: 'dwhinney1s@github.com',
		userPassword: '3BWmxyWiG',
		userPhone: '+46 (419) 746-5562',
		userAddress: '89 Cascade Way',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'hti388',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 5,
	},
	{
		userName: 'Sela Cramb',
		userEmail: 'scramb1t@google.pl',
		userPassword: 'QTwxzHqsz',
		userPhone: '+7 (870) 109-1932',
		userAddress: '733 Kim Street',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'OYn983',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 10,
	},
	{
		userName: 'Odette Dall',
		userEmail: 'odall1u@webnode.com',
		userPassword: 'q9a8iuhn',
		userPhone: '+62 (103) 353-7756',
		userAddress: '89 Crescent Oaks Parkway',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'JPT866',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 4,
	},
	{
		userName: 'Jeddy Daniel',
		userEmail: 'jdaniel1v@globo.com',
		userPassword: 'OoSyQYKIn',
		userPhone: '+52 (620) 597-4753',
		userAddress: '7 Fallview Parkway',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'HsY878',
		isFullTime: true,
		fSalary: '$130000',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 15,
	},
	{
		userName: 'Danny Uzielli',
		userEmail: 'duzielli1w@virginia.edu',
		userPassword: 'eVR28XSZ4Q',
		userPhone: '+386 (186) 861-0121',
		userAddress: '7 Memorial Way',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'NWV078',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 12,
	},
	{
		userName: 'Farly Freire',
		userEmail: 'ffreire1x@angelfire.com',
		userPassword: 'Z4mcGa1',
		userPhone: '+55 (869) 916-9427',
		userAddress: '3505 Waubesa Point',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'yMg037',
		isFullTime: true,
		fSalary: '$130000',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 12,
	},
	{
		userName: 'Hatti Leitch',
		userEmail: 'hleitch1y@newsvine.com',
		userPassword: 'PhpNSuXp',
		userPhone: '+55 (840) 640-1258',
		userAddress: '2277 Elka Pass',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'fcn221',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 8,
	},
	{
		userName: 'Blaire Menpes',
		userEmail: 'bmenpes1z@google.com.br',
		userPassword: 'LoMjzquoBN',
		userPhone: '+54 (682) 221-1404',
		userAddress: '11 Straubel Street',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'HSG052',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 15,
	},
	{
		userName: 'Loralie Alster',
		userEmail: 'lalster20@ibm.com',
		userPassword: 'qLrtmE8j',
		userPhone: '+386 (611) 344-7093',
		userAddress: '6 Orin Drive',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'qwX567',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 13,
	},
	{
		userName: 'Rooney Miskimmon',
		userEmail: 'rmiskimmon21@amazonaws.com',
		userPassword: 'HuTw8vzJ9',
		userPhone: '+351 (126) 842-6808',
		userAddress: '18 Glacier Hill Avenue',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'Pyv383',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 13,
	},
	{
		userName: 'Deanne Caslin',
		userEmail: 'dcaslin22@ifeng.com',
		userPassword: 'P2OU7B0p',
		userPhone: '+86 (311) 585-4099',
		userAddress: '562 John Wall Circle',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'dcF342',
		isFullTime: true,
		fSalary: '$120000',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 4,
	},
	{
		userName: 'Jamill Cardenas',
		userEmail: 'jcardenas23@php.net',
		userPassword: 'wFwT731Db',
		userPhone: '+86 (689) 372-5443',
		userAddress: '30 Arapahoe Drive',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'AYt650',
		isFullTime: true,
		fSalary: '$125000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 3,
	},
	{
		userName: 'Corrine Roseaman',
		userEmail: 'croseaman24@amazon.co.jp',
		userPassword: 'PAcNcc10eC',
		userPhone: '+1 (395) 662-2346',
		userAddress: '25404 Haas Lane',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'PBd817',
		isFullTime: true,
		fSalary: '$130000',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 1,
	},
	{
		userName: 'Quintilla Grane',
		userEmail: 'qgrane25@com.com',
		userPassword: 'PuA11ISKBl',
		userPhone: '+598 (813) 608-4257',
		userAddress: '387 Kennedy Parkway',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'qSH516',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 8,
	},
	{
		userName: 'Waylon Feron',
		userEmail: 'wferon26@slate.com',
		userPassword: 'bVHtUbNAXYGN',
		userPhone: '+351 (509) 317-1264',
		userAddress: '1 Killdeer Circle',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'qOn888',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 1,
	},
	{
		userName: 'Nesta Weigh',
		userEmail: 'nweigh27@mit.edu',
		userPassword: 'CKut1r',
		userPhone: '+46 (352) 147-1351',
		userAddress: '6 Spaight Pass',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'JFR058',
		isFullTime: true,
		fSalary: '$110000',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 6,
	},
];
export default fullTimeFaculty;
