const fullTimeFaculty = [
	{
		"userName": "Jacquie Dogerty",
		"userEmail": "jdogerty0@webmd.com",
		"userPassword": "5RkojWopN9w",
		"userPhone": "+63 (739) 976-0570",
		"userAddress": "73 Elka Court",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 101,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6000
	},
	{
		"userName": "Cynthie Gammade",
		"userEmail": "cgammade1@blinklist.com",
		"userPassword": "eTpXlca",
		"userPhone": "+30 (135) 562-0679",
		"userAddress": "275 Namekagon Center",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 102,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6001
	},
	{
		"userName": "Arlan Goly",
		"userEmail": "agoly2@bizjournals.com",
		"userPassword": "uWfrmxEq3",
		"userPhone": "+62 (212) 452-5399",
		"userAddress": "33846 Scoville Court",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 103,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6002
	},
	{
		"userName": "Tiphany Presser",
		"userEmail": "tpresser3@ox.ac.uk",
		"userPassword": "sP2prp01j",
		"userPhone": "+1 (661) 501-5513",
		"userAddress": "7139 Granby Street",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 104,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6003
	},
	{
		"userName": "Haven Burlingham",
		"userEmail": "hburlingham4@themeforest.net",
		"userPassword": "80VbMtidEo5",
		"userPhone": "+31 (317) 382-4297",
		"userAddress": "54957 Tomscot Parkway",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 105,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6004
	},
	{
		"userName": "Lennard Harnett",
		"userEmail": "lharnett5@sciencedirect.com",
		"userPassword": "4wXsGv",
		"userPhone": "+86 (715) 287-7094",
		"userAddress": "248 Walton Junction",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 106,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6005
	},
	{
		"userName": "Edsel Rosbrough",
		"userEmail": "erosbrough6@rambler.ru",
		"userPassword": "yq1UoiMh",
		"userPhone": "+7 (425) 911-0896",
		"userAddress": "6570 Schiller Avenue",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 107,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6006
	},
	{
		"userName": "Ardene Clacey",
		"userEmail": "aclacey7@wiley.com",
		"userPassword": "SOxNK7",
		"userPhone": "+66 (513) 355-8698",
		"userAddress": "3546 Bartillon Crossing",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 108,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6007
	},
	{
		"userName": "Sherwood Pennell",
		"userEmail": "spennell8@altervista.org",
		"userPassword": "XmKlsl2Z",
		"userPhone": "+86 (670) 802-7099",
		"userAddress": "1 Novick Point",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 109,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6008
	},
	{
		"userName": "Elicia Roscow",
		"userEmail": "eroscow9@studiopress.com",
		"userPassword": "EQ7s5y0j9",
		"userPhone": "+33 (909) 838-8447",
		"userAddress": "7 Fieldstone Park",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 110,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": true,
		"userID": 6009
	},
	{
		"userName": "Isadora Kruse",
		"userEmail": "ikrusea@marketwatch.com",
		"userPassword": "MLQnLxXtmDW",
		"userPhone": "+33 (581) 462-3598",
		"userAddress": "03371 Mccormick Center",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 111,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": true,
		"userID": 6010
	},
	{
		"userName": "Dorita Caswall",
		"userEmail": "dcaswallb@hibu.com",
		"userPassword": "eI5hOwWWGo",
		"userPhone": "+996 (518) 386-2116",
		"userAddress": "4 Johnson Pass",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 112,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6011
	},
	{
		"userName": "Shara Bautiste",
		"userEmail": "sbautistec@theguardian.com",
		"userPassword": "QsLa99ihYnt",
		"userPhone": "+98 (272) 377-5103",
		"userAddress": "6 Dapin Point",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 113,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6012
	},
	{
		"userName": "Antonin Cruess",
		"userEmail": "acruessd@vk.com",
		"userPassword": "tw7O1i",
		"userPhone": "+7 (355) 526-2461",
		"userAddress": "8 Bellgrove Way",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 114,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6013
	},
	{
		"userName": "Abigale O'Dare",
		"userEmail": "aodaree@skype.com",
		"userPassword": "MRHC75",
		"userPhone": "+86 (624) 368-9529",
		"userAddress": "7862 Northland Park",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 115,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": false,
		"userID": 6014
	},
	{
		"userName": "Hedi Ripping",
		"userEmail": "hrippingf@msu.edu",
		"userPassword": "YDmAuh1Y6",
		"userPhone": "+380 (465) 916-4313",
		"userAddress": "06 Fordem Drive",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 116,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": false,
		"userID": 6015
	},
	{
		"userName": "Drucill Errichiello",
		"userEmail": "derrichiellog@wp.com",
		"userPassword": "XizLWuC",
		"userPhone": "+62 (726) 177-4992",
		"userAddress": "41 Sullivan Pass",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 117,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6016
	},
	{
		"userName": "Wynn Tabbernor",
		"userEmail": "wtabbernorh@java.com",
		"userPassword": "992SBZfqVbfr",
		"userPhone": "+380 (262) 425-3481",
		"userAddress": "0258 Graedel Circle",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 118,
		"isFullTime": true,
		"fSalary": "$100,000 ",
		"fTenure": false,
		"userID": 6017
	},
	{
		"userName": "Charley Pfaffel",
		"userEmail": "cpfaffeli@trellian.com",
		"userPassword": "G17ErO",
		"userPhone": "+351 (851) 304-7950",
		"userAddress": "85 Sundown Park",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 119,
		"isFullTime": true,
		"fSalary": "$100,000 ",
		"fTenure": false,
		"userID": 6018
	},
	{
		"userName": "Elaine Billin",
		"userEmail": "ebillinj@bloomberg.com",
		"userPassword": "fvpIqR",
		"userPhone": "+961 (820) 564-3105",
		"userAddress": "29545 Pankratz Point",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 120,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6019
	},
	{
		"userName": "Nerta Tretter",
		"userEmail": "ntretterk@hexun.com",
		"userPassword": "UDgIOjriMnmZ",
		"userPhone": "+86 (577) 116-3626",
		"userAddress": "99 Sachs Lane",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 121,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": true,
		"userID": 6020
	},
	{
		"userName": "Errick Penella",
		"userEmail": "epenellal@bloomberg.com",
		"userPassword": "pcQVhqFM",
		"userPhone": "+60 (412) 197-9277",
		"userAddress": "4 Sachs Plaza",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 122,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": false,
		"userID": 6021
	},
	{
		"userName": "Byram Faulkener",
		"userEmail": "bfaulkenerm@nbcnews.com",
		"userPassword": "xeKsMF",
		"userPhone": "+358 (820) 135-2932",
		"userAddress": "58038 Garrison Terrace",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 123,
		"isFullTime": true,
		"fSalary": "$100,000 ",
		"fTenure": false,
		"userID": 6022
	},
	{
		"userName": "Clerkclaude Janusz",
		"userEmail": "cjanuszn@w3.org",
		"userPassword": "g9Dbvsb2EzI",
		"userPhone": "+46 (856) 232-0934",
		"userAddress": "4512 Manufacturers Trail",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 124,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": true,
		"userID": 6023
	},
	{
		"userName": "Erinn Ripping",
		"userEmail": "erippingo@domainmarket.com",
		"userPassword": "QmcQbDmRkUX",
		"userPhone": "+509 (961) 868-7457",
		"userAddress": "59866 Holy Cross Drive",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 125,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": true,
		"userID": 6024
	},
	{
		"userName": "Melloney Bushell",
		"userEmail": "mbushellp@fema.gov",
		"userPassword": "rLTkgac",
		"userPhone": "+7 (332) 125-5108",
		"userAddress": "7 Hallows Street",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 126,
		"isFullTime": true,
		"fSalary": "$100,000 ",
		"fTenure": false,
		"userID": 6025
	},
	{
		"userName": "Caddric Mardle",
		"userEmail": "cmardleq@biblegateway.com",
		"userPassword": "pxtYbz3UzV",
		"userPhone": "+86 (188) 148-9145",
		"userAddress": "00 Aberg Drive",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 127,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6026
	},
	{
		"userName": "Annalise McPharlain",
		"userEmail": "amcpharlainr@sourceforge.net",
		"userPassword": "fUZFCr",
		"userPhone": "+62 (139) 481-2399",
		"userAddress": "32 Manitowish Trail",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 128,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": false,
		"userID": 6027
	},
	{
		"userName": "Noell Horley",
		"userEmail": "nhorleys@yandex.ru",
		"userPassword": "KfkNQOn",
		"userPhone": "+62 (421) 231-0127",
		"userAddress": "5 Basil Terrace",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 129,
		"isFullTime": true,
		"fSalary": "$130,000 ",
		"fTenure": true,
		"userID": 6028
	},
	{
		"userName": "Elmo Aymeric",
		"userEmail": "eaymerict@eventbrite.com",
		"userPassword": "hIMGq2",
		"userPhone": "+46 (608) 521-7307",
		"userAddress": "9335 Laurel Junction",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 130,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6029
	},
	{
		"userName": "Theadora Winkell",
		"userEmail": "twinkellu@goo.ne.jp",
		"userPassword": "i8FCoNj",
		"userPhone": "+86 (703) 668-7091",
		"userAddress": "1412 Hanover Place",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 131,
		"isFullTime": true,
		"fSalary": "$130,000 ",
		"fTenure": false,
		"userID": 6030
	},
	{
		"userName": "Angeline Champagne",
		"userEmail": "achampagnev@woothemes.com",
		"userPassword": "ENSs5Wh7",
		"userPhone": "+86 (976) 868-8143",
		"userAddress": "304 Granby Parkway",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 132,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6031
	},
	{
		"userName": "Francklin Saveall",
		"userEmail": "fsaveallw@so-net.ne.jp",
		"userPassword": "aChcpyaM4",
		"userPhone": "+370 (350) 691-0551",
		"userAddress": "9 Monument Lane",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 133,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": true,
		"userID": 6032
	},
	{
		"userName": "Falkner Ibberson",
		"userEmail": "fibbersonx@sfgate.com",
		"userPassword": "1F0uL8",
		"userPhone": "+255 (831) 631-0023",
		"userAddress": "47230 Mallard Pass",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 134,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6033
	},
	{
		"userName": "Kalle Housecraft",
		"userEmail": "khousecrafty@gizmodo.com",
		"userPassword": "ruT5j1QtHTL",
		"userPhone": "+63 (776) 173-4201",
		"userAddress": "39044 Golf Course Street",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 135,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6034
	},
	{
		"userName": "Charline Hesser",
		"userEmail": "chesserz@nba.com",
		"userPassword": "FXj9DjVnaQTk",
		"userPhone": "+62 (426) 612-6897",
		"userAddress": "95721 Saint Paul Park",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 136,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": false,
		"userID": 6035
	},
	{
		"userName": "Byran Lyenyng",
		"userEmail": "blyenyng10@yellowpages.com",
		"userPassword": "3JLh0lbIv",
		"userPhone": "+62 (427) 547-5786",
		"userAddress": "763 Ronald Regan Crossing",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 137,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6036
	},
	{
		"userName": "Jacky Linnitt",
		"userEmail": "jlinnitt11@ted.com",
		"userPassword": "BNDt9vFHgDp",
		"userPhone": "+7 (688) 974-4454",
		"userAddress": "09905 Golden Leaf Alley",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 138,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": true,
		"userID": 6037
	},
	{
		"userName": "Wesley Caldes",
		"userEmail": "wcaldes12@techcrunch.com",
		"userPassword": "AaGavRkxwZeu",
		"userPhone": "+7 (592) 172-9259",
		"userAddress": "3201 Morning Place",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 139,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": false,
		"userID": 6038
	},
	{
		"userName": "Gil Yacobsohn",
		"userEmail": "gyacobsohn13@berkeley.edu",
		"userPassword": "GDQs9Uxt",
		"userPhone": "+380 (492) 974-4951",
		"userAddress": "5 Golf View Plaza",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 140,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6039
	},
	{
		"userName": "Noak Halwell",
		"userEmail": "nhalwell14@buzzfeed.com",
		"userPassword": "A2sUty5jQM",
		"userPhone": "+86 (235) 174-4907",
		"userAddress": "73062 Anzinger Terrace",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 141,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": false,
		"userID": 6040
	},
	{
		"userName": "Sisile O'Kielt",
		"userEmail": "sokielt15@ted.com",
		"userPassword": "MgcIObuw",
		"userPhone": "+7 (431) 401-4365",
		"userAddress": "19 Oriole Pass",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 142,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6041
	},
	{
		"userName": "Franni Brandle",
		"userEmail": "fbrandle16@google.cn",
		"userPassword": "fmmb37deG",
		"userPhone": "+355 (180) 785-2213",
		"userAddress": "47267 Esch Pass",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 143,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": true,
		"userID": 6042
	},
	{
		"userName": "Stanford Sutcliffe",
		"userEmail": "ssutcliffe17@dagondesign.com",
		"userPassword": "TSCs5fOqxv",
		"userPhone": "+62 (359) 436-0519",
		"userAddress": "9224 Mesta Junction",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 144,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6043
	},
	{
		"userName": "Cecilio Geane",
		"userEmail": "cgeane18@ifeng.com",
		"userPassword": "mVUZZwbtjVIc",
		"userPhone": "+1 (205) 374-2683",
		"userAddress": "705 Arizona Plaza",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 145,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6044
	},
	{
		"userName": "Maegan Guidotti",
		"userEmail": "mguidotti19@blog.com",
		"userPassword": "7qVUlUM3j",
		"userPhone": "+86 (893) 126-8898",
		"userAddress": "1 Hagan Place",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 146,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6045
	},
	{
		"userName": "Frasco Letham",
		"userEmail": "fletham1a@yolasite.com",
		"userPassword": "kygsczcmfx",
		"userPhone": "+967 (552) 331-6629",
		"userAddress": "8379 Grasskamp Junction",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 147,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6046
	},
	{
		"userName": "Saleem Scurfield",
		"userEmail": "sscurfield1b@dropbox.com",
		"userPassword": "47jn2Vw8ye6A",
		"userPhone": "+51 (944) 819-0492",
		"userAddress": "5 Hagan Point",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 148,
		"isFullTime": true,
		"fSalary": "$130,000 ",
		"fTenure": true,
		"userID": 6047
	},
	{
		"userName": "Bambi Breckenridge",
		"userEmail": "bbreckenridge1c@netvibes.com",
		"userPassword": "wpBoTeBNbc",
		"userPhone": "+20 (389) 919-1011",
		"userAddress": "5 Lakewood Trail",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 149,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": false,
		"userID": 6048
	},
	{
		"userName": "Gabriele Castagne",
		"userEmail": "gcastagne1d@naver.com",
		"userPassword": "Mlxeblpfa",
		"userPhone": "+63 (992) 328-9930",
		"userAddress": "8899 Del Mar Avenue",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 150,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": true,
		"userID": 6049
	},
	{
		"userName": "Wendell Pearch",
		"userEmail": "wpearch1e@alibaba.com",
		"userPassword": "v9M54Q24sZy7",
		"userPhone": "+62 (595) 673-0283",
		"userAddress": "237 Cascade Drive",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 151,
		"isFullTime": true,
		"fSalary": "$100,000 ",
		"fTenure": false,
		"userID": 6050
	},
	{
		"userName": "Carine Althrope",
		"userEmail": "calthrope1f@tinypic.com",
		"userPassword": "8OgdGTmMU",
		"userPhone": "+351 (490) 841-5772",
		"userAddress": "75368 Briar Crest Drive",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 152,
		"isFullTime": true,
		"fSalary": "$130,000 ",
		"fTenure": true,
		"userID": 6051
	},
	{
		"userName": "Gabby Guidoni",
		"userEmail": "gguidoni1g@weibo.com",
		"userPassword": "dOim5dHKKB",
		"userPhone": "+86 (302) 102-1037",
		"userAddress": "3 Gerald Court",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 153,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": false,
		"userID": 6052
	},
	{
		"userName": "Yance Lawranson",
		"userEmail": "ylawranson1h@prnewswire.com",
		"userPassword": "oee5J4",
		"userPhone": "+86 (426) 632-1451",
		"userAddress": "96248 Starling Junction",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 154,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": false,
		"userID": 6053
	},
	{
		"userName": "Othella Brosch",
		"userEmail": "obrosch1i@1688.com",
		"userPassword": "j5SXu6S",
		"userPhone": "+36 (743) 700-0408",
		"userAddress": "52438 Vidon Plaza",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 155,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6054
	},
	{
		"userName": "Norine Breckwell",
		"userEmail": "nbreckwell1j@wikipedia.org",
		"userPassword": "A46DjEb",
		"userPhone": "+1 (386) 354-9846",
		"userAddress": "57284 Kipling Park",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 156,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": true,
		"userID": 6055
	},
	{
		"userName": "Hastings McGrady",
		"userEmail": "hmcgrady1k@ed.gov",
		"userPassword": "Vk5j6uX",
		"userPhone": "+380 (495) 489-1605",
		"userAddress": "8 Pine View Parkway",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 157,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": true,
		"userID": 6056
	},
	{
		"userName": "Junia Vallantine",
		"userEmail": "jvallantine1l@jalbum.net",
		"userPassword": "Ijj9vFf5iKA",
		"userPhone": "+7 (359) 184-7563",
		"userAddress": "8 Mcguire Street",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 158,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": true,
		"userID": 6057
	},
	{
		"userName": "Akim Hunnawill",
		"userEmail": "ahunnawill1m@ning.com",
		"userPassword": "o21xUkQqf",
		"userPhone": "+45 (572) 180-6190",
		"userAddress": "97169 John Wall Park",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 159,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6058
	},
	{
		"userName": "Nevins Brusby",
		"userEmail": "nbrusby1n@hud.gov",
		"userPassword": "Dh6imWfkJmQo",
		"userPhone": "+62 (586) 443-6558",
		"userAddress": "2254 Quincy Lane",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 160,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": true,
		"userID": 6059
	},
	{
		"userName": "Jaquenetta Sarney",
		"userEmail": "jsarney1o@scientificamerican.com",
		"userPassword": "8Wk4yY4bI6q",
		"userPhone": "+62 (261) 679-4571",
		"userAddress": "025 Florence Park",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 161,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": true,
		"userID": 6060
	},
	{
		"userName": "Maressa Loukes",
		"userEmail": "mloukes1p@mapquest.com",
		"userPassword": "NapqtKU",
		"userPhone": "+371 (176) 854-1142",
		"userAddress": "996 North Alley",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 162,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6061
	},
	{
		"userName": "Franz Guerrazzi",
		"userEmail": "fguerrazzi1q@thetimes.co.uk",
		"userPassword": "Kwm4ANuAR",
		"userPhone": "+507 (829) 355-6622",
		"userAddress": "15 Valley Edge Point",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 163,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6062
	},
	{
		"userName": "Cece Chantler",
		"userEmail": "cchantler1r@hibu.com",
		"userPassword": "1Fmul5SM",
		"userPhone": "+84 (751) 976-0027",
		"userAddress": "96 North Lane",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 164,
		"isFullTime": true,
		"fSalary": "$100,000 ",
		"fTenure": false,
		"userID": 6063
	},
	{
		"userName": "Liv Hawkin",
		"userEmail": "lhawkin1s@woothemes.com",
		"userPassword": "H7c3Up",
		"userPhone": "+7 (692) 928-2260",
		"userAddress": "2890 Pawling Alley",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 165,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": true,
		"userID": 6064
	},
	{
		"userName": "Michel Girkins",
		"userEmail": "mgirkins1t@tripod.com",
		"userPassword": "OXpUiS",
		"userPhone": "+504 (449) 497-4334",
		"userAddress": "57774 Clemons Avenue",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 166,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6065
	},
	{
		"userName": "Hewet Hucke",
		"userEmail": "hhucke1u@macromedia.com",
		"userPassword": "2yBQweN",
		"userPhone": "+84 (491) 840-9065",
		"userAddress": "26132 Westend Junction",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 167,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": true,
		"userID": 6066
	},
	{
		"userName": "Adriano Blackhurst",
		"userEmail": "ablackhurst1v@gizmodo.com",
		"userPassword": "DAFdpJ",
		"userPhone": "+86 (946) 527-0709",
		"userAddress": "37 Atwood Parkway",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 168,
		"isFullTime": true,
		"fSalary": "$100,000 ",
		"fTenure": false,
		"userID": 6067
	},
	{
		"userName": "Faulkner Casterot",
		"userEmail": "fcasterot1w@alexa.com",
		"userPassword": "uyeS5QpC6",
		"userPhone": "+63 (414) 240-2029",
		"userAddress": "8738 Fair Oaks Alley",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 169,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6068
	},
	{
		"userName": "Tulley Dilliway",
		"userEmail": "tdilliway1x@latimes.com",
		"userPassword": "R6F38YdRM4SR",
		"userPhone": "+57 (641) 761-5582",
		"userAddress": "608 Bartillon Parkway",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 170,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": true,
		"userID": 6069
	},
	{
		"userName": "Florance Tidey",
		"userEmail": "ftidey1y@hibu.com",
		"userPassword": "K1YARq",
		"userPhone": "+55 (202) 775-3831",
		"userAddress": "345 Canary Drive",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 171,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6070
	},
	{
		"userName": "Effie Reade",
		"userEmail": "ereade1z@quantcast.com",
		"userPassword": "s0q1PpSp9B",
		"userPhone": "+86 (538) 125-5492",
		"userAddress": "152 Dahle Center",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 172,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": true,
		"userID": 6071
	},
	{
		"userName": "Luce Rothschild",
		"userEmail": "lrothschild20@free.fr",
		"userPassword": "UWqHJB",
		"userPhone": "+62 (957) 502-2671",
		"userAddress": "20 Pennsylvania Pass",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"roomIDNum": 173,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6072
	},
	{
		"userName": "Ashely Faloon",
		"userEmail": "afaloon21@slate.com",
		"userPassword": "MRpvRFzM6Ab",
		"userPhone": "+86 (651) 272-5720",
		"userAddress": "28 Elmside Plaza",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 174,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": false,
		"userID": 6073
	},
	{
		"userName": "Tristam Stoving",
		"userEmail": "tstoving22@sbwire.com",
		"userPassword": "SGqB8Ne",
		"userPhone": "+39 (906) 204-1657",
		"userAddress": "33 Walton Parkway",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 175,
		"isFullTime": true,
		"fSalary": "$100,000 ",
		"fTenure": false,
		"userID": 6074
	},
	{
		"userName": "Gertrud MacPaike",
		"userEmail": "gmacpaike23@nba.com",
		"userPassword": "QLDCS0Uu",
		"userPhone": "+33 (276) 405-3801",
		"userAddress": "06537 Melvin Place",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 176,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6075
	},
	{
		"userName": "Vitoria Haggath",
		"userEmail": "vhaggath24@springer.com",
		"userPassword": "7EFnCAPDvQK",
		"userPhone": "+86 (492) 859-3090",
		"userAddress": "7635 Maywood Street",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 177,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6076
	},
	{
		"userName": "Flynn Synder",
		"userEmail": "fsynder25@arizona.edu",
		"userPassword": "35qYBk",
		"userPhone": "+49 (361) 604-6652",
		"userAddress": "3889 Division Alley",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 178,
		"isFullTime": true,
		"fSalary": "$125,000 ",
		"fTenure": true,
		"userID": 6077
	},
	{
		"userName": "Stephanus Bingall",
		"userEmail": "sbingall26@boston.com",
		"userPassword": "16ywyL1NXopU",
		"userPhone": "+351 (140) 723-7494",
		"userAddress": "37 Wayridge Crossing",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"roomIDNum": 179,
		"isFullTime": true,
		"fSalary": "$110,000 ",
		"fTenure": false,
		"userID": 6078
	},
	{
		"userName": "Breanne Tixall",
		"userEmail": "btixall27@soundcloud.com",
		"userPassword": "diQiZvVk",
		"userPhone": "+55 (244) 625-5113",
		"userAddress": "243 Anderson Trail",
		"userType": "Faculty",
		"fRank": "Professor",
		"roomIDNum": 180,
		"isFullTime": true,
		"fSalary": "$120,000 ",
		"fTenure": false,
		"userID": 6079
	}
];
export default fullTimeFaculty;
