const graduatePartTime = [
	{
		userName: 'Angil Champney',
		userEmail: 'achampney0@buzzfeed.com',
		userPassword: 'eFie82f',
		userPhone: '(711) 4118387',
		userAddress: '06201 Banding Circle',
		userType: 'Student',
		sGPA: 2.1,
		sGradYear: 2017,
		sDOB: '5/13/2003',
		totalCredits: 40,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: true,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Liva Gatecliff',
		userEmail: 'lgatecliff1@plala.or.jp',
		userPassword: 'l3CeEmV',
		userPhone: '(624) 6757176',
		userAddress: '4 Calypso Plaza',
		userType: 'Student',
		sGPA: 2.6,
		sGradYear: 2018,
		sDOB: '1/11/2000',
		totalCredits: 111,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Robb Duffield',
		userEmail: 'rduffield2@huffingtonpost.com',
		userPassword: 'LxitIEU9ez0',
		userPhone: '(119) 6677817',
		userAddress: '9391 Mayer Avenue',
		userType: 'Student',
		sGPA: 1.3,
		sGradYear: 2019,
		sDOB: '2/15/1988',
		totalCredits: 111,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Rip Engelbrecht',
		userEmail: 'rengelbrecht3@virginia.edu',
		userPassword: 'hxuuVhAmr2DV',
		userPhone: '(468) 8834273',
		userAddress: '1123 Forest Dale Road',
		userType: 'Student',
		sGPA: 1.4,
		sGradYear: 2020,
		sDOB: '4/30/1996',
		totalCredits: 48,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Celeste Comino',
		userEmail: 'ccomino4@issuu.com',
		userPassword: 'qZNTpaZg',
		userPhone: '(649) 3257321',
		userAddress: '09280 Browning Plaza',
		userType: 'Student',
		sGPA: 3.6,
		sGradYear: 2021,
		sDOB: '1/18/1986',
		totalCredits: 120,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Pavel Sanpher',
		userEmail: 'psanpher5@sciencedirect.com',
		userPassword: 'ONud0OP',
		userPhone: '(140) 7686605',
		userAddress: '054 Spaight Trail',
		userType: 'Student',
		sGPA: 2.2,
		sGradYear: 2022,
		sDOB: '2/18/2000',
		totalCredits: 56,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Raynor Rolston',
		userEmail: 'rrolston6@weather.com',
		userPassword: 'MKqM90p',
		userPhone: '(412) 9368120',
		userAddress: '5 Manley Avenue',
		userType: 'Student',
		sGPA: 1.9,
		sGradYear: 2023,
		sDOB: '11/19/1992',
		totalCredits: 40,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Veradis Berwick',
		userEmail: 'vberwick7@netscape.com',
		userPassword: 'H36wVM',
		userPhone: '(632) 2352461',
		userAddress: '90 Amoth Trail',
		userType: 'Student',
		sGPA: 1.6,
		sGradYear: 2024,
		sDOB: '3/19/1999',
		totalCredits: 44,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Tanner Yearne',
		userEmail: 'tyearne8@globo.com',
		userPassword: 'MMAwky3sTA38',
		userPhone: '(264) 4571938',
		userAddress: '90 Alpine Road',
		userType: 'Student',
		sGPA: 3.9,
		sGradYear: 2025,
		sDOB: '12/27/1994',
		totalCredits: 11,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Mandy Swaffield',
		userEmail: 'mswaffield9@biblegateway.com',
		userPassword: 'tlvrgWDSn6wO',
		userPhone: '(309) 1161511',
		userAddress: '676 Kings Crossing',
		userType: 'Student',
		sGPA: 1.7,
		sGradYear: 2026,
		sDOB: '5/6/1998',
		totalCredits: 48,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: true,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Walliw Sheryn',
		userEmail: 'wsheryna@paginegialle.it',
		userPassword: 'QmG8KV',
		userPhone: '(138) 3309901',
		userAddress: '248 Bartillon Alley',
		userType: 'Student',
		sGPA: 2.8,
		sGradYear: 2017,
		sDOB: '7/15/1988',
		totalCredits: 24,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Abbye Brigge',
		userEmail: 'abriggeb@1188.com',
		userPassword: 'DS9yJ5L',
		userPhone: '(181) 4640717',
		userAddress: '809 Iowa Terrace',
		userType: 'Student',
		sGPA: 1.4,
		sGradYear: 2018,
		sDOB: '7/28/1997',
		totalCredits: 96,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Bryon Dmitr',
		userEmail: 'bdmitrc@feedburner.com',
		userPassword: 'oEaNSQq',
		userPhone: '(556) 5362730',
		userAddress: '84426 Duke Crossing',
		userType: 'Student',
		sGPA: 2.1,
		sGradYear: 2019,
		sDOB: '12/2/1985',
		totalCredits: 112,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Myrtice Gainsburgh',
		userEmail: 'mgainsburghd@squidoo.com',
		userPassword: 'FnnDDqkjk',
		userPhone: '(915) 8543465',
		userAddress: '79 Bonner Circle',
		userType: 'Student',
		sGPA: 2.3,
		sGradYear: 2020,
		sDOB: '1/19/1993',
		totalCredits: 112,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Merry Tafani',
		userEmail: 'mtafanie@economist.com',
		userPassword: 'dD1nsdF',
		userPhone: '(235) 2872710',
		userAddress: '4 Vernon Parkway',
		userType: 'Student',
		sGPA: 1.6,
		sGradYear: 2021,
		sDOB: '9/5/1981',
		totalCredits: 64,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Roberto Eckels',
		userEmail: 'reckelsf@bbc.co.uk',
		userPassword: 'VrMj9gKdt',
		userPhone: '(577) 4235810',
		userAddress: '71 Hallows Crossing',
		userType: 'Student',
		sGPA: 3.1,
		sGradYear: 2022,
		sDOB: '1/15/1985',
		totalCredits: 36,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Waite Keyworth',
		userEmail: 'wkeyworthg@loc.gov',
		userPassword: 'Hyppx2E',
		userPhone: '(420) 5449023',
		userAddress: '7 Susan Drive',
		userType: 'Student',
		sGPA: 2.6,
		sGradYear: 2023,
		sDOB: '6/10/1992',
		totalCredits: 80,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
	{
		userName: 'Meara Eunson',
		userEmail: 'meunsonh@t.co',
		userPassword: '1wINrChPU0',
		userPhone: '(513) 5764967',
		userAddress: '54 North Pass',
		userType: 'Student',
		sGPA: 3.0,
		sGradYear: 2024,
		sDOB: '3/12/1984',
		totalCredits: 44,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Vilma Angell',
		userEmail: 'vangelli@globo.com',
		userPassword: 'bltuW90Ok',
		userPhone: '(507) 9647953',
		userAddress: '84712 Reindahl Plaza',
		userType: 'Student',
		sGPA: 1.7,
		sGradYear: 2025,
		sDOB: '5/17/2000',
		totalCredits: 68,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
	{
		userName: 'Avery Rupke',
		userEmail: 'arupkej@weebly.com',
		userPassword: 'OXKWAAk',
		userPhone: '(969) 9849350',
		userAddress: '8 Evergreen Pass',
		userType: 'Student',
		sGPA: 1.6,
		sGradYear: 2026,
		sDOB: '6/9/1984',
		totalCredits: 44,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
	{
		userName: 'Kata Inchan',
		userEmail: 'kinchank@icq.com',
		userPassword: 'rwCT4r',
		userPhone: '(372) 9862947',
		userAddress: '10082 Springview Court',
		userType: 'Student',
		sGPA: 3.7,
		sGradYear: 2017,
		sDOB: '3/6/1998',
		totalCredits: 80,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
	{
		userName: 'Bethina Milkins',
		userEmail: 'bmilkinsl@washington.edu',
		userPassword: 'yAZBE5g09IK',
		userPhone: '(486) 2629846',
		userAddress: '51 Village Green Trail',
		userType: 'Student',
		sGPA: 2.8,
		sGradYear: 2018,
		sDOB: '7/23/1984',
		totalCredits: 80,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Vanessa Marchment',
		userEmail: 'vmarchmentm@newyorker.com',
		userPassword: 'zqRrV2s',
		userPhone: '(594) 9191991',
		userAddress: '873 Cherokee Alley',
		userType: 'Student',
		sGPA: 1.2,
		sGradYear: 2019,
		sDOB: '2/25/1995',
		totalCredits: 60,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: true,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Viki Belford',
		userEmail: 'vbelfordn@cdbaby.com',
		userPassword: 'nvJYXVq2uz',
		userPhone: '(993) 9294082',
		userAddress: '25 Lakewood Gardens Alley',
		userType: 'Student',
		sGPA: 3.0,
		sGradYear: 2020,
		sDOB: '7/7/1998',
		totalCredits: 100,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Lanny Newell',
		userEmail: 'lnewello@sogou.com',
		userPassword: 'zUjwXayd',
		userPhone: '(941) 8575993',
		userAddress: '03 Butterfield Avenue',
		userType: 'Student',
		sGPA: 2.9,
		sGradYear: 2021,
		sDOB: '4/3/1996',
		totalCredits: 96,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: true,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Hendrika Goshawk',
		userEmail: 'hgoshawkp@sfgate.com',
		userPassword: 'yYCm7nQI',
		userPhone: '(461) 4943298',
		userAddress: '0548 Mariners Cove Center',
		userType: 'Student',
		sGPA: 3.4,
		sGradYear: 2022,
		sDOB: '10/5/2000',
		totalCredits: 32,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Suellen Jessel',
		userEmail: 'sjesselq@deviantart.com',
		userPassword: 'SUtPeTC2RL',
		userPhone: '(117) 1099062',
		userAddress: '64288 4th Place',
		userType: 'Student',
		sGPA: 3.5,
		sGradYear: 2023,
		sDOB: '7/18/1990',
		totalCredits: 32,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Datha Trevains',
		userEmail: 'dtrevainsr@cpanel.net',
		userPassword: 'XRUXnbjmWneL',
		userPhone: '(987) 8228945',
		userAddress: '6539 Florence Center',
		userType: 'Student',
		sGPA: 1.3,
		sGradYear: 2024,
		sDOB: '6/2/2000',
		totalCredits: 52,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Tracie Charpin',
		userEmail: 'tcharpins@senate.gov',
		userPassword: 'KGe6tgFKQ',
		userPhone: '(799) 2776846',
		userAddress: '458 Eastlawn Lane',
		userType: 'Student',
		sGPA: 2.2,
		sGradYear: 2025,
		sDOB: '6/1/2001',
		totalCredits: 24,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Erie Heckle',
		userEmail: 'ehecklet@yahoo.com',
		userPassword: 'oemmClgyFWo',
		userPhone: '(663) 4035249',
		userAddress: '62882 Charing Cross Alley',
		userType: 'Student',
		sGPA: 1.6,
		sGradYear: 2026,
		sDOB: '11/1/1997',
		totalCredits: 96,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Terry Ruste',
		userEmail: 'trusteu@jigsy.com',
		userPassword: 'zIJMmCh',
		userPhone: '(421) 9802445',
		userAddress: '778 Londonderry Point',
		userType: 'Student',
		sGPA: 3.1,
		sGradYear: 2017,
		sDOB: '4/28/1993',
		totalCredits: 36,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
	{
		userName: 'Westley Dahlen',
		userEmail: 'wdahlenv@unesco.org',
		userPassword: 'AQEsgwFKp',
		userPhone: '(280) 6238373',
		userAddress: '98 Holy Cross Court',
		userType: 'Student',
		sGPA: 2.3,
		sGradYear: 2018,
		sDOB: '11/4/1992',
		totalCredits: 96,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Sydelle Twallin',
		userEmail: 'stwallinw@mashable.com',
		userPassword: 'pa7xsqgc',
		userPhone: '(990) 2883977',
		userAddress: '23 Orin Street',
		userType: 'Student',
		sGPA: 2.8,
		sGradYear: 2019,
		sDOB: '11/29/1985',
		totalCredits: 24,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: true,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Paule Fairleigh',
		userEmail: 'pfairleighx@webmd.com',
		userPassword: 'TZMqbT',
		userPhone: '(502) 3893227',
		userAddress: '568 Dottie Center',
		userType: 'Student',
		sGPA: 2.4,
		sGradYear: 2020,
		sDOB: '1/2/1994',
		totalCredits: 96,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Etty Stidever',
		userEmail: 'estidevery@whitehouse.gov',
		userPassword: 'c2VRmOHtFR',
		userPhone: '(952) 4075098',
		userAddress: '5784 Blue Bill Park Park',
		userType: 'Student',
		sGPA: 3.8,
		sGradYear: 2021,
		sDOB: '6/17/1990',
		totalCredits: 104,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Orion Menear',
		userEmail: 'omenearz@seattletimes.com',
		userPassword: 'H46zgzq',
		userPhone: '(719) 6522430',
		userAddress: '03959 Emmet Alley',
		userType: 'Student',
		sGPA: 2.4,
		sGradYear: 2022,
		sDOB: '3/13/1988',
		totalCredits: 56,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
	{
		userName: 'Alex Bernakiewicz',
		userEmail: 'abernakiewicz10@51.la',
		userPassword: 'IJvxZssns',
		userPhone: '(139) 8185605',
		userAddress: '85 Brentwood Avenue',
		userType: 'Student',
		sGPA: 3.4,
		sGradYear: 2023,
		sDOB: '12/1/1981',
		totalCredits: 120,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Mathilde Gilliver',
		userEmail: 'mgilliver11@yolasite.com',
		userPassword: 'jtngD9E',
		userPhone: '(842) 3710457',
		userAddress: '78 Thompson Trail',
		userType: 'Student',
		sGPA: 3.0,
		sGradYear: 2024,
		sDOB: '3/6/1983',
		totalCredits: 68,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Agata Greir',
		userEmail: 'agreir12@github.io',
		userPassword: 'DXQdo1d',
		userPhone: '(324) 3134295',
		userAddress: '70 Marquette Park',
		userType: 'Student',
		sGPA: 2.1,
		sGradYear: 2025,
		sDOB: '5/14/1989',
		totalCredits: 68,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Emanuele Flounders',
		userEmail: 'eflounders13@jiathis.com',
		userPassword: 'FcVu46Q',
		userPhone: '(470) 4362975',
		userAddress: '4 Haas Way',
		userType: 'Student',
		sGPA: 2.2,
		sGradYear: 2026,
		sDOB: '10/24/1992',
		totalCredits: 72,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
	{
		userName: 'Rachelle Longthorn',
		userEmail: 'rlongthorn14@de.vu',
		userPassword: 'wzNVSLaKJHTA',
		userPhone: '(534) 7284335',
		userAddress: '4602 Burning Wood Plaza',
		userType: 'Student',
		sGPA: 1.8,
		sGradYear: 2017,
		sDOB: '6/9/1986',
		totalCredits: 80,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Cobbie Dudbridge',
		userEmail: 'cdudbridge15@plala.or.jp',
		userPassword: '03s46pzur5',
		userPhone: '(690) 3772667',
		userAddress: '785 Dunning Pass',
		userType: 'Student',
		sGPA: 2.8,
		sGradYear: 2018,
		sDOB: '9/13/1989',
		totalCredits: 52,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Gaby Pecey',
		userEmail: 'gpecey11@upenn.edu',
		userPassword: 'igiuNTi0',
		userPhone: '(978) 5398363',
		userAddress: '00 7th Plaza',
		userType: 'Student',
		sGPA: 1.2,
		sGradYear: 2019,
		sDOB: '12/11/1984',
		totalCredits: 24,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Susann Tedridge',
		userEmail: 'stedridge17@usgs.gov',
		userPassword: 'kxrI5EE',
		userPhone: '(701) 6732987',
		userAddress: '21 Myrtle Hill',
		userType: 'Student',
		sGPA: 3.9,
		sGradYear: 2020,
		sDOB: '8/15/1995',
		totalCredits: 72,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
	{
		userName: 'Brander Wozencraft',
		userEmail: 'bwozencraft18@squidoo.com',
		userPassword: 'JkrWVEkGboLf',
		userPhone: '(432) 4246079',
		userAddress: '2 Fordem Way',
		userType: 'Student',
		sGPA: 3.1,
		sGradYear: 2021,
		sDOB: '12/5/1993',
		totalCredits: 8,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
	{
		userName: 'Sven Matysik',
		userEmail: 'smatysik19@furl.net',
		userPassword: 'dO6ep4uQN',
		userPhone: '(497) 4147198',
		userAddress: '47435 Continental Circle',
		userType: 'Student',
		sGPA: 2.0,
		sGradYear: 2022,
		sDOB: '9/25/1997',
		totalCredits: 20,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Lonny Sargeaunt',
		userEmail: 'lsargeaunt1a@wiley.com',
		userPassword: '2X2GW5',
		userPhone: '(139) 8003533',
		userAddress: '81 Rutledge Road',
		userType: 'Student',
		sGPA: 2.1,
		sGradYear: 2023,
		sDOB: '10/24/1995',
		totalCredits: 104,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Ronni Seabridge',
		userEmail: 'rseabridge1b@redcross.org',
		userPassword: 'isSciNVgn89',
		userPhone: '(297) 1814698',
		userAddress: '29022 Wayridge Alley',
		userType: 'Student',
		sGPA: 1.2,
		sGradYear: 2024,
		sDOB: '11/3/1992',
		totalCredits: 36,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
	{
		userName: 'Toiboid Lacey',
		userEmail: 'tlacey1c@mayoclinic.com',
		userPassword: '8oeQN5LI6gJ',
		userPhone: '(822) 7957323',
		userAddress: '6603 Blaine Crossing',
		userType: 'Student',
		sGPA: 3.1,
		sGradYear: 2025,
		sDOB: '1/9/1984',
		totalCredits: 92,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Gracia Schankelborg',
		userEmail: 'gschankelborg1d@google.it',
		userPassword: 'zazHxM',
		userPhone: '(180) 6953119',
		userAddress: '81929 Maywood Lane',
		userType: 'Student',
		sGPA: 3.2,
		sGradYear: 2026,
		sDOB: '7/6/1997',
		totalCredits: 100,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: true,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Reider Praundl',
		userEmail: 'rpraundl1e@webeden.co.uk',
		userPassword: '21JO7hk4S',
		userPhone: '(604) 2581569',
		userAddress: '5375 School Center',
		userType: 'Student',
		sGPA: 3.9,
		sGradYear: 2017,
		sDOB: '2/11/1995',
		totalCredits: 112,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Sloane Surmeyers',
		userEmail: 'ssurmeyers1f@goo.ne.jp',
		userPassword: 'XSNPA08X',
		userPhone: '(314) 4052911',
		userAddress: '645 Arizona Junction',
		userType: 'Student',
		sGPA: 1.2,
		sGradYear: 2018,
		sDOB: '8/14/2000',
		totalCredits: 11,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Meg Greatham',
		userEmail: 'mgreatham1g@live.com',
		userPassword: 'GiyioXMjGsuq',
		userPhone: '(178) 1812961',
		userAddress: '397 South Way',
		userType: 'Student',
		sGPA: 3.4,
		sGradYear: 2019,
		sDOB: '9/10/1985',
		totalCredits: 84,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: true,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Demetrius Moff',
		userEmail: 'dmoff1h@who.int',
		userPassword: 'coFyY0',
		userPhone: '(372) 9601110',
		userAddress: '7 Crescent Oaks Court',
		userType: 'Student',
		sGPA: 2.4,
		sGradYear: 2020,
		sDOB: '9/12/1992',
		totalCredits: 8,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: true,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Micky Betun',
		userEmail: 'mbetun1i@google.com.br',
		userPassword: 'xgtuZMFnpC',
		userPhone: '(226) 5595114',
		userAddress: '1 Springs Trail',
		userType: 'Student',
		sGPA: 2.1,
		sGradYear: 2021,
		sDOB: '1/4/2001',
		totalCredits: 92,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: true,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Aloysius Delleschi',
		userEmail: 'adelleschi1j@spotify.com',
		userPassword: 'W49TkY',
		userPhone: '(446) 5827172',
		userAddress: '417 Barby Point',
		userType: 'Student',
		sGPA: 1.4,
		sGradYear: 2022,
		sDOB: '5/30/1984',
		totalCredits: 56,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: true,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
	{
		userName: 'Bianca Keattch',
		userEmail: 'bkeattch1k@domainmarket.com',
		userPassword: 'i81Hb7fQNJ',
		userPhone: '(503) 3074292',
		userAddress: '65360 Charing Cross Point',
		userType: 'Student',
		sGPA: 2.9,
		sGradYear: 2023,
		sDOB: '10/9/1980',
		totalCredits: 76,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Wilburt Stears',
		userEmail: 'wstears1l@comsenz.com',
		userPassword: 'T9sfqyC4VJU',
		userPhone: '(349) 9801360',
		userAddress: '6 Fairfield Court',
		userType: 'Student',
		sGPA: 2.6,
		sGradYear: 2024,
		sDOB: '11/14/1990',
		totalCredits: 96,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Garey Frostdick',
		userEmail: 'gfrostdick1m@tripod.com',
		userPassword: 'O8poPW5itf',
		userPhone: '(461) 3734964',
		userAddress: '56 Moland Center',
		userType: 'Student',
		sGPA: 1.1,
		sGradYear: 2025,
		sDOB: '11/22/1992',
		totalCredits: 20,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: true,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Packston Hillock',
		userEmail: 'phillock1n@fotki.com',
		userPassword: '5fPIFib83',
		userPhone: '(583) 3221181',
		userAddress: '1 Springview Way',
		userType: 'Student',
		sGPA: 1.5,
		sGradYear: 2026,
		sDOB: '12/13/1982',
		totalCredits: 32,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Riobard Dundendale',
		userEmail: 'rdundendale1o@skype.com',
		userPassword: 'x36jkzrpsd',
		userPhone: '(345) 2108433',
		userAddress: '09512 Ridge Oak Parkway',
		userType: 'Student',
		sGPA: 1.8,
		sGradYear: 2017,
		sDOB: '4/11/2003',
		totalCredits: 108,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: true,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Bennie Macak',
		userEmail: 'bmacak1p@reverbnation.com',
		userPassword: 'JfnLN2',
		userPhone: '(101) 4903317',
		userAddress: '6 Kings Street',
		userType: 'Student',
		sGPA: 3.1,
		sGradYear: 2018,
		sDOB: '4/19/1981',
		totalCredits: 104,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Ulick Pocklington',
		userEmail: 'upocklington1q@parallels.com',
		userPassword: 'BtBLV7',
		userPhone: '(549) 3883772',
		userAddress: '06051 Bayside Parkway',
		userType: 'Student',
		sGPA: 2.0,
		sGradYear: 2019,
		sDOB: '9/20/1986',
		totalCredits: 44,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Quentin McKinnell',
		userEmail: 'qmckinnell1r@cam.ac.uk',
		userPassword: 'Q2ZaIDC',
		userPhone: '(832) 4989709',
		userAddress: '98908 Spohn Hill',
		userType: 'Student',
		sGPA: 1.9,
		sGradYear: 2020,
		sDOB: '1/31/1999',
		totalCredits: 56,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Lucio McFarland',
		userEmail: 'lmcfarland1s@flavors.me',
		userPassword: 'G6LcMV6Qr2Iq',
		userPhone: '(124) 9902641',
		userAddress: '38550 7th Lane',
		userType: 'Student',
		sGPA: 1.3,
		sGradYear: 2021,
		sDOB: '6/17/1985',
		totalCredits: 24,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'M.S',
		tutionCost: '$7000',
		hasMealPlan: true,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Smith Rocca',
		userEmail: 'srocca1t@multiply.com',
		userPassword: '088CT517K3my',
		userPhone: '(529) 9419461',
		userAddress: '58884 Sloan Parkway',
		userType: 'Student',
		sGPA: 3.6,
		sGradYear: 2022,
		sDOB: '7/13/2001',
		totalCredits: 100,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
	{
		userName: 'Demetre Bernardez',
		userEmail: 'dbernardez1u@wunderground.com',
		userPassword: 'kdRM05FoJt',
		userPhone: '(763) 6455804',
		userAddress: '72878 Spaight Place',
		userType: 'Student',
		sGPA: 4.0,
		sGradYear: 2023,
		sDOB: '2/7/1994',
		totalCredits: 20,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
	{
		userName: 'Thorndike Hamer',
		userEmail: 'thamer1v@hostgator.com',
		userPassword: 'veZRvE',
		userPhone: '(530) 8532257',
		userAddress: '7 Sloan Way',
		userType: 'Student',
		sGPA: 3.0,
		sGradYear: 2024,
		sDOB: '8/18/1991',
		totalCredits: 56,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Ardys Vawton',
		userEmail: 'avawton1w@wisc.edu',
		userPassword: 'CXx3PaUZ6Act',
		userPhone: '(547) 4777354',
		userAddress: '966 8th Crossing',
		userType: 'Student',
		sGPA: 1.4,
		sGradYear: 2025,
		sDOB: '11/7/1989',
		totalCredits: 96,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Fidela Gimenez',
		userEmail: 'fgimenez1x@tripod.com',
		userPassword: '4urOgSh3VKIB',
		userPhone: '(806) 5999747',
		userAddress: '824 Milwaukee Avenue',
		userType: 'Student',
		sGPA: 1.1,
		sGradYear: 2026,
		sDOB: '1/14/1997',
		totalCredits: 8,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Isabel Bunch',
		userEmail: 'ibunch1y@skype.com',
		userPassword: 'e3DIIpV5E',
		userPhone: '(862) 2582783',
		userAddress: '433 Farragut Alley',
		userType: 'Student',
		sGPA: 2.6,
		sGradYear: 2017,
		sDOB: '10/25/1999',
		totalCredits: 24,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Kimberli Brownsea',
		userEmail: 'kbrownsea1z@go.com',
		userPassword: 'PXftBOH',
		userPhone: '(104) 7743151',
		userAddress: '11 Schlimgen Court',
		userType: 'Student',
		sGPA: 3.8,
		sGradYear: 2018,
		sDOB: '11/1/2002',
		totalCredits: 72,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
	{
		userName: 'Sharlene Arlidge',
		userEmail: 'sarlidge20@mysql.com',
		userPassword: 's5MSI226D',
		userPhone: '(652) 8698366',
		userAddress: '60 Bluestem Place',
		userType: 'Student',
		sGPA: 3.8,
		sGradYear: 2019,
		sDOB: '2/18/1987',
		totalCredits: 120,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 11,
	},
	{
		userName: 'Estell Helwig',
		userEmail: 'ehelwig21@ask.com',
		userPassword: 'tWQDbkvIWz8',
		userPhone: '(492) 6021261',
		userAddress: '3 Waxwing Trail',
		userType: 'Student',
		sGPA: 2.7,
		sGradYear: 2020,
		sDOB: '2/4/1990',
		totalCredits: 44,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
	{
		userName: 'Marya Minchin',
		userEmail: 'mminchin22@blinklist.com',
		userPassword: 'jqLSs5',
		userPhone: '(289) 7593898',
		userAddress: '60455 Hoffman Lane',
		userType: 'Student',
		sGPA: 2.1,
		sGradYear: 2021,
		sDOB: '12/19/1992',
		totalCredits: 96,
		studentType: 'graduate',
		isFullTime: false,
		mastersOrPHD: 'PHD',
		tutionCost: '$7000',
		hasMealPlan: false,
		maxCreditsAllowed: 11,
		minCreditsAllowed: 4,
		currentCredits: 4,
	},
];

export default graduatePartTime;
