const graduateFullTime = [
	{
		"userName": "Lucita Howsley",
		"userEmail": "lhowsley0@slate.com",
		"userPassword": "GsylFFeIugyg",
		"userPhone": "(897) 3279365",
		"userAddress": "90202 Fulton Circle",
		"userType": "Student",
		"sGPA": 3.6,
		"sGradYear": 2017,
		"sDOB": "3/12/1985",
		"totalCredits": 24,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2000
	},
	{
		"userName": "Kerwin Lefeaver",
		"userEmail": "klefeaver1@blogtalkradio.com",
		"userPassword": "YmyFKF",
		"userPhone": "(465) 5560234",
		"userAddress": "0 Rockefeller Park",
		"userType": "Student",
		"sGPA": 2.4,
		"sGradYear": 2018,
		"sDOB": "3/7/1990",
		"totalCredits": 116,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2001
	},
	{
		"userName": "Monti Ducroe",
		"userEmail": "mducroe2@friendfeed.com",
		"userPassword": "dZ5aCqGDP",
		"userPhone": "(902) 5192141",
		"userAddress": "382 Eggendart Street",
		"userType": "Student",
		"sGPA": 1.5,
		"sGradYear": 2019,
		"sDOB": "3/29/1991",
		"totalCredits": 120,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2002
	},
	{
		"userName": "Ryley Pontefract",
		"userEmail": "rpontefract3@about.com",
		"userPassword": "fb9yJH6iqFT",
		"userPhone": "(802) 8475379",
		"userAddress": "85045 Haas Center",
		"userType": "Student",
		"sGPA": 2.9,
		"sGradYear": 2020,
		"sDOB": "11/1/1997",
		"totalCredits": 20,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "M.S",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2003
	},
	{
		"userName": "Ailina Droghan",
		"userEmail": "adroghan4@archive.org",
		"userPassword": "UftP2eV",
		"userPhone": "(335) 4146467",
		"userAddress": "51571 Kenwood Plaza",
		"userType": "Student",
		"sGPA": 2.8,
		"sGradYear": 2021,
		"sDOB": "7/19/1983",
		"totalCredits": 36,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2004
	},
	{
		"userName": "Catlee Blaxlande",
		"userEmail": "cblaxlande5@paypal.com",
		"userPassword": "4LrsKs",
		"userPhone": "(766) 3946215",
		"userAddress": "8 Weeping Birch Road",
		"userType": "Student",
		"sGPA": 2.8,
		"sGradYear": 2022,
		"sDOB": "7/26/1997",
		"totalCredits": 20,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2005
	},
	{
		"userName": "Kristoforo Karpman",
		"userEmail": "kkarpman6@patch.com",
		"userPassword": "oXVcNqJRSO",
		"userPhone": "(302) 6313669",
		"userAddress": "1 Coleman Point",
		"userType": "Student",
		"sGPA": 2.4,
		"sGradYear": 2023,
		"sDOB": "12/12/2000",
		"totalCredits": 76,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": true,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2006
	},
	{
		"userName": "Kath Olohan",
		"userEmail": "kolohan7@networksolutions.com",
		"userPassword": "RLSDi3",
		"userPhone": "(316) 8797554",
		"userAddress": "13 Pearson Street",
		"userType": "Student",
		"sGPA": 1.8,
		"sGradYear": 2024,
		"sDOB": "6/30/1980",
		"totalCredits": 76,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2007
	},
	{
		"userName": "Adelaide McAlarney",
		"userEmail": "amcalarney8@foxnews.com",
		"userPassword": "L6QkB3QS5TD",
		"userPhone": "(214) 6364329",
		"userAddress": "225 Pepper Wood Park",
		"userType": "Student",
		"sGPA": 3.1,
		"sGradYear": 2025,
		"sDOB": "11/17/1990",
		"totalCredits": 16,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": true,
		"isDorming": true,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2008
	},
	{
		"userName": "Cornela Decort",
		"userEmail": "cdecort9@wikipedia.org",
		"userPassword": "XljlN1",
		"userPhone": "(899) 8752664",
		"userAddress": "5443 Waubesa Parkway",
		"userType": "Student",
		"sGPA": 3.5,
		"sGradYear": 2026,
		"sDOB": "8/19/1992",
		"totalCredits": 104,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "M.S",
		"tutionCost": "$10,000",
		"hasMealPlan": true,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 12,
		"userID": 2009
	},
	{
		"userName": "Bertha Severwright",
		"userEmail": "bseverwrighta@rambler.ru",
		"userPassword": "tDlSrc778",
		"userPhone": "(384) 9323348",
		"userAddress": "194 Farragut Court",
		"userType": "Student",
		"sGPA": 3.7,
		"sGradYear": 2017,
		"sDOB": "10/16/1980",
		"totalCredits": 88,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "M.S",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2010
	},
	{
		"userName": "Jakob Franies",
		"userEmail": "jfraniesb@symantec.com",
		"userPassword": "qbqMty",
		"userPhone": "(856) 6052021",
		"userAddress": "643 Holy Cross Center",
		"userType": "Student",
		"sGPA": 2.9,
		"sGradYear": 2018,
		"sDOB": "7/1/1998",
		"totalCredits": 120,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": true,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2011
	},
	{
		"userName": "Daveta Rouby",
		"userEmail": "droubyc@xing.com",
		"userPassword": "ZTJ6NRR",
		"userPhone": "(558) 2623399",
		"userAddress": "7289 Longview Street",
		"userType": "Student",
		"sGPA": 3.4,
		"sGradYear": 2019,
		"sDOB": "8/3/1982",
		"totalCredits": 88,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2012
	},
	{
		"userName": "Blisse Castilljo",
		"userEmail": "bcastilljod@google.ca",
		"userPassword": "ocbYHZgao",
		"userPhone": "(467) 9193000",
		"userAddress": "22394 Red Cloud Crossing",
		"userType": "Student",
		"sGPA": 4,
		"sGradYear": 2020,
		"sDOB": "6/1/1981",
		"totalCredits": 32,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "M.S",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2013
	},
	{
		"userName": "Trula Scrowston",
		"userEmail": "tscrowstone@dailymotion.com",
		"userPassword": "fe2qpur",
		"userPhone": "(429) 8327935",
		"userAddress": "16 Meadow Vale Road",
		"userType": "Student",
		"sGPA": 1.9,
		"sGradYear": 2021,
		"sDOB": "7/28/1987",
		"totalCredits": 56,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2014
	},
	{
		"userName": "Sutton Holston",
		"userEmail": "sholstonf@yahoo.co.jp",
		"userPassword": "heXPfxB",
		"userPhone": "(319) 8054863",
		"userAddress": "1 Merchant Park",
		"userType": "Student",
		"sGPA": 1.6,
		"sGradYear": 2022,
		"sDOB": "10/3/1983",
		"totalCredits": 96,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "M.S",
		"tutionCost": "$10,000",
		"hasMealPlan": true,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2015
	},
	{
		"userName": "Antoine Goman",
		"userEmail": "agomang@vinaora.com",
		"userPassword": "G2G4zAJsa",
		"userPhone": "(798) 3921771",
		"userAddress": "66302 Declaration Junction",
		"userType": "Student",
		"sGPA": 2.6,
		"sGradYear": 2023,
		"sDOB": "9/18/1997",
		"totalCredits": 24,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2016
	},
	{
		"userName": "Charmine Madigan",
		"userEmail": "cmadiganh@latimes.com",
		"userPassword": "RTvdpYmF7PhB",
		"userPhone": "(817) 7196057",
		"userAddress": "47039 Clemons Crossing",
		"userType": "Student",
		"sGPA": 3,
		"sGradYear": 2024,
		"sDOB": "2/14/1980",
		"totalCredits": 32,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": true,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2017
	},
	{
		"userName": "Isac Gurry",
		"userEmail": "igurryi@mit.edu",
		"userPassword": "gPS0fA3",
		"userPhone": "(179) 2983510",
		"userAddress": "07 Mallard Lane",
		"userType": "Student",
		"sGPA": 1.4,
		"sGradYear": 2025,
		"sDOB": "11/7/1990",
		"totalCredits": 92,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2018
	},
	{
		"userName": "Gerda Toghill",
		"userEmail": "gtoghillj@discovery.com",
		"userPassword": "FpmvtYbc",
		"userPhone": "(620) 8340895",
		"userAddress": "32750 Ridgeway Lane",
		"userType": "Student",
		"sGPA": 1.6,
		"sGradYear": 2026,
		"sDOB": "6/30/1992",
		"totalCredits": 108,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2019
	},
	{
		"userName": "Robinia O'Henery",
		"userEmail": "roheneryk@twitter.com",
		"userPassword": "FPwnGqd",
		"userPhone": "(814) 5184900",
		"userAddress": "7549 Delladonna Road",
		"userType": "Student",
		"sGPA": 2.5,
		"sGradYear": 2017,
		"sDOB": "7/11/1990",
		"totalCredits": 52,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2020
	},
	{
		"userName": "Dominik Fishleigh",
		"userEmail": "dfishleighl@whitehouse.gov",
		"userPassword": "xTZ7DyaMYns",
		"userPhone": "(570) 4423968",
		"userAddress": "422 Springview Drive",
		"userType": "Student",
		"sGPA": 1.7,
		"sGradYear": 2018,
		"sDOB": "3/27/2001",
		"totalCredits": 8,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2021
	},
	{
		"userName": "Trudi Strathman",
		"userEmail": "tstrathmanm@issuu.com",
		"userPassword": "nSNWhENkiFk",
		"userPhone": "(718) 8339169",
		"userAddress": "020 Grim Hill",
		"userType": "Student",
		"sGPA": 3,
		"sGradYear": 2019,
		"sDOB": "8/28/1987",
		"totalCredits": 108,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "M.S",
		"tutionCost": "$10,000",
		"hasMealPlan": true,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 12,
		"userID": 2022
	},
	{
		"userName": "Taylor Hawkin",
		"userEmail": "thawkinn@army.mil",
		"userPassword": "9q0iSP",
		"userPhone": "(832) 6036726",
		"userAddress": "87154 Shasta Trail",
		"userType": "Student",
		"sGPA": 1.8,
		"sGradYear": 2020,
		"sDOB": "8/18/1988",
		"totalCredits": 44,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "M.S",
		"tutionCost": "$10,000",
		"hasMealPlan": false,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2023
	},
	{
		"userName": "Putnam Caulder",
		"userEmail": "pcauldero@paypal.com",
		"userPassword": "NTqFev1OSY74",
		"userPhone": "(815) 9643216",
		"userAddress": "7 Esch Alley",
		"userType": "Student",
		"sGPA": 3.5,
		"sGradYear": 2021,
		"sDOB": "9/24/1994",
		"totalCredits": 88,
		"studentType": "graduate",
		"isFullTime": true,
		"mastersOrPHD": "PHD",
		"tutionCost": "$10,000",
		"hasMealPlan": true,
		"isDorming": false,
		"maxCreditsAllowed": 16,
		"minCreditsAllowed": 12,
		"currentCredits": 16,
		"userID": 2024
	}
];
export default graduateFullTime;
