const graduatePartTime = [
	{
		"userName": "Claribel Tither",
		"userEmail": "CTither@GuptaUni.edu",
		"userPassword": "eFie82f",
		"userPhone": "(711) 4118387",
		"userAddress": "06201 Banding Circle",
		"userType": "Student",
		"sGPA": 2.1,
		"sGradYear": 2017,
		"sDOB": "5/13/2003",
		"totalCredits": 40,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1000
	},
	{
		"userName": "Hewitt Serrels",
		"userEmail": "HSerrels@GuptaUni.edu",
		"userPassword": "l3CeEmV",
		"userPhone": "(624) 6757176",
		"userAddress": "4 Calypso Plaza",
		"userType": "Student",
		"sGPA": 2.6,
		"sGradYear": 2018,
		"sDOB": "1/11/2000",
		"totalCredits": 111,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1001
	},
	{
		"userName": "Torrie Hackly",
		"userEmail": "THackly@GuptaUni.edu",
		"userPassword": "LxitIEU9ez0",
		"userPhone": "(119) 6677817",
		"userAddress": "9391 Mayer Avenue",
		"userType": "Student",
		"sGPA": 1.3,
		"sGradYear": 2019,
		"sDOB": "2/15/1988",
		"totalCredits": 111,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1002
	},
	{
		"userName": "Micheil Isaac",
		"userEmail": "MIsaac@GuptaUni.edu",
		"userPassword": "hxuuVhAmr2DV",
		"userPhone": "(468) 8834273",
		"userAddress": "1123 Forest Dale Road",
		"userType": "Student",
		"sGPA": 1.4,
		"sGradYear": 2020,
		"sDOB": "4/30/1996",
		"totalCredits": 48,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1003
	},
	{
		"userName": "Averyl McConachie",
		"userEmail": "AMcConac@GuptaUni.edu",
		"userPassword": "qZNTpaZg",
		"userPhone": "(649) 3257321",
		"userAddress": "09280 Browning Plaza",
		"userType": "Student",
		"sGPA": 3.6,
		"sGradYear": 2021,
		"sDOB": "1/18/1986",
		"totalCredits": 120,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1004
	},
	{
		"userName": "Lauren Tomczykiewicz",
		"userEmail": "LTomczyk@GuptaUni.edu",
		"userPassword": "ONud0OP",
		"userPhone": "(140) 7686605",
		"userAddress": "054 Spaight Trail",
		"userType": "Student",
		"sGPA": 2.2,
		"sGradYear": 2022,
		"sDOB": "2/18/2000",
		"totalCredits": 56,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1005
	},
	{
		"userName": "Berk Bwye",
		"userEmail": "BBwye@GuptaUni.edu",
		"userPassword": "MKqM90p",
		"userPhone": "(412) 9368120",
		"userAddress": "5 Manley Avenue",
		"userType": "Student",
		"sGPA": 1.9,
		"sGradYear": 2023,
		"sDOB": "11/19/1992",
		"totalCredits": 40,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1006
	},
	{
		"userName": "Orv Castagnier",
		"userEmail": "OCastagn@GuptaUni.edu",
		"userPassword": "H36wVM",
		"userPhone": "(632) 2352461",
		"userAddress": "90 Amoth Trail",
		"userType": "Student",
		"sGPA": 1.6,
		"sGradYear": 2024,
		"sDOB": "3/19/1999",
		"totalCredits": 44,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1007
	},
	{
		"userName": "Aloise Dimmack",
		"userEmail": "ADimmack@GuptaUni.edu",
		"userPassword": "MMAwky3sTA38",
		"userPhone": "(264) 4571938",
		"userAddress": "90 Alpine Road",
		"userType": "Student",
		"sGPA": 3.9,
		"sGradYear": 2025,
		"sDOB": "12/27/1994",
		"totalCredits": 11,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1008
	},
	{
		"userName": "Sebastiano Glyde",
		"userEmail": "SGlyde@GuptaUni.edu",
		"userPassword": "tlvrgWDSn6wO",
		"userPhone": "(309) 1161511",
		"userAddress": "676 Kings Crossing",
		"userType": "Student",
		"sGPA": 1.7,
		"sGradYear": 2026,
		"sDOB": "5/6/1998",
		"totalCredits": 48,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1009
	},
	{
		"userName": "Mac Gladden",
		"userEmail": "MGladden@GuptaUni.edu",
		"userPassword": "QmG8KV",
		"userPhone": "(138) 3309901",
		"userAddress": "248 Bartillon Alley",
		"userType": "Student",
		"sGPA": 2.8,
		"sGradYear": 2017,
		"sDOB": "7/15/1988",
		"totalCredits": 24,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1010
	},
	{
		"userName": "Jaclyn Linsay",
		"userEmail": "JLinsay@GuptaUni.edu",
		"userPassword": "DS9yJ5L",
		"userPhone": "(181) 4640717",
		"userAddress": "809 Iowa Terrace",
		"userType": "Student",
		"sGPA": 1.4,
		"sGradYear": 2018,
		"sDOB": "7/28/1997",
		"totalCredits": 96,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1011
	},
	{
		"userName": "Cody Southworth",
		"userEmail": "CSouthwo@GuptaUni.edu",
		"userPassword": "oEaNSQq",
		"userPhone": "(556) 5362730",
		"userAddress": "84426 Duke Crossing",
		"userType": "Student",
		"sGPA": 2.1,
		"sGradYear": 2019,
		"sDOB": "12/2/1985",
		"totalCredits": 112,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1012
	},
	{
		"userName": "Coretta Tickle",
		"userEmail": "CTickle@GuptaUni.edu",
		"userPassword": "FnnDDqkjk",
		"userPhone": "(915) 8543465",
		"userAddress": "79 Bonner Circle",
		"userType": "Student",
		"sGPA": 2.3,
		"sGradYear": 2020,
		"sDOB": "1/19/1993",
		"totalCredits": 112,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1013
	},
	{
		"userName": "Nancee Judron",
		"userEmail": "NJudron@GuptaUni.edu",
		"userPassword": "dD1nsdF",
		"userPhone": "(235) 2872710",
		"userAddress": "4 Vernon Parkway",
		"userType": "Student",
		"sGPA": 1.6,
		"sGradYear": 2021,
		"sDOB": "9/5/1981",
		"totalCredits": 64,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1014
	},
	{
		"userName": "Collete Chung",
		"userEmail": "CChung@GuptaUni.edu",
		"userPassword": "VrMj9gKdt",
		"userPhone": "(577) 4235810",
		"userAddress": "71 Hallows Crossing",
		"userType": "Student",
		"sGPA": 3.1,
		"sGradYear": 2022,
		"sDOB": "1/15/1985",
		"totalCredits": 36,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1015
	},
	{
		"userName": "Rorke Quesne",
		"userEmail": "RQuesne@GuptaUni.edu",
		"userPassword": "Hyppx2E",
		"userPhone": "(420) 5449023",
		"userAddress": "7 Susan Drive",
		"userType": "Student",
		"sGPA": 2.6,
		"sGradYear": 2023,
		"sDOB": "6/10/1992",
		"totalCredits": 80,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1016
	},
	{
		"userName": "Florry Ogilvie",
		"userEmail": "FOgilvie@GuptaUni.edu",
		"userPassword": "1wINrChPU0",
		"userPhone": "(513) 5764967",
		"userAddress": "54 North Pass",
		"userType": "Student",
		"sGPA": 3,
		"sGradYear": 2024,
		"sDOB": "3/12/1984",
		"totalCredits": 44,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1017
	},
	{
		"userName": "Farrel Vobes",
		"userEmail": "FVobes@GuptaUni.edu",
		"userPassword": "bltuW90Ok",
		"userPhone": "(507) 9647953",
		"userAddress": "84712 Reindahl Plaza",
		"userType": "Student",
		"sGPA": 1.7,
		"sGradYear": 2025,
		"sDOB": "5/17/2000",
		"totalCredits": 68,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1018
	},
	{
		"userName": "Marlowe Cockayme",
		"userEmail": "MCockaym@GuptaUni.edu",
		"userPassword": "OXKWAAk",
		"userPhone": "(969) 9849350",
		"userAddress": "8 Evergreen Pass",
		"userType": "Student",
		"sGPA": 1.6,
		"sGradYear": 2026,
		"sDOB": "6/9/1984",
		"totalCredits": 44,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1019
	},
	{
		"userName": "Mimi Blades",
		"userEmail": "MBlades@GuptaUni.edu",
		"userPassword": "rwCT4r",
		"userPhone": "(372) 9862947",
		"userAddress": "10082 Springview Court",
		"userType": "Student",
		"sGPA": 3.7,
		"sGradYear": 2017,
		"sDOB": "3/6/1998",
		"totalCredits": 80,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1020
	},
	{
		"userName": "Ambrose Tollet",
		"userEmail": "ATollet@GuptaUni.edu",
		"userPassword": "yAZBE5g09IK",
		"userPhone": "(486) 2629846",
		"userAddress": "51 Village Green Trail",
		"userType": "Student",
		"sGPA": 2.8,
		"sGradYear": 2018,
		"sDOB": "7/23/1984",
		"totalCredits": 80,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1021
	},
	{
		"userName": "Bernardina Rosengren",
		"userEmail": "BRosengr@GuptaUni.edu",
		"userPassword": "zqRrV2s",
		"userPhone": "(594) 9191991",
		"userAddress": "873 Cherokee Alley",
		"userType": "Student",
		"sGPA": 1.2,
		"sGradYear": 2019,
		"sDOB": "2/25/1995",
		"totalCredits": 60,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1022
	},
	{
		"userName": "Viola Dumper",
		"userEmail": "VDumper@GuptaUni.edu",
		"userPassword": "nvJYXVq2uz",
		"userPhone": "(993) 9294082",
		"userAddress": "25 Lakewood Gardens Alley",
		"userType": "Student",
		"sGPA": 3,
		"sGradYear": 2020,
		"sDOB": "7/7/1998",
		"totalCredits": 100,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1023
	},
	{
		"userName": "Giselbert Banfill",
		"userEmail": "GBanfill@GuptaUni.edu",
		"userPassword": "zUjwXayd",
		"userPhone": "(941) 8575993",
		"userAddress": "03 Butterfield Avenue",
		"userType": "Student",
		"sGPA": 2.9,
		"sGradYear": 2021,
		"sDOB": "4/3/1996",
		"totalCredits": 96,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1024
	},
	{
		"userName": "Wilow Coggon",
		"userEmail": "WCoggon@GuptaUni.edu",
		"userPassword": "yYCm7nQI",
		"userPhone": "(461) 4943298",
		"userAddress": "0548 Mariners Cove Center",
		"userType": "Student",
		"sGPA": 3.4,
		"sGradYear": 2022,
		"sDOB": "10/5/2000",
		"totalCredits": 32,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1025
	},
	{
		"userName": "Izabel Dumelow",
		"userEmail": "IDumelow@GuptaUni.edu",
		"userPassword": "SUtPeTC2RL",
		"userPhone": "(117) 1099062",
		"userAddress": "64288 4th Place",
		"userType": "Student",
		"sGPA": 3.5,
		"sGradYear": 2023,
		"sDOB": "7/18/1990",
		"totalCredits": 32,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1026
	},
	{
		"userName": "Halli Aynold",
		"userEmail": "HAynold@GuptaUni.edu",
		"userPassword": "XRUXnbjmWneL",
		"userPhone": "(987) 8228945",
		"userAddress": "6539 Florence Center",
		"userType": "Student",
		"sGPA": 1.3,
		"sGradYear": 2024,
		"sDOB": "6/2/2000",
		"totalCredits": 52,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1027
	},
	{
		"userName": "Deanne Barth",
		"userEmail": "DBarth@GuptaUni.edu",
		"userPassword": "KGe6tgFKQ",
		"userPhone": "(799) 2776846",
		"userAddress": "458 Eastlawn Lane",
		"userType": "Student",
		"sGPA": 2.2,
		"sGradYear": 2025,
		"sDOB": "6/1/2001",
		"totalCredits": 24,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1028
	},
	{
		"userName": "Ikey Crunkhurn",
		"userEmail": "ICrunkhu@GuptaUni.edu",
		"userPassword": "oemmClgyFWo",
		"userPhone": "(663) 4035249",
		"userAddress": "62882 Charing Cross Alley",
		"userType": "Student",
		"sGPA": 1.6,
		"sGradYear": 2026,
		"sDOB": "11/1/1997",
		"totalCredits": 96,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1029
	},
	{
		"userName": "Patrizia Taffurelli",
		"userEmail": "PTaffure@GuptaUni.edu",
		"userPassword": "zIJMmCh",
		"userPhone": "(421) 9802445",
		"userAddress": "778 Londonderry Point",
		"userType": "Student",
		"sGPA": 3.1,
		"sGradYear": 2017,
		"sDOB": "4/28/1993",
		"totalCredits": 36,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1030
	},
	{
		"userName": "Rowena Jesse",
		"userEmail": "RJesse@GuptaUni.edu",
		"userPassword": "AQEsgwFKp",
		"userPhone": "(280) 6238373",
		"userAddress": "98 Holy Cross Court",
		"userType": "Student",
		"sGPA": 2.3,
		"sGradYear": 2018,
		"sDOB": "11/4/1992",
		"totalCredits": 96,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1031
	},
	{
		"userName": "Christi Diddams",
		"userEmail": "CDiddams@GuptaUni.edu",
		"userPassword": "pa7xsqgc",
		"userPhone": "(990) 2883977",
		"userAddress": "23 Orin Street",
		"userType": "Student",
		"sGPA": 2.8,
		"sGradYear": 2019,
		"sDOB": "11/29/1985",
		"totalCredits": 24,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1032
	},
	{
		"userName": "Auguste Laffling",
		"userEmail": "ALafflin@GuptaUni.edu",
		"userPassword": "TZMqbT",
		"userPhone": "(502) 3893227",
		"userAddress": "568 Dottie Center",
		"userType": "Student",
		"sGPA": 2.4,
		"sGradYear": 2020,
		"sDOB": "1/2/1994",
		"totalCredits": 96,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1033
	},
	{
		"userName": "Caroline Kevern",
		"userEmail": "CKevern@GuptaUni.edu",
		"userPassword": "c2VRmOHtFR",
		"userPhone": "(952) 4075098",
		"userAddress": "5784 Blue Bill Park Park",
		"userType": "Student",
		"sGPA": 3.8,
		"sGradYear": 2021,
		"sDOB": "6/17/1990",
		"totalCredits": 104,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1034
	},
	{
		"userName": "Lorain People",
		"userEmail": "LPeople@GuptaUni.edu",
		"userPassword": "H46zgzq",
		"userPhone": "(719) 6522430",
		"userAddress": "03959 Emmet Alley",
		"userType": "Student",
		"sGPA": 2.4,
		"sGradYear": 2022,
		"sDOB": "3/13/1988",
		"totalCredits": 56,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1035
	},
	{
		"userName": "Lorilyn Woltman",
		"userEmail": "LWoltman@GuptaUni.edu",
		"userPassword": "IJvxZssns",
		"userPhone": "(139) 8185605",
		"userAddress": "85 Brentwood Avenue",
		"userType": "Student",
		"sGPA": 3.4,
		"sGradYear": 2023,
		"sDOB": "12/1/1981",
		"totalCredits": 120,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1036
	},
	{
		"userName": "Bunnie Barczynski",
		"userEmail": "BBarczyn@GuptaUni.edu",
		"userPassword": "jtngD9E",
		"userPhone": "(842) 3710457",
		"userAddress": "78 Thompson Trail",
		"userType": "Student",
		"sGPA": 3,
		"sGradYear": 2024,
		"sDOB": "3/6/1983",
		"totalCredits": 68,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1037
	},
	{
		"userName": "Angel Lowdham",
		"userEmail": "ALowdham@GuptaUni.edu",
		"userPassword": "DXQdo1d",
		"userPhone": "(324) 3134295",
		"userAddress": "70 Marquette Park",
		"userType": "Student",
		"sGPA": 2.1,
		"sGradYear": 2025,
		"sDOB": "5/14/1989",
		"totalCredits": 68,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1038
	},
	{
		"userName": "Diahann Rootes",
		"userEmail": "DRootes@GuptaUni.edu",
		"userPassword": "FcVu46Q",
		"userPhone": "(470) 4362975",
		"userAddress": "4 Haas Way",
		"userType": "Student",
		"sGPA": 2.2,
		"sGradYear": 2026,
		"sDOB": "10/24/1992",
		"totalCredits": 72,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1039
	},
	{
		"userName": "Tye Bock",
		"userEmail": "TBock@GuptaUni.edu",
		"userPassword": "wzNVSLaKJHTA",
		"userPhone": "(534) 7284335",
		"userAddress": "4602 Burning Wood Plaza",
		"userType": "Student",
		"sGPA": 1.8,
		"sGradYear": 2017,
		"sDOB": "6/9/1986",
		"totalCredits": 80,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1040
	},
	{
		"userName": "Pippa Smorthwaite",
		"userEmail": "PSmorthw@GuptaUni.edu",
		"userPassword": "03s46pzur5",
		"userPhone": "(690) 3772667",
		"userAddress": "785 Dunning Pass",
		"userType": "Student",
		"sGPA": 2.8,
		"sGradYear": 2018,
		"sDOB": "9/13/1989",
		"totalCredits": 52,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1041
	},
	{
		"userName": "Greggory Quilter",
		"userEmail": "GQuilter@GuptaUni.edu",
		"userPassword": "igiuNTi0",
		"userPhone": "(978) 5398363",
		"userAddress": "00 7th Plaza",
		"userType": "Student",
		"sGPA": 1.2,
		"sGradYear": 2019,
		"sDOB": "12/11/1984",
		"totalCredits": 24,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1042
	},
	{
		"userName": "Audry Avraam",
		"userEmail": "AAvraam@GuptaUni.edu",
		"userPassword": "kxrI5EE",
		"userPhone": "(701) 6732987",
		"userAddress": "21 Myrtle Hill",
		"userType": "Student",
		"sGPA": 3.9,
		"sGradYear": 2020,
		"sDOB": "8/15/1995",
		"totalCredits": 72,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1043
	},
	{
		"userName": "Arlee Catling",
		"userEmail": "ACatling@GuptaUni.edu",
		"userPassword": "JkrWVEkGboLf",
		"userPhone": "(432) 4246079",
		"userAddress": "2 Fordem Way",
		"userType": "Student",
		"sGPA": 3.1,
		"sGradYear": 2021,
		"sDOB": "12/5/1993",
		"totalCredits": 8,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1044
	},
	{
		"userName": "Etan Hardison",
		"userEmail": "EHardiso@GuptaUni.edu",
		"userPassword": "dO6ep4uQN",
		"userPhone": "(497) 4147198",
		"userAddress": "47435 Continental Circle",
		"userType": "Student",
		"sGPA": 2,
		"sGradYear": 2022,
		"sDOB": "9/25/1997",
		"totalCredits": 20,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1045
	},
	{
		"userName": "Wolf Spores",
		"userEmail": "WSpores@GuptaUni.edu",
		"userPassword": "2X2GW5",
		"userPhone": "(139) 8003533",
		"userAddress": "81 Rutledge Road",
		"userType": "Student",
		"sGPA": 2.1,
		"sGradYear": 2023,
		"sDOB": "10/24/1995",
		"totalCredits": 104,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1046
	},
	{
		"userName": "Lettie Meeson",
		"userEmail": "LMeeson@GuptaUni.edu",
		"userPassword": "isSciNVgn89",
		"userPhone": "(297) 1814698",
		"userAddress": "29022 Wayridge Alley",
		"userType": "Student",
		"sGPA": 1.2,
		"sGradYear": 2024,
		"sDOB": "11/3/1992",
		"totalCredits": 36,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1047
	},
	{
		"userName": "Ibby Bohden",
		"userEmail": "IBohden@GuptaUni.edu",
		"userPassword": "8oeQN5LI6gJ",
		"userPhone": "(822) 7957323",
		"userAddress": "6603 Blaine Crossing",
		"userType": "Student",
		"sGPA": 3.1,
		"sGradYear": 2025,
		"sDOB": "1/9/1984",
		"totalCredits": 92,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1048
	},
	{
		"userName": "Garrard Sobczak",
		"userEmail": "GSobczak@GuptaUni.edu",
		"userPassword": "zazHxM",
		"userPhone": "(180) 6953119",
		"userAddress": "81929 Maywood Lane",
		"userType": "Student",
		"sGPA": 3.2,
		"sGradYear": 2026,
		"sDOB": "7/6/1997",
		"totalCredits": 100,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1049
	},
	{
		"userName": "Giffy Berthod",
		"userEmail": "GBerthod@GuptaUni.edu",
		"userPassword": "21JO7hk4S",
		"userPhone": "(604) 2581569",
		"userAddress": "5375 School Center",
		"userType": "Student",
		"sGPA": 3.9,
		"sGradYear": 2017,
		"sDOB": "2/11/1995",
		"totalCredits": 112,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1050
	},
	{
		"userName": "Carree Bennike",
		"userEmail": "CBennike@GuptaUni.edu",
		"userPassword": "XSNPA08X",
		"userPhone": "(314) 4052911",
		"userAddress": "645 Arizona Junction",
		"userType": "Student",
		"sGPA": 1.2,
		"sGradYear": 2018,
		"sDOB": "8/14/2000",
		"totalCredits": 11,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1051
	},
	{
		"userName": "Eyde Twaite",
		"userEmail": "ETwaite@GuptaUni.edu",
		"userPassword": "GiyioXMjGsuq",
		"userPhone": "(178) 1812961",
		"userAddress": "397 South Way",
		"userType": "Student",
		"sGPA": 3.4,
		"sGradYear": 2019,
		"sDOB": "9/10/1985",
		"totalCredits": 84,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1052
	},
	{
		"userName": "Astrid Chasles",
		"userEmail": "AChasles@GuptaUni.edu",
		"userPassword": "coFyY0",
		"userPhone": "(372) 9601110",
		"userAddress": "7 Crescent Oaks Court",
		"userType": "Student",
		"sGPA": 2.4,
		"sGradYear": 2020,
		"sDOB": "9/12/1992",
		"totalCredits": 8,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1053
	},
	{
		"userName": "Cleo Marshall",
		"userEmail": "CMarshal@GuptaUni.edu",
		"userPassword": "xgtuZMFnpC",
		"userPhone": "(226) 5595114",
		"userAddress": "1 Springs Trail",
		"userType": "Student",
		"sGPA": 2.1,
		"sGradYear": 2021,
		"sDOB": "1/4/2001",
		"totalCredits": 92,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1054
	},
	{
		"userName": "Andonis Biddle",
		"userEmail": "ABiddle@GuptaUni.edu",
		"userPassword": "W49TkY",
		"userPhone": "(446) 5827172",
		"userAddress": "417 Barby Point",
		"userType": "Student",
		"sGPA": 1.4,
		"sGradYear": 2022,
		"sDOB": "5/30/1984",
		"totalCredits": 56,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1055
	},
	{
		"userName": "Darcy Olrenshaw",
		"userEmail": "DOlrensh@GuptaUni.edu",
		"userPassword": "i81Hb7fQNJ",
		"userPhone": "(503) 3074292",
		"userAddress": "65360 Charing Cross Point",
		"userType": "Student",
		"sGPA": 2.9,
		"sGradYear": 2023,
		"sDOB": "10/9/1980",
		"totalCredits": 76,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1056
	},
	{
		"userName": "Aron Corrigan",
		"userEmail": "ACorriga@GuptaUni.edu",
		"userPassword": "T9sfqyC4VJU",
		"userPhone": "(349) 9801360",
		"userAddress": "6 Fairfield Court",
		"userType": "Student",
		"sGPA": 2.6,
		"sGradYear": 2024,
		"sDOB": "11/14/1990",
		"totalCredits": 96,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1057
	},
	{
		"userName": "Halli Withringten",
		"userEmail": "HWithrin@GuptaUni.edu",
		"userPassword": "O8poPW5itf",
		"userPhone": "(461) 3734964",
		"userAddress": "56 Moland Center",
		"userType": "Student",
		"sGPA": 1.1,
		"sGradYear": 2025,
		"sDOB": "11/22/1992",
		"totalCredits": 20,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1058
	},
	{
		"userName": "Gerry Giacomucci",
		"userEmail": "GGiacomu@GuptaUni.edu",
		"userPassword": "5fPIFib83",
		"userPhone": "(583) 3221181",
		"userAddress": "1 Springview Way",
		"userType": "Student",
		"sGPA": 1.5,
		"sGradYear": 2026,
		"sDOB": "12/13/1982",
		"totalCredits": 32,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1059
	},
	{
		"userName": "Cristie Shellum",
		"userEmail": "CShellum@GuptaUni.edu",
		"userPassword": "x36jkzrpsd",
		"userPhone": "(345) 2108433",
		"userAddress": "09512 Ridge Oak Parkway",
		"userType": "Student",
		"sGPA": 1.8,
		"sGradYear": 2017,
		"sDOB": "4/11/2003",
		"totalCredits": 108,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1060
	},
	{
		"userName": "Sigismund Cissell",
		"userEmail": "SCissell@GuptaUni.edu",
		"userPassword": "JfnLN2",
		"userPhone": "(101) 4903317",
		"userAddress": "6 Kings Street",
		"userType": "Student",
		"sGPA": 3.1,
		"sGradYear": 2018,
		"sDOB": "4/19/1981",
		"totalCredits": 104,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1061
	},
	{
		"userName": "Antonella Forton",
		"userEmail": "AForton@GuptaUni.edu",
		"userPassword": "BtBLV7",
		"userPhone": "(549) 3883772",
		"userAddress": "06051 Bayside Parkway",
		"userType": "Student",
		"sGPA": 2,
		"sGradYear": 2019,
		"sDOB": "9/20/1986",
		"totalCredits": 44,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1062
	},
	{
		"userName": "Nance Domerq",
		"userEmail": "NDomerq@GuptaUni.edu",
		"userPassword": "Q2ZaIDC",
		"userPhone": "(832) 4989709",
		"userAddress": "98908 Spohn Hill",
		"userType": "Student",
		"sGPA": 1.9,
		"sGradYear": 2020,
		"sDOB": "1/31/1999",
		"totalCredits": 56,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1063
	},
	{
		"userName": "Mary Windeatt",
		"userEmail": "MWindeat@GuptaUni.edu",
		"userPassword": "G6LcMV6Qr2Iq",
		"userPhone": "(124) 9902641",
		"userAddress": "38550 7th Lane",
		"userType": "Student",
		"sGPA": 1.3,
		"sGradYear": 2021,
		"sDOB": "6/17/1985",
		"totalCredits": 24,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "M.S",
		"tutionCost": "$7,000 ",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1064
	},
	{
		"userName": "Warren Emmanuele",
		"userEmail": "WEmmanue@GuptaUni.edu",
		"userPassword": "088CT517K3my",
		"userPhone": "(529) 9419461",
		"userAddress": "58884 Sloan Parkway",
		"userType": "Student",
		"sGPA": 3.6,
		"sGradYear": 2022,
		"sDOB": "7/13/2001",
		"totalCredits": 100,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1065
	},
	{
		"userName": "Yule Johnes",
		"userEmail": "YJohnes@GuptaUni.edu",
		"userPassword": "kdRM05FoJt",
		"userPhone": "(763) 6455804",
		"userAddress": "72878 Spaight Place",
		"userType": "Student",
		"sGPA": 4,
		"sGradYear": 2023,
		"sDOB": "2/7/1994",
		"totalCredits": 20,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1066
	},
	{
		"userName": "Stefa Lorenzo",
		"userEmail": "SLorenzo@GuptaUni.edu",
		"userPassword": "veZRvE",
		"userPhone": "(530) 8532257",
		"userAddress": "7 Sloan Way",
		"userType": "Student",
		"sGPA": 3,
		"sGradYear": 2024,
		"sDOB": "8/18/1991",
		"totalCredits": 56,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1067
	},
	{
		"userName": "Pierrette Crownshaw",
		"userEmail": "PCrownsh@GuptaUni.edu",
		"userPassword": "CXx3PaUZ6Act",
		"userPhone": "(547) 4777354",
		"userAddress": "966 8th Crossing",
		"userType": "Student",
		"sGPA": 1.4,
		"sGradYear": 2025,
		"sDOB": "11/7/1989",
		"totalCredits": 96,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1068
	},
	{
		"userName": "Jolie Ivimey",
		"userEmail": "JIvimey@GuptaUni.edu",
		"userPassword": "4urOgSh3VKIB",
		"userPhone": "(806) 5999747",
		"userAddress": "824 Milwaukee Avenue",
		"userType": "Student",
		"sGPA": 1.1,
		"sGradYear": 2026,
		"sDOB": "1/14/1997",
		"totalCredits": 8,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1069
	},
	{
		"userName": "Mar O'Brogan",
		"userEmail": "MO'Broga@GuptaUni.edu",
		"userPassword": "e3DIIpV5E",
		"userPhone": "(862) 2582783",
		"userAddress": "433 Farragut Alley",
		"userType": "Student",
		"sGPA": 2.6,
		"sGradYear": 2017,
		"sDOB": "10/25/1999",
		"totalCredits": 24,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1070
	},
	{
		"userName": "Josias Flockhart",
		"userEmail": "JFlockha@GuptaUni.edu",
		"userPassword": "PXftBOH",
		"userPhone": "(104) 7743151",
		"userAddress": "11 Schlimgen Court",
		"userType": "Student",
		"sGPA": 3.8,
		"sGradYear": 2018,
		"sDOB": "11/1/2002",
		"totalCredits": 72,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1071
	},
	{
		"userName": "Mathias Steketee",
		"userEmail": "MStekete@GuptaUni.edu",
		"userPassword": "s5MSI226D",
		"userPhone": "(652) 8698366",
		"userAddress": "60 Bluestem Place",
		"userType": "Student",
		"sGPA": 3.8,
		"sGradYear": 2019,
		"sDOB": "2/18/1987",
		"totalCredits": 120,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 1072
	},
	{
		"userName": "Ignacius Hayter",
		"userEmail": "IHayter@GuptaUni.edu",
		"userPassword": "tWQDbkvIWz8",
		"userPhone": "(492) 6021261",
		"userAddress": "3 Waxwing Trail",
		"userType": "Student",
		"sGPA": 2.7,
		"sGradYear": 2020,
		"sDOB": "2/4/1990",
		"totalCredits": 44,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1073
	},
	{
		"userName": "Sascha Yegorev",
		"userEmail": "SYegorev@GuptaUni.edu",
		"userPassword": "jqLSs5",
		"userPhone": "(289) 7593898",
		"userAddress": "60455 Hoffman Lane",
		"userType": "Student",
		"sGPA": 2.1,
		"sGradYear": 2021,
		"sDOB": "12/19/1992",
		"totalCredits": 96,
		"studentType": "graduate",
		"isFullTime": false,
		"mastersOrPHD": "PHD",
		"tutionCost": "$7,000 ",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 1074
	}
];

export default graduatePartTime;
