const partTimeFaculty = [
	{
		userName: 'Hiram Fowkes',
		userEmail: 'hfowkes0@scientificamerican.com',
		userPassword: 'yp4NaCvIy',
		userPhone: '+52 (512) 312-6162',
		userAddress: '10306 Colorado Pass',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'JaX346',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 1,
	},
	{
		userName: 'Cristina Auden',
		userEmail: 'cauden1@gnu.org',
		userPassword: 'NNiDcX',
		userPhone: '+84 (610) 192-1458',
		userAddress: '66719 South Hill',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'hAk793',
		isFullTime: false,
		hourlyPay: '$19',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 14,
	},
	{
		userName: 'Justen Vallantine',
		userEmail: 'jvallantine2@amazon.com',
		userPassword: 'WdPqLZydhM',
		userPhone: '+63 (140) 431-7620',
		userAddress: '70785 Northview Court',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'ASn896',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 9,
	},
	{
		userName: 'Gabriella Rawood',
		userEmail: 'grawood3@issuu.com',
		userPassword: 'f60VxBai',
		userPhone: '+45 (320) 976-6007',
		userAddress: '25302 Forest Pass',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'xHC247',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 9,
	},
	{
		userName: 'Cassius McKeighen',
		userEmail: 'cmckeighen4@icio.us',
		userPassword: 'IOzdHn',
		userPhone: '+20 (614) 581-3904',
		userAddress: '08191 Briar Crest Trail',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'Vmb920',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 10,
	},
	{
		userName: 'Margi McBayne',
		userEmail: 'mmcbayne5@patch.com',
		userPassword: 'Pl3OJGq19qVy',
		userPhone: '+1 (328) 633-2502',
		userAddress: '39210 High Crossing Terrace',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'yQY261',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 13,
	},
	{
		userName: 'Timmy Drinkhill',
		userEmail: 'tdrinkhill6@goodreads.com',
		userPassword: 'XAhWVM2n',
		userPhone: '+351 (332) 478-6530',
		userAddress: '15792 Kropf Point',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'Mqv060',
		isFullTime: false,
		hourlyPay: '$19',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 1,
	},
	{
		userName: 'Perle Tregona',
		userEmail: 'ptregona7@fda.gov',
		userPassword: 'CiIlTadGH7q',
		userPhone: '+62 (807) 188-6560',
		userAddress: '49774 Porter Trail',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Hpe747',
		isFullTime: false,
		hourlyPay: '$19',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 3,
	},
	{
		userName: 'Arlen Mixter',
		userEmail: 'amixter8@walmart.com',
		userPassword: 'VkQhWQTr0jCl',
		userPhone: '+62 (683) 428-3461',
		userAddress: '14922 Blaine Plaza',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'lCA769',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 15,
	},
	{
		userName: 'Sigfrid Klausewitz',
		userEmail: 'sklausewitz9@homestead.com',
		userPassword: '9OyExVnY',
		userPhone: '+56 (196) 650-2263',
		userAddress: '452 Pleasure Avenue',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'KPI779',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 13,
	},
	{
		userName: 'Mada Lias',
		userEmail: 'mliasa@people.com.cn',
		userPassword: 'bM9JfMWMWe',
		userPhone: '+51 (761) 143-7079',
		userAddress: '04 Sloan Plaza',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'MRU817',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 10,
	},
	{
		userName: 'Babbie Nesby',
		userEmail: 'bnesbyb@sciencedaily.com',
		userPassword: 'GNr0OGAUk',
		userPhone: '+55 (566) 553-7142',
		userAddress: '4 Claremont Drive',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'vuk317',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 10,
	},
	{
		userName: 'Theadora Hoolaghan',
		userEmail: 'thoolaghanc@alexa.com',
		userPassword: 'SfmB0ZF1sF',
		userPhone: '+86 (268) 984-1187',
		userAddress: '625 Hovde Point',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Hau063',
		isFullTime: false,
		hourlyPay: '$19',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 11,
	},
	{
		userName: 'Oralia Godsafe',
		userEmail: 'ogodsafed@ehow.com',
		userPassword: 'z8BFdNJ5y',
		userPhone: '+7 (195) 777-8197',
		userAddress: '2 Ridgeview Alley',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'VMR256',
		isFullTime: false,
		hourlyPay: '$19',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 7,
	},
	{
		userName: 'Towney Mottini',
		userEmail: 'tmottinie@eepurl.com',
		userPassword: 'fxmXDKr',
		userPhone: '+63 (340) 444-6941',
		userAddress: '08685 Warrior Plaza',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'vZY855',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 5,
	},
	{
		userName: 'Sunshine Gathercole',
		userEmail: 'sgathercolef@list-manage.com',
		userPassword: 'siKNiQk0',
		userPhone: '+63 (499) 613-2977',
		userAddress: '9 Corry Center',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'IEN787',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 8,
	},
	{
		userName: 'Mart Vollam',
		userEmail: 'mvollamg@mac.com',
		userPassword: 'c5hGFAkmyaSU',
		userPhone: '+355 (515) 330-8557',
		userAddress: '23908 Spenser Hill',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'uSx243',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 14,
	},
	{
		userName: 'Lucy Millions',
		userEmail: 'lmillionsh@mapy.cz',
		userPassword: 'GfrFGArI',
		userPhone: '+84 (527) 370-8930',
		userAddress: '0 Hooker Trail',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'qTC997',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 1,
	},
	{
		userName: 'Ave Purvis',
		userEmail: 'apurvisi@economist.com',
		userPassword: 'tKqJrjNqW',
		userPhone: '+34 (921) 309-2572',
		userAddress: '19 7th Terrace',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'wIE994',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 3,
	},
	{
		userName: 'Veradis Crawley',
		userEmail: 'vcrawleyj@tuttocitta.it',
		userPassword: 'KgBZFkeNL',
		userPhone: '+86 (449) 159-2773',
		userAddress: '8436 Declaration Crossing',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'uaZ108',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 5,
	},
	{
		userName: 'Valle Antowski',
		userEmail: 'vantowskik@gov.uk',
		userPassword: 'kJv5zsCV21B',
		userPhone: '+420 (553) 643-9364',
		userAddress: '45574 Melvin Circle',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'ApX902',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 8,
	},
	{
		userName: 'Duncan Agirre',
		userEmail: 'dagirrel@tinypic.com',
		userPassword: 'd6izmxa2bH4z',
		userPhone: '+420 (653) 859-2874',
		userAddress: '624 Russell Street',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'FXC282',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 2,
	},
	{
		userName: 'Vick Adrien',
		userEmail: 'vadrienm@ucoz.com',
		userPassword: 'Qy96Bm',
		userPhone: '+237 (402) 732-0685',
		userAddress: '85544 Hoard Court',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'VCi538',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 1,
	},
	{
		userName: 'Poppy Eisikovitsh',
		userEmail: 'peisikovitshn@nps.gov',
		userPassword: 'OIxmPmXDLI3a',
		userPhone: '+86 (773) 399-8058',
		userAddress: '76 Johnson Junction',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'COG927',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 7,
	},
	{
		userName: 'Ezra Birdseye',
		userEmail: 'ebirdseyeo@google.com.hk',
		userPassword: 'kzr5Stoj',
		userPhone: '+81 (150) 246-5748',
		userAddress: '198 Holy Cross Crossing',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'TZA648',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 12,
	},
	{
		userName: 'Haily Livingston',
		userEmail: 'hlivingstonp@weebly.com',
		userPassword: 'To4zo2f',
		userPhone: '+7 (970) 978-3694',
		userAddress: '0620 Farwell Trail',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'rgN390',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 8,
	},
	{
		userName: "Jolene O'Growgane",
		userEmail: 'jogrowganeq@nbcnews.com',
		userPassword: '9VbjKiCp6',
		userPhone: '+46 (265) 285-4908',
		userAddress: '766 Farmco Pass',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'iYM278',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 15,
	},
	{
		userName: 'Daisi Ahearne',
		userEmail: 'dahearner@jalbum.net',
		userPassword: '2jArr12qu',
		userPhone: '+48 (551) 104-0797',
		userAddress: '48 Barby Center',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'iet004',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 11,
	},
	{
		userName: 'Skip Puttrell',
		userEmail: 'sputtrells@bbb.org',
		userPassword: 'OEjMgf3v12T',
		userPhone: '+7 (467) 726-9806',
		userAddress: '65 Stephen Junction',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'xkO496',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 5,
	},
	{
		userName: 'Chrissy McEnhill',
		userEmail: 'cmcenhillt@about.me',
		userPassword: 'z7HvbgfT',
		userPhone: '+62 (590) 802-1840',
		userAddress: '64142 Lighthouse Bay Terrace',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'xEl664',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 1,
	},
	{
		userName: 'Cybil Cuttles',
		userEmail: 'ccuttlesu@dot.gov',
		userPassword: 'z6qr0zvbn2s',
		userPhone: '+62 (901) 898-7114',
		userAddress: '18448 Harper Way',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'scO808',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 14,
	},
	{
		userName: 'Gay Windas',
		userEmail: 'gwindasv@netlog.com',
		userPassword: 'P75fsr5k2N',
		userPhone: '+963 (716) 354-0851',
		userAddress: '5 Rusk Lane',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'tWF353',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 1,
	},
	{
		userName: 'Vern Gosenell',
		userEmail: 'vgosenellw@flickr.com',
		userPassword: 'mjt08x',
		userPhone: '+33 (253) 418-3242',
		userAddress: '6881 Upham Terrace',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'DJX567',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 4,
	},
	{
		userName: 'Sky Raubenheim',
		userEmail: 'sraubenheimx@sourceforge.net',
		userPassword: 'Gi9PRC',
		userPhone: '+86 (471) 318-9111',
		userAddress: '996 Anhalt Hill',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'pzB607',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 9,
	},
	{
		userName: 'Enoch Casajuana',
		userEmail: 'ecasajuanay@oakley.com',
		userPassword: '2B9ZygGa',
		userPhone: '+62 (572) 436-0071',
		userAddress: '65325 Pepper Wood Pass',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'uKe246',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 14,
	},
	{
		userName: 'Myrna McClymond',
		userEmail: 'mmcclymondz@plala.or.jp',
		userPassword: 'OPc4e6WiN3',
		userPhone: '+86 (983) 405-0587',
		userAddress: '4 Declaration Street',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'wQs594',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 7,
	},
	{
		userName: 'Gradeigh Bowcock',
		userEmail: 'gbowcock10@hexun.com',
		userPassword: 'DpKV9wY0mx',
		userPhone: '+86 (821) 966-8871',
		userAddress: '21 Rutledge Pass',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'Kcu455',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 15,
	},
	{
		userName: 'Hatti Cocklie',
		userEmail: 'hcocklie11@si.edu',
		userPassword: 'mmHhzp',
		userPhone: '+7 (990) 978-7624',
		userAddress: '694 Schurz Road',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'xHS506',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 11,
	},
	{
		userName: 'Merwyn Alcide',
		userEmail: 'malcide12@unesco.org',
		userPassword: 'l3yj2N7yN',
		userPhone: '+231 (517) 883-7469',
		userAddress: '465 Waywood Road',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'xjL768',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 10,
	},
	{
		userName: 'Thibaud Baily',
		userEmail: 'tbaily13@jimdo.com',
		userPassword: 'fQJFH3pR',
		userPhone: '+62 (867) 394-5286',
		userAddress: '22821 Maywood Drive',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'TXN122',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 3,
	},
	{
		userName: 'Norry Pammenter',
		userEmail: 'npammenter14@disqus.com',
		userPassword: 'TdkOsGe',
		userPhone: '+86 (772) 298-0996',
		userAddress: '212 Mcbride Pass',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'vfy513',
		isFullTime: false,
		hourlyPay: '$19',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 15,
	},
	{
		userName: 'Brandea Houdmont',
		userEmail: 'bhoudmont15@zdnet.com',
		userPassword: 'w846K6',
		userPhone: '+62 (167) 738-6847',
		userAddress: '7441 Garrison Crossing',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'Lla773',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 10,
	},
	{
		userName: 'Care Yukhin',
		userEmail: 'cyukhin16@privacy.gov.au',
		userPassword: 'SHOCiR0CI',
		userPhone: '+51 (438) 740-1965',
		userAddress: '8679 Hollow Ridge Drive',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'BQn024',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 5,
	},
	{
		userName: 'Karena Goathrop',
		userEmail: 'kgoathrop17@cmu.edu',
		userPassword: '969jaHl6P',
		userPhone: '+86 (884) 269-1108',
		userAddress: '04807 West Court',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'qyj000',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 15,
	},
	{
		userName: 'Selena Ruppertz',
		userEmail: 'sruppertz18@elegantthemes.com',
		userPassword: 'bOK5oR',
		userPhone: '+1 (167) 658-0805',
		userAddress: '30704 Fallview Park',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'FmY126',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 10,
	},
	{
		userName: 'Ailis Lombardo',
		userEmail: 'alombardo19@instagram.com',
		userPassword: 'wSaIdH',
		userPhone: '+509 (992) 366-8195',
		userAddress: '92205 Eliot Lane',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'LOk211',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 10,
	},
	{
		userName: 'Gerard Scough',
		userEmail: 'gscough1a@ebay.co.uk',
		userPassword: 'qMacfbPC8W',
		userPhone: '+30 (372) 509-8732',
		userAddress: '3752 Warner Place',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'xVp813',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 7,
	},
	{
		userName: 'Sutton Lonnon',
		userEmail: 'slonnon1b@pinterest.com',
		userPassword: 'UrfKNZj',
		userPhone: '+30 (131) 795-7804',
		userAddress: '66 Cascade Park',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'XTf854',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 9,
	},
	{
		userName: 'Isaak Kobisch',
		userEmail: 'ikobisch1c@dropbox.com',
		userPassword: 'IYLN60',
		userPhone: '+351 (786) 311-5515',
		userAddress: '3 Truax Place',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'nGD378',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 9,
	},
	{
		userName: 'Othello Minshull',
		userEmail: 'ominshull1d@imgur.com',
		userPassword: 'KoqyMd8WlCs',
		userPhone: '+81 (365) 902-4548',
		userAddress: '3561 Veith Center',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'VMG714',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 2,
	},
	{
		userName: 'Bert Ranscome',
		userEmail: 'branscome1e@yale.edu',
		userPassword: 'dWzUgjt5U',
		userPhone: '+62 (938) 776-6289',
		userAddress: '796 Holy Cross Drive',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'shb759',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 8,
	},
	{
		userName: 'Almeda Prest',
		userEmail: 'aprest1f@buzzfeed.com',
		userPassword: 'fkbBVdV',
		userPhone: '+385 (254) 673-7059',
		userAddress: '115 Gulseth Pass',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'avb238',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 6,
	},
	{
		userName: 'Nina Curran',
		userEmail: 'ncurran1g@huffingtonpost.com',
		userPassword: 'hPZdx0iC',
		userPhone: '+86 (755) 213-2138',
		userAddress: '93154 Service Avenue',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'JIk877',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 14,
	},
	{
		userName: 'Cecilius Pallesen',
		userEmail: 'cpallesen1h@paypal.com',
		userPassword: 'jxh71x9qeQ5',
		userPhone: '+33 (328) 221-9734',
		userAddress: '622 Cardinal Avenue',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'tXP380',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 6,
	},
	{
		userName: 'Hali Novak',
		userEmail: 'hnovak1i@salon.com',
		userPassword: '70d3dbnUw',
		userPhone: '+86 (278) 672-9932',
		userAddress: '42 Jackson Trail',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'ntB367',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 13,
	},
	{
		userName: 'Letisha Barcke',
		userEmail: 'lbarcke1j@economist.com',
		userPassword: 'EJGwP0P9eL',
		userPhone: '+380 (164) 938-8072',
		userAddress: '698 Village Green Alley',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Xiw134',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 8,
	},
	{
		userName: 'Lorne Sillitoe',
		userEmail: 'lsillitoe1k@mit.edu',
		userPassword: '9OsBzn',
		userPhone: '+53 (634) 849-6979',
		userAddress: '60 Elgar Hill',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'fTG852',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 13,
	},
	{
		userName: 'Boone Sawfoot',
		userEmail: 'bsawfoot1l@ca.gov',
		userPassword: '1s4l3e0',
		userPhone: '+49 (523) 979-8571',
		userAddress: '834 Novick Point',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'iRb806',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 10,
	},
	{
		userName: 'Erda Oakden',
		userEmail: 'eoakden1m@hc360.com',
		userPassword: 'YGCbkufPc',
		userPhone: '+81 (272) 333-7171',
		userAddress: '7963 Anzinger Court',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'cuO017',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 2,
	},
	{
		userName: 'Thayne Pietersma',
		userEmail: 'tpietersma1n@blogs.com',
		userPassword: 'FZ0Ein',
		userPhone: '+54 (217) 123-6248',
		userAddress: '52896 Forest Run Point',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'oDY661',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 2,
	},
	{
		userName: 'Tallie Minigo',
		userEmail: 'tminigo1o@illinois.edu',
		userPassword: 'Nqw6i0',
		userPhone: '+251 (645) 644-8503',
		userAddress: '980 Wayridge Court',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'BDm847',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 4,
	},
	{
		userName: 'Stefania Ajsik',
		userEmail: 'sajsik1p@plala.or.jp',
		userPassword: 'R6IrPN',
		userPhone: '+62 (427) 375-4216',
		userAddress: '22 Express Parkway',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Uil496',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 9,
	},
	{
		userName: 'Ninetta Palister',
		userEmail: 'npalister1q@discovery.com',
		userPassword: 'qbfOEPdP',
		userPhone: '+57 (808) 686-0809',
		userAddress: '4 Myrtle Junction',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'XNi379',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 1,
	},
	{
		userName: 'Anastasia Truett',
		userEmail: 'atruett1r@cbsnews.com',
		userPassword: 'JqHdU46',
		userPhone: '+263 (111) 853-9460',
		userAddress: '2 Annamark Avenue',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'vPe316',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 12,
	},
	{
		userName: 'Tybalt Beardsley',
		userEmail: 'tbeardsley1s@list-manage.com',
		userPassword: 's0asWzt6OXW',
		userPhone: '+55 (561) 375-5291',
		userAddress: '9548 Drewry Place',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Xut182',
		isFullTime: false,
		hourlyPay: '$19',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 6,
	},
	{
		userName: 'Timotheus Sparrowe',
		userEmail: 'tsparrowe1t@ning.com',
		userPassword: 'qt27T4IUgWq',
		userPhone: '+86 (247) 524-6814',
		userAddress: '02 Twin Pines Place',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Whi739',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 6,
	},
	{
		userName: 'Ammamaria Yakovlev',
		userEmail: 'ayakovlev1u@ucoz.ru',
		userPassword: 'dcIFFE',
		userPhone: '+255 (358) 759-6427',
		userAddress: '6844 Continental Court',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'Pvp804',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 2,
	},
	{
		userName: 'Maisey Volk',
		userEmail: 'mvolk1v@virginia.edu',
		userPassword: '90PnDejw51Q',
		userPhone: '+47 (356) 409-8085',
		userAddress: '7 Main Avenue',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'dYS320',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 3,
	},
	{
		userName: 'Bliss Cicconetti',
		userEmail: 'bcicconetti1w@wufoo.com',
		userPassword: 'gZ0re5T',
		userPhone: '+95 (606) 698-7414',
		userAddress: '7948 Kipling Pass',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'TAs300',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 15,
	},
	{
		userName: 'Teddy Wyndham',
		userEmail: 'twyndham1x@stanford.edu',
		userPassword: 'a3FFODuODqX',
		userPhone: '+46 (265) 400-7986',
		userAddress: '99 Schlimgen Crossing',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'eOq149',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 2,
	},
	{
		userName: 'Friederike Brand-Hardy',
		userEmail: 'fbrandhardy1y@dmoz.org',
		userPassword: 'uWDjyLs7ioMk',
		userPhone: '+57 (431) 358-9898',
		userAddress: '11326 Dennis Alley',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'eSi417',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 7,
	},
	{
		userName: 'Ilse Alti',
		userEmail: 'ialti1z@washington.edu',
		userPassword: 'qvmMq3KsHb',
		userPhone: '+62 (630) 696-5100',
		userAddress: '7 Longview Park',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'uig507',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 10,
	},
	{
		userName: 'Ernie Panons',
		userEmail: 'epanons20@elpais.com',
		userPassword: 'Gy6loFxr',
		userPhone: '+86 (123) 435-1815',
		userAddress: '5 Fulton Hill',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'FQa896',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 15,
	},
	{
		userName: 'Karlyn Llopis',
		userEmail: 'kllopis21@house.gov',
		userPassword: 'yNpOShBop',
		userPhone: '+86 (763) 902-3503',
		userAddress: '7 Bunting Court',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'khH269',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 15,
	},
	{
		userName: 'Tandie Breakey',
		userEmail: 'tbreakey22@state.gov',
		userPassword: 't7fLxfq7D',
		userPhone: '+82 (839) 535-0446',
		userAddress: '58903 Sloan Court',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Tev880',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 10,
	},
	{
		userName: 'Monah Carlow',
		userEmail: 'mcarlow23@reuters.com',
		userPassword: 'm6IvM5VKbx',
		userPhone: '+86 (827) 496-4648',
		userAddress: '7410 Lindbergh Alley',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'mgR339',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 7,
	},
	{
		userName: 'Tammie Breslau',
		userEmail: 'tbreslau24@utexas.edu',
		userPassword: 'tCI0hja',
		userPhone: '+48 (854) 818-2197',
		userAddress: '570 Becker Crossing',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'BFw080',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 12,
	},
	{
		userName: 'Rosana Burr',
		userEmail: 'rburr25@gmpg.org',
		userPassword: 'WRGI1tmw2',
		userPhone: '+86 (601) 792-2419',
		userAddress: '4608 Bobwhite Center',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Ort886',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 3,
	},
	{
		userName: 'Stanford Lodovichi',
		userEmail: 'slodovichi26@google.com',
		userPassword: 'YFupwCoHV1DZ',
		userPhone: '+597 (400) 788-6669',
		userAddress: '570 Manley Court',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'ikP200',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 8,
	},
	{
		userName: 'Rolland Ledeker',
		userEmail: 'rledeker27@google.com.au',
		userPassword: '7CEIXoOh',
		userPhone: '+62 (729) 197-7900',
		userAddress: '04 Mcguire Junction',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'PHL140',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 5,
	},
];
export default partTimeFaculty;
