const partTimeFaculty = [
	{
		userName: 'Arnoldo Wynrehame',
		userEmail: 'awynrehame0@plala.or.jp',
		userPassword: 'g92Siq01cj9',
		userPhone: '+33 (833) 601-6819',
		userAddress: '89698 Hazelcrest Trail',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'Epi676',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 1,
	},
	{
		userName: 'Miquela Korf',
		userEmail: 'mkorf1@list-manage.com',
		userPassword: 'xl7gxzwS',
		userPhone: '+7 (674) 278-7613',
		userAddress: '75 Village Plaza',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'jCT924',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 2,
	},
	{
		userName: 'Cheri Tilte',
		userEmail: 'ctilte2@cbslocal.com',
		userPassword: 'Ve60T3YZn4R',
		userPhone: '+62 (852) 125-0567',
		userAddress: '32449 Sachtjen Terrace',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Syb275',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 3,
	},
	{
		userName: 'Michel Bedlington',
		userEmail: 'mbedlington3@feedburner.com',
		userPassword: 'oTC8bU',
		userPhone: '+7 (773) 786-1275',
		userAddress: '6 Milwaukee Drive',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'Llt605',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 4,
	},
	{
		userName: 'Renelle Braybrooke',
		userEmail: 'rbraybrooke4@360.cn',
		userPassword: 'UuKjBmz',
		userPhone: '+51 (827) 372-1236',
		userAddress: '71 Marcy Way',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'Qse644',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 5,
	},
	{
		userName: 'Reggie Becerra',
		userEmail: 'rbecerra5@instagram.com',
		userPassword: 'S0Ch29NnB0',
		userPhone: '+227 (360) 298-9834',
		userAddress: '8 Steensland Way',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'Gjc354',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 6,
	},
	{
		userName: 'Sharla Dissman',
		userEmail: 'sdissman6@state.tx.us',
		userPassword: 'koQaRKXgbV2',
		userPhone: '+593 (154) 752-3315',
		userAddress: '77 Lakeland Parkway',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'sTV140',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 7,
	},
	{
		userName: 'Pincus Kaley',
		userEmail: 'pkaley7@skype.com',
		userPassword: 'bguycrhm50',
		userPhone: '+62 (687) 550-4298',
		userAddress: '10 Westridge Alley',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'qOj446',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 8,
	},
	{
		userName: 'Joane Wardingly',
		userEmail: 'jwardingly8@plala.or.jp',
		userPassword: 'q9ngF3cXU6y',
		userPhone: '+86 (223) 566-1810',
		userAddress: '77469 Tony Street',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'dXE279',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 9,
	},
	{
		userName: 'Shanan Rolles',
		userEmail: 'srolles9@boston.com',
		userPassword: 'zoUgXT',
		userPhone: '+86 (248) 195-6514',
		userAddress: '866 Cardinal Avenue',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'qcE342',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 10,
	},
	{
		userName: 'Kalle Colson',
		userEmail: 'kcolsona@dell.com',
		userPassword: 'umxagq6BYteU',
		userPhone: '+86 (635) 623-9868',
		userAddress: '6 Golden Leaf Street',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'reS728',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 11,
	},
	{
		userName: 'Stephannie Robeson',
		userEmail: 'srobesonb@nature.com',
		userPassword: 'GWMTy2A6u',
		userPhone: '+46 (927) 440-1970',
		userAddress: '5 Hazelcrest Parkway',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'Ptp270',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 12,
	},
	{
		userName: 'Matteo Dranfield',
		userEmail: 'mdranfieldc@ask.com',
		userPassword: 'qJvRsqqK',
		userPhone: '+86 (576) 499-8461',
		userAddress: '42 Stone Corner Street',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'Jkl908',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 13,
	},
	{
		userName: 'Terrance Dusey',
		userEmail: 'tduseyd@tiny.cc',
		userPassword: 'ytVFoH4',
		userPhone: '+45 (644) 572-7427',
		userAddress: '0676 Doe Crossing Center',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'fvd195',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 14,
	},
	{
		userName: 'Roshelle MacAllan',
		userEmail: 'rmacallane@live.com',
		userPassword: 'aKPALY3X9',
		userPhone: '+1 (201) 682-0610',
		userAddress: '823 Leroy Crossing',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'ETI516',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 15,
	},
	{
		userName: 'Halie Willimot',
		userEmail: 'hwillimotf@hp.com',
		userPassword: 'tL2KWqZ8ZXt',
		userPhone: '+1 (202) 859-3569',
		userAddress: '9052 Southridge Parkway',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'tdN697',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 16,
	},
	{
		userName: 'Vidovic Yurmanovev',
		userEmail: 'vyurmanovevg@ihg.com',
		userPassword: 'wTCZ5mU',
		userPhone: '+62 (767) 599-5293',
		userAddress: '4246 Fieldstone Junction',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'acu812',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 17,
	},
	{
		userName: 'Bamby Veeler',
		userEmail: 'bveelerh@wiley.com',
		userPassword: 'EpVHLkrRxG',
		userPhone: '+86 (684) 496-7347',
		userAddress: '841 Rieder Junction',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'cti341',
		isFullTime: false,
		hourlyPay: '$19',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 18,
	},
	{
		userName: 'Jarrid Haberjam',
		userEmail: 'jhaberjami@devhub.com',
		userPassword: 'BFDK2grTk1',
		userPhone: '+86 (881) 790-7087',
		userAddress: '0 Raven Circle',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'sdw627',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 19,
	},
	{
		userName: 'Dwain Chastney',
		userEmail: 'dchastneyj@cnet.com',
		userPassword: 'yiSSlizr',
		userPhone: '+62 (375) 794-1114',
		userAddress: '061 Crescent Oaks Junction',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'cKP900',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 20,
	},
	{
		userName: 'Amil Dahmel',
		userEmail: 'adahmelk@zdnet.com',
		userPassword: '7LuhLqd0NRjz',
		userPhone: '+86 (550) 616-7210',
		userAddress: '6709 West Trail',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'kRo617',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 21,
	},
	{
		userName: 'Waly Billett',
		userEmail: 'wbillettl@msn.com',
		userPassword: '3S9cm3OUW',
		userPhone: '+1 (916) 100-5648',
		userAddress: '440 Aberg Alley',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'TcV635',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 22,
	},
	{
		userName: 'Enriqueta Doumer',
		userEmail: 'edoumerm@google.pl',
		userPassword: '1qNeA5TH8g',
		userPhone: '+86 (485) 908-1175',
		userAddress: '0306 Hagan Street',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'pFD883',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 23,
	},
	{
		userName: 'Yurik Hinze',
		userEmail: 'yhinzen@sourceforge.net',
		userPassword: 'kbyUGQFhIKH4',
		userPhone: '+387 (431) 376-3345',
		userAddress: '484 Crownhardt Point',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'wVG738',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 24,
	},
	{
		userName: 'Milicent Millson',
		userEmail: 'mmillsono@theatlantic.com',
		userPassword: 'nSIGZx',
		userPhone: '+976 (952) 180-3365',
		userAddress: '1 Westridge Crossing',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'skU521',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 25,
	},
	{
		userName: 'Ardenia Simm',
		userEmail: 'asimmp@washington.edu',
		userPassword: 'iV5u7MG7qxr8',
		userPhone: '+62 (893) 293-3230',
		userAddress: '2333 Mallory Point',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'BwV588',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 26,
	},
	{
		userName: 'Cyndia Dykins',
		userEmail: 'cdykinsq@economist.com',
		userPassword: 'QimdB7zN',
		userPhone: '+30 (628) 779-9230',
		userAddress: '276 Annamark Center',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'jEz275',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 27,
	},
	{
		userName: 'Burtie Wincom',
		userEmail: 'bwincomr@php.net',
		userPassword: 'fQqV8Swr5Ne',
		userPhone: '+358 (899) 294-8025',
		userAddress: '2382 Autumn Leaf Point',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'ovi576',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 28,
	},
	{
		userName: 'Libby Dibden',
		userEmail: 'ldibdens@dion.ne.jp',
		userPassword: '0fzUn1yfXHCs',
		userPhone: '+55 (105) 512-9694',
		userAddress: '1 Bobwhite Lane',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'Pga049',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 29,
	},
	{
		userName: 'Gill Larchiere',
		userEmail: 'glarchieret@apple.com',
		userPassword: '5e2xZwDsf9',
		userPhone: '+55 (274) 543-7079',
		userAddress: '65296 West Road',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'PxB051',
		isFullTime: false,
		hourlyPay: '$19',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 30,
	},
	{
		userName: 'Shara Petkens',
		userEmail: 'spetkensu@vimeo.com',
		userPassword: 'kf7yXp',
		userPhone: '+55 (748) 529-1901',
		userAddress: '58820 Sauthoff Junction',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'wJd161',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 31,
	},
	{
		userName: 'Catlee Karpov',
		userEmail: 'ckarpovv@hhs.gov',
		userPassword: 'FfdR7m8P',
		userPhone: '+221 (780) 154-5305',
		userAddress: '8 Bashford Center',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'KtA452',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 32,
	},
	{
		userName: 'Town Kempster',
		userEmail: 'tkempsterw@pagesperso-orange.fr',
		userPassword: 'H7XYw1cUaWvo',
		userPhone: '+359 (854) 801-0553',
		userAddress: '93615 Vernon Crossing',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'zpZ496',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 33,
	},
	{
		userName: 'Gilburt Bellord',
		userEmail: 'gbellordx@jiathis.com',
		userPassword: '8uDXUf0',
		userPhone: '+62 (188) 240-7650',
		userAddress: '45 Almo Alley',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'Tlp297',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 34,
	},
	{
		userName: 'North Organ',
		userEmail: 'norgany@psu.edu',
		userPassword: 'F1zadzvyo',
		userPhone: '+62 (377) 223-1881',
		userAddress: '30 Swallow Road',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'QeN368',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 35,
	},
	{
		userName: 'Anthony Mugg',
		userEmail: 'amuggz@yahoo.co.jp',
		userPassword: 'XGpW1K1',
		userPhone: '+230 (998) 743-1417',
		userAddress: '7864 Bultman Alley',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'jIP891',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 36,
	},
	{
		userName: 'Caddric Measor',
		userEmail: 'cmeasor10@phpbb.com',
		userPassword: 'DpH3kCDWP8y',
		userPhone: '+46 (287) 540-2158',
		userAddress: '23462 Debra Alley',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'YSc149',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 37,
	},
	{
		userName: 'Claudelle Matyasik',
		userEmail: 'cmatyasik11@cargocollective.com',
		userPassword: 'CrFAq4kWdgKC',
		userPhone: '+7 (757) 136-4749',
		userAddress: '26298 Spaight Hill',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'Slx265',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 38,
	},
	{
		userName: 'Brandon Yarranton',
		userEmail: 'byarranton12@opensource.org',
		userPassword: 'F90HCJq',
		userPhone: '+63 (796) 934-4034',
		userAddress: '0 Village Green Street',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'liJ372',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 39,
	},
	{
		userName: 'Skipp Minelli',
		userEmail: 'sminelli13@cpanel.net',
		userPassword: 'RBfiBbdsiG59',
		userPhone: '+355 (348) 533-6426',
		userAddress: '90052 Crescent Oaks Center',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'udm074',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 40,
	},
	{
		userName: 'Marlane Karsh',
		userEmail: 'mkarsh14@nasa.gov',
		userPassword: 'cyWh9wcZoAM',
		userPhone: '+86 (869) 869-8715',
		userAddress: '97 Cordelia Crossing',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'OUo680',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 41,
	},
	{
		userName: 'Michell Caddick',
		userEmail: 'mcaddick15@telegraph.co.uk',
		userPassword: 'KGjsXtw19',
		userPhone: '+374 (679) 761-0385',
		userAddress: '083 Norway Maple Avenue',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'sWm647',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 42,
	},
	{
		userName: 'Theodosia Delph',
		userEmail: 'tdelph16@spiegel.de',
		userPassword: 'nhi0KsKJ',
		userPhone: '+46 (521) 241-3532',
		userAddress: '73291 Westridge Lane',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'kSz619',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 43,
	},
	{
		userName: 'Tod Sudddard',
		userEmail: 'tsudddard17@geocities.com',
		userPassword: 'KLcKY7Ql',
		userPhone: '+86 (931) 789-7857',
		userAddress: '9 Loeprich Point',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'gua293',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 44,
	},
	{
		userName: 'Caprice Reame',
		userEmail: 'creame18@woothemes.com',
		userPassword: 'ki5hRz0bAF',
		userPhone: '+62 (402) 357-6586',
		userAddress: '46592 Trailsway Plaza',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'KMn678',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 45,
	},
	{
		userName: 'Rodge Cosley',
		userEmail: 'rcosley19@digg.com',
		userPassword: 'NixuawtkcH',
		userPhone: '+994 (244) 118-4412',
		userAddress: '1000 Sheridan Junction',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'jUN049',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 46,
	},
	{
		userName: 'Jorge Drinkall',
		userEmail: 'jdrinkall1a@youtu.be',
		userPassword: 'Flxx8xjiDdu',
		userPhone: '+1 (314) 174-4556',
		userAddress: '348 Donald Park',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'tSd213',
		isFullTime: false,
		hourlyPay: '$19',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 47,
	},
	{
		userName: 'Perry Welden',
		userEmail: 'pwelden1b@github.com',
		userPassword: 'kgNjkxYmG5P1',
		userPhone: '+30 (998) 599-8261',
		userAddress: '6404 Lindbergh Lane',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'eNX362',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 48,
	},
	{
		userName: 'Osgood Skelhorn',
		userEmail: 'oskelhorn1c@ehow.com',
		userPassword: 'PEqcN6h1D7KQ',
		userPhone: '+33 (186) 745-9091',
		userAddress: '7009 Rigney Plaza',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'QvK091',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 49,
	},
	{
		userName: 'Natividad Wyndham',
		userEmail: 'nwyndham1d@slate.com',
		userPassword: 'kOBEc9Zei',
		userPhone: '+54 (154) 479-3780',
		userAddress: '11456 Welch Place',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'yut774',
		isFullTime: false,
		hourlyPay: '$19',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 50,
	},
	{
		userName: 'Lance Warder',
		userEmail: 'lwarder1e@amazon.co.uk',
		userPassword: 'OqeMC3lYP',
		userPhone: '+1 (602) 446-5511',
		userAddress: '67536 Green Center',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'BMk643',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 51,
	},
	{
		userName: 'Bertrand Diviney',
		userEmail: 'bdiviney1f@webs.com',
		userPassword: 'tCVn6iTURgH',
		userPhone: '+62 (717) 870-9357',
		userAddress: '65 Sage Terrace',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'tns405',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 52,
	},
	{
		userName: 'Pauletta Eilhertsen',
		userEmail: 'peilhertsen1g@prweb.com',
		userPassword: 'jd5ELGPyWQ6m',
		userPhone: '+86 (148) 451-0855',
		userAddress: '9 Alpine Way',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'RwF502',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 53,
	},
	{
		userName: 'Rich Ealden',
		userEmail: 'realden1h@psu.edu',
		userPassword: 'pu6qY2YfR',
		userPhone: '+7 (722) 651-2121',
		userAddress: '65933 Luster Center',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'iKe160',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 54,
	},
	{
		userName: 'Gawain Tregoning',
		userEmail: 'gtregoning1i@narod.ru',
		userPassword: 'C8oeF6ux',
		userPhone: '+48 (317) 416-9631',
		userAddress: '89 Delaware Circle',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'UWV137',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 55,
	},
	{
		userName: 'Rosamund Afield',
		userEmail: 'rafield1j@europa.eu',
		userPassword: 'H75FFqX',
		userPhone: '+228 (772) 242-6884',
		userAddress: '361 Stang Alley',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'XzE572',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 56,
	},
	{
		userName: 'Alysa Rogeon',
		userEmail: 'arogeon1k@dot.gov',
		userPassword: 'nohZTjkt',
		userPhone: '+66 (278) 770-7478',
		userAddress: '39 Hooker Lane',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'knL500',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 57,
	},
	{
		userName: 'Rolf Newling',
		userEmail: 'rnewling1l@wunderground.com',
		userPassword: 'XRleTK5xNj',
		userPhone: '+1 (865) 616-3171',
		userAddress: '075 Harper Trail',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'pxl258',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 58,
	},
	{
		userName: 'Chancey Mc Grath',
		userEmail: 'cmc1m@com.com',
		userPassword: 'OToHmmEEIfki',
		userPhone: '+86 (650) 676-8623',
		userAddress: '085 Londonderry Drive',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'tOw623',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 59,
	},
	{
		userName: 'Inna Le Marquis',
		userEmail: 'ile1n@themeforest.net',
		userPassword: '3sJ0lajt59z',
		userPhone: '+48 (306) 547-6309',
		userAddress: '534 Fairfield Park',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'wxX726',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 60,
	},
	{
		userName: 'Clarance Tallow',
		userEmail: 'ctallow1o@php.net',
		userPassword: '86gJf7',
		userPhone: '+65 (494) 596-9384',
		userAddress: '96 Monument Junction',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'DQH660',
		isFullTime: false,
		hourlyPay: '$19',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 61,
	},
	{
		userName: 'Burt Temlett',
		userEmail: 'btemlett1p@youtube.com',
		userPassword: 'kn8yOXddX',
		userPhone: '+86 (270) 465-9780',
		userAddress: '6388 Garrison Center',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'ZuL664',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 62,
	},
	{
		userName: 'Veradis Dalton',
		userEmail: 'vdalton1q@ft.com',
		userPassword: 'j6Pyqz',
		userPhone: '+62 (982) 739-8819',
		userAddress: '08494 Gale Court',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'nYT217',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 63,
	},
	{
		userName: 'Mariejeanne Pringuer',
		userEmail: 'mpringuer1r@xing.com',
		userPassword: 'Db9BBEi',
		userPhone: '+27 (375) 130-8305',
		userAddress: '44215 Stang Plaza',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'lTW997',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 64,
	},
	{
		userName: 'Waylin Breming',
		userEmail: 'wbreming1s@cloudflare.com',
		userPassword: 'NJvCPb',
		userPhone: '+86 (393) 401-8524',
		userAddress: '54 Dapin Point',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'nOj659',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 65,
	},
	{
		userName: 'Mil Morland',
		userEmail: 'mmorland1t@newsvine.com',
		userPassword: 'qdAML3ov',
		userPhone: '+62 (103) 490-9674',
		userAddress: '60 Hoepker Street',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'gje916',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 66,
	},
	{
		userName: 'Errick Fleischer',
		userEmail: 'efleischer1u@pbs.org',
		userPassword: 'Jyz11xfDPC9u',
		userPhone: '+51 (827) 651-0223',
		userAddress: '507 Morning Way',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'WKx660',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 67,
	},
	{
		userName: 'Candice Durban',
		userEmail: 'cdurban1v@webs.com',
		userPassword: 'rjLECDp',
		userPhone: '+7 (267) 218-4357',
		userAddress: '7 Northland Point',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'bju368',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 68,
	},
	{
		userName: 'Gwendolyn Seawell',
		userEmail: 'gseawell1w@ifeng.com',
		userPassword: 'NvNHETZ',
		userPhone: '+63 (517) 537-9503',
		userAddress: '28 Maple Hill',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'xVC951',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 69,
	},
	{
		userName: 'Edmund Floyde',
		userEmail: 'efloyde1x@yahoo.com',
		userPassword: '45X9U5v',
		userPhone: '+235 (443) 814-5798',
		userAddress: '4080 Dexter Drive',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'dzF506',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: true,
		deptID: 70,
	},
	{
		userName: 'Kaia MacAughtrie',
		userEmail: 'kmacaughtrie1y@acquirethisname.com',
		userPassword: 'EvQuF7th',
		userPhone: '+7 (176) 482-5544',
		userAddress: '92582 Meadow Valley Court',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'pIN773',
		isFullTime: false,
		hourlyPay: '$15',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 71,
	},
	{
		userName: 'Creighton Juett',
		userEmail: 'cjuett1z@mlb.com',
		userPassword: 'w2Y7I0zVa92w',
		userPhone: '+86 (810) 338-9508',
		userAddress: '381 Thackeray Way',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'sBx165',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 72,
	},
	{
		userName: 'Dorette Ivoshin',
		userEmail: 'divoshin20@mayoclinic.com',
		userPassword: 'phPwwRPr1',
		userPhone: '+31 (126) 500-3198',
		userAddress: '11 Brown Junction',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'uyZ706',
		isFullTime: false,
		hourlyPay: '$17',
		teachOrResearch: 'Research',
		fTenure: false,
		deptID: 73,
	},
	{
		userName: 'Theresa Rogerson',
		userEmail: 'trogerson21@washingtonpost.com',
		userPassword: 'aZgQHHQ',
		userPhone: '+7 (642) 318-3635',
		userAddress: '914 Delaware Street',
		userType: 'Faculty',
		fRank: 'Associate Professor',
		fOfficeNumber: 'jdS388',
		isFullTime: false,
		hourlyPay: '$19',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 74,
	},
	{
		userName: 'Jamima Renfield',
		userEmail: 'jrenfield22@facebook.com',
		userPassword: 'cmuQJFj',
		userPhone: '+27 (984) 712-7794',
		userAddress: '8 Fisk Court',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'boA008',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 75,
	},
	{
		userName: 'Tamma Dalliwater',
		userEmail: 'tdalliwater23@vkontakte.ru',
		userPassword: 'ld2NhQC',
		userPhone: '+57 (962) 822-0197',
		userAddress: '233 Shelley Alley',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'oMg703',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 76,
	},
	{
		userName: 'Jayne Wilkennson',
		userEmail: 'jwilkennson24@vinaora.com',
		userPassword: 'SRzas2',
		userPhone: '+62 (177) 119-1677',
		userAddress: '104 Buell Hill',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'SRw842',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 77,
	},
	{
		userName: 'Hendrik Tonsley',
		userEmail: 'htonsley25@arstechnica.com',
		userPassword: 'lI3YqeBRDXI',
		userPhone: '+420 (989) 786-6499',
		userAddress: '53530 Jay Alley',
		userType: 'Faculty',
		fRank: 'Professor',
		fOfficeNumber: 'rjf634',
		isFullTime: false,
		hourlyPay: '$18',
		teachOrResearch: 'Teach',
		fTenure: true,
		deptID: 78,
	},
	{
		userName: 'Dorothee Yokelman',
		userEmail: 'dyokelman26@about.me',
		userPassword: 'N0PPXYblwLi',
		userPhone: '+86 (183) 535-9085',
		userAddress: '45371 Loomis Pass',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'kPD865',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 79,
	},
	{
		userName: 'Tammy Negri',
		userEmail: 'tnegri27@nbcnews.com',
		userPassword: 'KydXEa34VYr',
		userPhone: '+381 (820) 934-2189',
		userAddress: '06 Stephen Crossing',
		userType: 'Faculty',
		fRank: 'Assistant Professor',
		fOfficeNumber: 'pox576',
		isFullTime: false,
		hourlyPay: '$16',
		teachOrResearch: 'Teach',
		fTenure: false,
		deptID: 80,
	},
];
export default partTimeFaculty;
