const partTimeFaculty = [
	{
		"userName": "Emma Herries",
		"userEmail": "eherries0@hatena.ne.jp",
		"userPassword": "Mq7I1VR",
		"userPhone": "+31 (283) 184-7197",
		"userAddress": "3 Norway Maple Drive",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5000
	},
	{
		"userName": "Arnuad Andreolli",
		"userEmail": "aandreolli1@livejournal.com",
		"userPassword": "85KaUoHH2",
		"userPhone": "+20 (409) 326-7766",
		"userAddress": "8232 Monument Place",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Teach",
		"userID": 5001
	},
	{
		"userName": "Bjorn Kivell",
		"userEmail": "bkivell2@twitpic.com",
		"userPassword": "TyvqgE",
		"userPhone": "+1 (820) 515-9347",
		"userAddress": "104 Badeau Plaza",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Teach",
		"userID": 5002
	},
	{
		"userName": "Berri Bullent",
		"userEmail": "bbullent3@tripadvisor.com",
		"userPassword": "C5WkvpTQ7uxt",
		"userPhone": "+993 (357) 352-4124",
		"userAddress": "73512 Summer Ridge Way",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Research",
		"userID": 5003
	},
	{
		"userName": "Gilly Ladbrook",
		"userEmail": "gladbrook4@flickr.com",
		"userPassword": "0ejN5YJ",
		"userPhone": "+385 (599) 173-7027",
		"userAddress": "3 Pleasure Terrace",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5004
	},
	{
		"userName": "Killy Tackett",
		"userEmail": "ktackett5@accuweather.com",
		"userPassword": "KkYUhd1G",
		"userPhone": "+504 (123) 469-4771",
		"userAddress": "08 Del Sol Avenue",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5005
	},
	{
		"userName": "Elke Cabera",
		"userEmail": "ecabera6@geocities.jp",
		"userPassword": "pptNfz8HB",
		"userPhone": "+234 (840) 632-5917",
		"userAddress": "48442 Rowland Avenue",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5006
	},
	{
		"userName": "Kiersten Ricardet",
		"userEmail": "kricardet7@pbs.org",
		"userPassword": "UGuA7AF",
		"userPhone": "+992 (593) 410-6150",
		"userAddress": "89603 Grayhawk Circle",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Teach",
		"userID": 5007
	},
	{
		"userName": "Aloysia Cestard",
		"userEmail": "acestard8@feedburner.com",
		"userPassword": "FOzaXVUat",
		"userPhone": "+86 (817) 890-7280",
		"userAddress": "2567 Annamark Pass",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Teach",
		"userID": 5008
	},
	{
		"userName": "Donn Cuberley",
		"userEmail": "dcuberley9@dyndns.org",
		"userPassword": "QYW33a2",
		"userPhone": "+1 (155) 771-1582",
		"userAddress": "4602 Reinke Point",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Research",
		"userID": 5009
	},
	{
		"userName": "Courtenay Dyster",
		"userEmail": "cdystera@cbc.ca",
		"userPassword": "Sthj4YCtJd",
		"userPhone": "+1 (314) 728-0439",
		"userAddress": "7014 Stone Corner Lane",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5010
	},
	{
		"userName": "Bernadine Sealove",
		"userEmail": "bsealoveb@parallels.com",
		"userPassword": "xMeSdEenSy",
		"userPhone": "+251 (843) 228-8179",
		"userAddress": "16544 Express Plaza",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5011
	},
	{
		"userName": "Stacey Ruprich",
		"userEmail": "sruprichc@bloglovin.com",
		"userPassword": "dTjZPjs3tN",
		"userPhone": "+52 (908) 725-6204",
		"userAddress": "112 Bluestem Avenue",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Research",
		"userID": 5012
	},
	{
		"userName": "Madeline Bisgrove",
		"userEmail": "mbisgroved@yahoo.com",
		"userPassword": "qRoI8yhBlNL2",
		"userPhone": "+7 (494) 474-6495",
		"userAddress": "0049 Vera Avenue",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5013
	},
	{
		"userName": "Filip Mulbery",
		"userEmail": "fmulberye@fda.gov",
		"userPassword": "eH0vAP",
		"userPhone": "+358 (861) 349-2843",
		"userAddress": "01 Lerdahl Point",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5014
	},
	{
		"userName": "Maximo Ridges",
		"userEmail": "mridgesf@yelp.com",
		"userPassword": "9QCEf76",
		"userPhone": "+48 (407) 550-4457",
		"userAddress": "100 Mosinee Place",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5015
	},
	{
		"userName": "Saunders Disman",
		"userEmail": "sdismang@yelp.com",
		"userPassword": "6UwYlbbxX8Kd",
		"userPhone": "+7 (992) 592-8826",
		"userAddress": "764 Drewry Lane",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5016
	},
	{
		"userName": "Trina Kender",
		"userEmail": "tkenderh@sogou.com",
		"userPassword": "7z1PjVqu7",
		"userPhone": "+63 (730) 933-8550",
		"userAddress": "8702 Service Alley",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5017
	},
	{
		"userName": "Harmonie Glendinning",
		"userEmail": "hglendinningi@123-reg.co.uk",
		"userPassword": "slVOP9A54Rxy",
		"userPhone": "+235 (618) 826-1962",
		"userAddress": "102 Fordem Center",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Research",
		"userID": 5018
	},
	{
		"userName": "Lukas Pulley",
		"userEmail": "lpulleyj@wufoo.com",
		"userPassword": "ta6QLH",
		"userPhone": "+7 (798) 501-5000",
		"userAddress": "856 Westend Hill",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Teach",
		"userID": 5019
	},
	{
		"userName": "Reuven Soffe",
		"userEmail": "rsoffek@sun.com",
		"userPassword": "Qbnqt3iHcwg1",
		"userPhone": "+54 (475) 198-5456",
		"userAddress": "75 Del Sol Terrace",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Research",
		"userID": 5020
	},
	{
		"userName": "Odelia Grasser",
		"userEmail": "ograsserl@yahoo.co.jp",
		"userPassword": "CxvZcm26VZ6",
		"userPhone": "+48 (579) 730-8335",
		"userAddress": "34170 Morningstar Terrace",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5021
	},
	{
		"userName": "Sisile Lowne",
		"userEmail": "slownem@homestead.com",
		"userPassword": "Q2wRcRK",
		"userPhone": "+7 (755) 260-4736",
		"userAddress": "4 Debra Street",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5022
	},
	{
		"userName": "Sheppard Grass",
		"userEmail": "sgrassn@1und1.de",
		"userPassword": "72WOTx",
		"userPhone": "+62 (666) 502-2824",
		"userAddress": "6 Killdeer Hill",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5023
	},
	{
		"userName": "Eben Mullaney",
		"userEmail": "emullaneyo@gov.uk",
		"userPassword": "2T4NMZe3g",
		"userPhone": "+46 (943) 914-6404",
		"userAddress": "10415 Sloan Drive",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5024
	},
	{
		"userName": "Andrea O'Reilly",
		"userEmail": "aoreillyp@senate.gov",
		"userPassword": "VelrAU8UhBy",
		"userPhone": "+62 (432) 642-0729",
		"userAddress": "9321 Clemons Pass",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Teach",
		"userID": 5025
	},
	{
		"userName": "Bondon Heaney`",
		"userEmail": "bheaneyq@list-manage.com",
		"userPassword": "ZUPOnEK",
		"userPhone": "+963 (183) 477-8087",
		"userAddress": "5478 Algoma Trail",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5026
	},
	{
		"userName": "Carly Palphramand",
		"userEmail": "cpalphramandr@ucoz.ru",
		"userPassword": "A9shFf",
		"userPhone": "+380 (989) 326-5351",
		"userAddress": "62 Westridge Center",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Teach",
		"userID": 5027
	},
	{
		"userName": "Griswold Syratt",
		"userEmail": "gsyratts@sciencedaily.com",
		"userPassword": "5312kmb",
		"userPhone": "+86 (554) 744-9027",
		"userAddress": "82 Ludington Park",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Teach",
		"userID": 5028
	},
	{
		"userName": "Ellie Poter",
		"userEmail": "epotert@mysql.com",
		"userPassword": "fOnqNCAK",
		"userPhone": "+351 (193) 452-4424",
		"userAddress": "3 Waywood Trail",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5029
	},
	{
		"userName": "Biddie O'Driscole",
		"userEmail": "bodriscoleu@addthis.com",
		"userPassword": "9KdzOZ0hKe",
		"userPhone": "+674 (457) 386-9690",
		"userAddress": "12 Sunfield Road",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5030
	},
	{
		"userName": "Nikolaos Wormell",
		"userEmail": "nwormellv@home.pl",
		"userPassword": "1vzWX0E6h",
		"userPhone": "+86 (689) 166-3785",
		"userAddress": "323 Oak Circle",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5031
	},
	{
		"userName": "Devland Readett",
		"userEmail": "dreadettw@reuters.com",
		"userPassword": "90sCADbm5",
		"userPhone": "+62 (717) 150-2842",
		"userAddress": "5059 Glacier Hill Pass",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Teach",
		"userID": 5032
	},
	{
		"userName": "Portie Brownbill",
		"userEmail": "pbrownbillx@china.com.cn",
		"userPassword": "GO5Bg93E0Y",
		"userPhone": "+7 (541) 724-1966",
		"userAddress": "0 Gale Lane",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5033
	},
	{
		"userName": "Jillene McGilvary",
		"userEmail": "jmcgilvaryy@nyu.edu",
		"userPassword": "aWl9L5yr3WV",
		"userPhone": "+55 (359) 971-6364",
		"userAddress": "82940 Cottonwood Terrace",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5034
	},
	{
		"userName": "Imojean Hurring",
		"userEmail": "ihurringz@wiley.com",
		"userPassword": "TycMS6qCRzJ",
		"userPhone": "+7 (205) 539-0465",
		"userAddress": "40536 Kingsford Street",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5035
	},
	{
		"userName": "Newton MacCawley",
		"userEmail": "nmaccawley10@sohu.com",
		"userPassword": "6eASaFzm",
		"userPhone": "+389 (340) 926-1301",
		"userAddress": "434 Utah Alley",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5036
	},
	{
		"userName": "Gannon Truckett",
		"userEmail": "gtruckett11@ebay.co.uk",
		"userPassword": "hXkmxH",
		"userPhone": "+358 (535) 540-5824",
		"userAddress": "2095 Stephen Terrace",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5037
	},
	{
		"userName": "Julieta Jeynes",
		"userEmail": "jjeynes12@guardian.co.uk",
		"userPassword": "hRLnYg",
		"userPhone": "+63 (159) 105-9841",
		"userAddress": "7074 Comanche Crossing",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5038
	},
	{
		"userName": "Minette Jouaneton",
		"userEmail": "mjouaneton13@cnn.com",
		"userPassword": "GffuAcNIwPmH",
		"userPhone": "+351 (476) 673-7394",
		"userAddress": "36 Sachs Parkway",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5039
	},
	{
		"userName": "Berkeley Macbane",
		"userEmail": "bmacbane14@mapquest.com",
		"userPassword": "evEACo",
		"userPhone": "+973 (944) 107-6011",
		"userAddress": "7 Morningstar Park",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Teach",
		"userID": 5040
	},
	{
		"userName": "Fredek Losebie",
		"userEmail": "flosebie15@wisc.edu",
		"userPassword": "HfZHmb",
		"userPhone": "+86 (762) 378-0199",
		"userAddress": "13 Prentice Junction",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5041
	},
	{
		"userName": "Gregg Briggs",
		"userEmail": "gbriggs16@sphinn.com",
		"userPassword": "YY1g88Oupr",
		"userPhone": "+86 (695) 610-4772",
		"userAddress": "1931 Banding Point",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Research",
		"userID": 5042
	},
	{
		"userName": "Laurene Edlyne",
		"userEmail": "ledlyne17@ox.ac.uk",
		"userPassword": "uDz9W06V6G",
		"userPhone": "+86 (465) 275-2011",
		"userAddress": "4 Alpine Place",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5043
	},
	{
		"userName": "Remy Darell",
		"userEmail": "rdarell18@google.com.au",
		"userPassword": "rQoWYp",
		"userPhone": "+62 (541) 646-6760",
		"userAddress": "54755 Packers Road",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5044
	},
	{
		"userName": "Gallagher Franzewitch",
		"userEmail": "gfranzewitch19@dmoz.org",
		"userPassword": "Oe1rs96q",
		"userPhone": "+375 (143) 599-2269",
		"userAddress": "70 Oakridge Hill",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Teach",
		"userID": 5045
	},
	{
		"userName": "Giffie Veysey",
		"userEmail": "gveysey1a@flavors.me",
		"userPassword": "3XKz5F9LC",
		"userPhone": "+60 (397) 332-2841",
		"userAddress": "58406 Bobwhite Point",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5046
	},
	{
		"userName": "Nial Lambdin",
		"userEmail": "nlambdin1b@harvard.edu",
		"userPassword": "atQBNEUWxQc",
		"userPhone": "+48 (586) 702-8493",
		"userAddress": "4 Calypso Road",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5047
	},
	{
		"userName": "Rebe Layhe",
		"userEmail": "rlayhe1c@cbslocal.com",
		"userPassword": "Ftn5DXc",
		"userPhone": "+33 (383) 953-2024",
		"userAddress": "7 Garrison Alley",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5048
	},
	{
		"userName": "Wallie Mara",
		"userEmail": "wmara1d@amazon.com",
		"userPassword": "3bL4lffh",
		"userPhone": "+591 (704) 259-5162",
		"userAddress": "31958 Macpherson Court",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5049
	},
	{
		"userName": "Lucretia Guillain",
		"userEmail": "lguillain1e@gmpg.org",
		"userPassword": "rZkLbq",
		"userPhone": "+86 (979) 947-1111",
		"userAddress": "626 Monterey Drive",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5050
	},
	{
		"userName": "Robina Hospital",
		"userEmail": "rhospital1f@taobao.com",
		"userPassword": "DK0pTPMX",
		"userPhone": "+86 (238) 241-8335",
		"userAddress": "12 Stoughton Court",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Teach",
		"userID": 5051
	},
	{
		"userName": "Lamond Rattray",
		"userEmail": "lrattray1g@360.cn",
		"userPassword": "s34yynGCzN",
		"userPhone": "+66 (178) 372-6766",
		"userAddress": "2181 Clyde Gallagher Pass",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Teach",
		"userID": 5052
	},
	{
		"userName": "Trever Innett",
		"userEmail": "tinnett1h@dot.gov",
		"userPassword": "SYpAdVdQkBi",
		"userPhone": "+62 (854) 663-9787",
		"userAddress": "92264 Graedel Point",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Research",
		"userID": 5053
	},
	{
		"userName": "Claudian Dolder",
		"userEmail": "cdolder1i@stanford.edu",
		"userPassword": "q4Wj09Yba",
		"userPhone": "+86 (157) 869-2717",
		"userAddress": "85 Weeping Birch Place",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5054
	},
	{
		"userName": "Valma Springer",
		"userEmail": "vspringer1j@odnoklassniki.ru",
		"userPassword": "DpeBbYK",
		"userPhone": "+62 (961) 412-3426",
		"userAddress": "3445 Kim Plaza",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5055
	},
	{
		"userName": "Lanni Rasher",
		"userEmail": "lrasher1k@cloudflare.com",
		"userPassword": "FQPJQ650dUG",
		"userPhone": "+54 (881) 451-3882",
		"userAddress": "11 Springview Court",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5056
	},
	{
		"userName": "Kara Rojel",
		"userEmail": "krojel1l@businessweek.com",
		"userPassword": "7LV7FrP",
		"userPhone": "+7 (712) 204-5331",
		"userAddress": "54855 Brentwood Crossing",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5057
	},
	{
		"userName": "Magdalena Finci",
		"userEmail": "mfinci1m@accuweather.com",
		"userPassword": "yt1ztcbpqh2",
		"userPhone": "+27 (299) 342-3992",
		"userAddress": "7176 Shoshone Plaza",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Research",
		"userID": 5058
	},
	{
		"userName": "Sidney Gundry",
		"userEmail": "sgundry1n@state.gov",
		"userPassword": "GENNtwi7d",
		"userPhone": "+380 (201) 990-0216",
		"userAddress": "06 Esker Plaza",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5059
	},
	{
		"userName": "Forester MacFadden",
		"userEmail": "fmacfadden1o@berkeley.edu",
		"userPassword": "LpOWSa",
		"userPhone": "+48 (679) 662-9597",
		"userAddress": "2 Old Shore Place",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5060
	},
	{
		"userName": "Cassi Dmitrovic",
		"userEmail": "cdmitrovic1p@unesco.org",
		"userPassword": "ZKlJpIirh4",
		"userPhone": "+27 (375) 336-8514",
		"userAddress": "1135 6th Place",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5061
	},
	{
		"userName": "Inger Belton",
		"userEmail": "ibelton1q@bluehost.com",
		"userPassword": "PWuQwttnlg5",
		"userPhone": "+358 (507) 161-3475",
		"userAddress": "83567 Spenser Point",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5062
	},
	{
		"userName": "Catlaina Woolerton",
		"userEmail": "cwoolerton1r@vk.com",
		"userPassword": "6FnTuBwouVW",
		"userPhone": "+359 (836) 156-6386",
		"userAddress": "2625 Mosinee Terrace",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Research",
		"userID": 5063
	},
	{
		"userName": "Winona Villaron",
		"userEmail": "wvillaron1s@joomla.org",
		"userPassword": "XjF2Xto",
		"userPhone": "+355 (935) 955-6923",
		"userAddress": "0097 Schiller Street",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5064
	},
	{
		"userName": "Koral Tomsa",
		"userEmail": "ktomsa1t@nba.com",
		"userPassword": "3Y5ydNQp",
		"userPhone": "+966 (117) 750-6566",
		"userAddress": "4402 Thompson Circle",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Teach",
		"userID": 5065
	},
	{
		"userName": "Barry Schroter",
		"userEmail": "bschroter1u@fastcompany.com",
		"userPassword": "IPQ4BvzcO6x2",
		"userPhone": "+62 (994) 207-9679",
		"userAddress": "802 Sunfield Lane",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Research",
		"userID": 5066
	},
	{
		"userName": "Kelly Dallaghan",
		"userEmail": "kdallaghan1v@narod.ru",
		"userPassword": "s6DHkw7C",
		"userPhone": "+33 (445) 157-1152",
		"userAddress": "9728 Walton Pass",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5067
	},
	{
		"userName": "Rahal Caddies",
		"userEmail": "rcaddies1w@utexas.edu",
		"userPassword": "vT8MLPUHY",
		"userPhone": "+352 (100) 719-3098",
		"userAddress": "5 Southridge Alley",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5068
	},
	{
		"userName": "Billye Gatling",
		"userEmail": "bgatling1x@4shared.com",
		"userPassword": "iJCxTAblFU",
		"userPhone": "+1 (864) 763-7118",
		"userAddress": "31998 Schiller Hill",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5069
	},
	{
		"userName": "Jethro Adamov",
		"userEmail": "jadamov1y@chronoengine.com",
		"userPassword": "DCLcQBPJj9",
		"userPhone": "+86 (697) 662-5804",
		"userAddress": "066 Westport Hill",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Teach",
		"userID": 5070
	},
	{
		"userName": "Kippy O'Crevy",
		"userEmail": "kocrevy1z@google.com",
		"userPassword": "Xn1E7YFOY",
		"userPhone": "+371 (522) 781-0162",
		"userAddress": "7299 Crowley Circle",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Research",
		"userID": 5071
	},
	{
		"userName": "Mario Eymer",
		"userEmail": "meymer20@tinyurl.com",
		"userPassword": "bZ72kopvjc",
		"userPhone": "+351 (736) 267-7190",
		"userAddress": "79921 Red Cloud Trail",
		"userType": "Faculty",
		"fRank": "Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Teach",
		"userID": 5072
	},
	{
		"userName": "Nara Doodney",
		"userEmail": "ndoodney21@soup.io",
		"userPassword": "Hc3iB5I",
		"userPhone": "+62 (529) 507-2421",
		"userAddress": "2 Loftsgordon Trail",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$15 ",
		"teachOrResearch": "Teach",
		"userID": 5073
	},
	{
		"userName": "Evangelina Goold",
		"userEmail": "egoold22@pagesperso-orange.fr",
		"userPassword": "4rmQdbr",
		"userPhone": "+33 (537) 107-7261",
		"userAddress": "3755 Red Cloud Alley",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Teach",
		"userID": 5074
	},
	{
		"userName": "Lonny Emanuel",
		"userEmail": "lemanuel23@alibaba.com",
		"userPassword": "TT8jWpLokSW",
		"userPhone": "+86 (931) 397-9181",
		"userAddress": "17702 Warner Court",
		"userType": "Faculty",
		"fRank": "Assistant Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Teach",
		"userID": 5075
	},
	{
		"userName": "Kynthia Lytton",
		"userEmail": "klytton24@businesswire.com",
		"userPassword": "ymAsRZ0cJu",
		"userPhone": "+237 (820) 118-8675",
		"userAddress": "75483 Roxbury Parkway",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$19 ",
		"teachOrResearch": "Research",
		"userID": 5076
	},
	{
		"userName": "Bell Kilrow",
		"userEmail": "bkilrow25@google.de",
		"userPassword": "EGbj9G5",
		"userPhone": "+357 (675) 369-1701",
		"userAddress": "9333 Tony Road",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$16 ",
		"teachOrResearch": "Research",
		"userID": 5077
	},
	{
		"userName": "Donica Poulsom",
		"userEmail": "dpoulsom26@deliciousdays.com",
		"userPassword": "QEgjhh",
		"userPhone": "+963 (969) 803-6024",
		"userAddress": "596 Fisk Plaza",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$17 ",
		"teachOrResearch": "Teach",
		"userID": 5078
	},
	{
		"userName": "Filmer McLardie",
		"userEmail": "fmclardie27@gizmodo.com",
		"userPassword": "H2hH1up1J5QD",
		"userPhone": "+86 (328) 329-2198",
		"userAddress": "0 Hollow Ridge Center",
		"userType": "Faculty",
		"fRank": "Associate Professor",
		"isFullTime": false,
		"hourlyPay": "$18 ",
		"teachOrResearch": "Teach",
		"userID": 5079
	}
];
export default partTimeFaculty;
