const researcher = [
	{
		"userName": "Carlotta Cotgrove",
		"userEmail": "ccotgrove0@statcounter.com",
		"userPassword": "TxHtu4",
		"userPhone": "(528) 2497575",
		"userAddress": "75 Mcguire Place",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 190,
		"userID": 9500
	},
	{
		"userName": "Marley Kingston",
		"userEmail": "mkingston1@surveymonkey.com",
		"userPassword": "nVwNbtqVTq58",
		"userPhone": "(979) 7364450",
		"userAddress": "7487 Spaight Point",
		"userType": "Researcher",
		"researchSalary": "$75,000 ",
		"researchOfficeNum": 190,
		"userID": 9501
	},
	{
		"userName": "Suzanna Joscelyne",
		"userEmail": "sjoscelyne2@naver.com",
		"userPassword": "7z3IzHjGw",
		"userPhone": "(402) 5091845",
		"userAddress": "95274 Fieldstone Parkway",
		"userType": "Researcher",
		"researchSalary": "$75,000 ",
		"researchOfficeNum": 191,
		"userID": 9502
	},
	{
		"userName": "Mathilde Isacsson",
		"userEmail": "misacsson3@exblog.jp",
		"userPassword": "arzNAU4Jlai",
		"userPhone": "(196) 9980810",
		"userAddress": "40167 Mariners Cove Junction",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 191,
		"userID": 9503
	},
	{
		"userName": "Natalee Anker",
		"userEmail": "nanker4@over-blog.com",
		"userPassword": "QLnpmoxtxN",
		"userPhone": "(815) 5441431",
		"userAddress": "8 Northfield Plaza",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 192,
		"userID": 9504
	},
	{
		"userName": "Simone Tesimon",
		"userEmail": "stesimon5@reuters.com",
		"userPassword": "RwZhJ5",
		"userPhone": "(756) 9309824",
		"userAddress": "9 Scofield Way",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 192,
		"userID": 9505
	},
	{
		"userName": "Bordie Corneille",
		"userEmail": "bcorneille6@bigcartel.com",
		"userPassword": "tgoY5x",
		"userPhone": "(581) 2910043",
		"userAddress": "7015 Beilfuss Alley",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 193,
		"userID": 9506
	},
	{
		"userName": "Florian Rafe",
		"userEmail": "frafe7@time.com",
		"userPassword": "rMONuy2XARf",
		"userPhone": "(466) 7452209",
		"userAddress": "8 Spohn Place",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 193,
		"userID": 9507
	},
	{
		"userName": "Darcy Halso",
		"userEmail": "dhalso8@tmall.com",
		"userPassword": "kFkAV1ViPQ7i",
		"userPhone": "(190) 8594361",
		"userAddress": "01384 Monica Alley",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 194,
		"userID": 9508
	},
	{
		"userName": "Priscella Frederick",
		"userEmail": "pfrederick9@google.ru",
		"userPassword": "Y2ssJgdp",
		"userPhone": "(313) 7966342",
		"userAddress": "4972 Fairview Hill",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 194,
		"userID": 9509
	},
	{
		"userName": "Annabelle Lusgdin",
		"userEmail": "alusgdina@wired.com",
		"userPassword": "AGoqEMKCZF",
		"userPhone": "(925) 7367362",
		"userAddress": "311 Memorial Point",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 195,
		"userID": 9510
	},
	{
		"userName": "Regan Sterling",
		"userEmail": "rsterlingb@desdev.cn",
		"userPassword": "VEmO8K",
		"userPhone": "(140) 7223990",
		"userAddress": "986 Ronald Regan Circle",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 195,
		"userID": 9511
	},
	{
		"userName": "Kaela Freda",
		"userEmail": "kfredac@adobe.com",
		"userPassword": "Assl9iIXfT",
		"userPhone": "(168) 5902494",
		"userAddress": "63450 Talmadge Park",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 196,
		"userID": 9512
	},
	{
		"userName": "Billy Todman",
		"userEmail": "btodmand@ask.com",
		"userPassword": "jJbiKy",
		"userPhone": "(104) 9776308",
		"userAddress": "60332 Summerview Way",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 196,
		"userID": 9513
	},
	{
		"userName": "Golda Dancer",
		"userEmail": "gdancere@slate.com",
		"userPassword": "1ZzIh5",
		"userPhone": "(821) 2287291",
		"userAddress": "41929 Ryan Circle",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 197,
		"userID": 9514
	},
	{
		"userName": "Keenan Mc Harg",
		"userEmail": "kmcf@vk.com",
		"userPassword": "Z7DmVI",
		"userPhone": "(886) 9531073",
		"userAddress": "3 Vera Trail",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 197,
		"userID": 9515
	},
	{
		"userName": "Ardyth Human",
		"userEmail": "ahumang@wp.com",
		"userPassword": "zdQ7Dxk58",
		"userPhone": "(194) 2581616",
		"userAddress": "34969 Maple Terrace",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 198,
		"userID": 9516
	},
	{
		"userName": "Starlin Cordon",
		"userEmail": "scordonh@ucoz.ru",
		"userPassword": "ln9HQ2bSG3I",
		"userPhone": "(255) 7009219",
		"userAddress": "02658 Prentice Terrace",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 198,
		"userID": 9517
	},
	{
		"userName": "Darb Rhubottom",
		"userEmail": "drhubottomi@360.cn",
		"userPassword": "Sb6TiL",
		"userPhone": "(101) 5322051",
		"userAddress": "88935 Carberry Avenue",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 199,
		"userID": 9518
	},
	{
		"userName": "Adore Sherbrook",
		"userEmail": "asherbrookj@reuters.com",
		"userPassword": "T6UFbh1",
		"userPhone": "(729) 8965731",
		"userAddress": "33093 Rutledge Place",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 199,
		"userID": 9519
	},
	{
		"userName": "Shawn Keenor",
		"userEmail": "skeenork@pagesperso-orange.fr",
		"userPassword": "ortyVNQsrX3X",
		"userPhone": "(205) 9333072",
		"userAddress": "20 Gateway Trail",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 200,
		"userID": 9520
	},
	{
		"userName": "Chancey Knoller",
		"userEmail": "cknollerl@t.co",
		"userPassword": "evjRyiSMs",
		"userPhone": "(754) 2909860",
		"userAddress": "97 Fisk Terrace",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 200,
		"userID": 9521
	},
	{
		"userName": "Robenia Sore",
		"userEmail": "rsorem@state.gov",
		"userPassword": "w5W3Yu",
		"userPhone": "(104) 1129748",
		"userAddress": "7 Grim Parkway",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 201,
		"userID": 9522
	},
	{
		"userName": "Ogdon Calderonello",
		"userEmail": "ocalderonellon@cnn.com",
		"userPassword": "vFNBRec6Ja",
		"userPhone": "(355) 7860471",
		"userAddress": "4224 Tennessee Place",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 201,
		"userID": 9523
	},
	{
		"userName": "Ase Cobain",
		"userEmail": "acobaino@webs.com",
		"userPassword": "1RmmuoAWaJ5",
		"userPhone": "(228) 7170620",
		"userAddress": "7 Manufacturers Pass",
		"userType": "Researcher",
		"researchSalary": "$75,000 ",
		"researchOfficeNum": 201,
		"userID": 9524
	}
];
export default researcher;
