const undergraduatePartTime = [
	{
		"userName": "Ricca Seeler",
		"userEmail": "rseeler0@ft.com",
		"userPassword": "SHNgUzFj",
		"userPhone": "(664) 3301773",
		"userAddress": "647 Fremont Terrace",
		"userType": "Student",
		"sGPA": 2.5,
		"sGradYear": 2017,
		"sDOB": "11/21/1985",
		"totalCredits": 36,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3000
	},
	{
		"userName": "Janelle Waiton",
		"userEmail": "jwaiton1@php.net",
		"userPassword": "21Ie69lL32q",
		"userPhone": "(415) 9547628",
		"userAddress": "052 Ramsey Crossing",
		"userType": "Student",
		"sGPA": 1.6,
		"sGradYear": 2018,
		"sDOB": "12/27/2002",
		"totalCredits": 88,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3001
	},
	{
		"userName": "Cyrill Torns",
		"userEmail": "ctorns2@etsy.com",
		"userPassword": "coRs1psoUs",
		"userPhone": "(139) 9069109",
		"userAddress": "5416 Orin Way",
		"userType": "Student",
		"sGPA": 2.8,
		"sGradYear": 2019,
		"sDOB": "6/19/1987",
		"totalCredits": 4,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3002
	},
	{
		"userName": "Kaia Vear",
		"userEmail": "kvear3@va.gov",
		"userPassword": "u1oRypTEc",
		"userPhone": "(380) 3753877",
		"userAddress": "1 Grasskamp Alley",
		"userType": "Student",
		"sGPA": 3,
		"sGradYear": 2020,
		"sDOB": "12/6/1994",
		"totalCredits": 120,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3003
	},
	{
		"userName": "Car Buddles",
		"userEmail": "cbuddles4@reuters.com",
		"userPassword": "1MTehl",
		"userPhone": "(884) 2341622",
		"userAddress": "383 Clyde Gallagher Trail",
		"userType": "Student",
		"sGPA": 3.1,
		"sGradYear": 2021,
		"sDOB": "2/2/1987",
		"totalCredits": 16,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3004
	},
	{
		"userName": "Oates Small",
		"userEmail": "osmall5@mlb.com",
		"userPassword": "6rCpTPLcDc",
		"userPhone": "(890) 6980491",
		"userAddress": "007 Loomis Terrace",
		"userType": "Student",
		"sGPA": 1.6,
		"sGradYear": 2022,
		"sDOB": "11/17/1983",
		"totalCredits": 12,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3005
	},
	{
		"userName": "Vito Flintoff",
		"userEmail": "vflintoff6@smugmug.com",
		"userPassword": "vucccEC",
		"userPhone": "(353) 2974436",
		"userAddress": "937 Marquette Avenue",
		"userType": "Student",
		"sGPA": 3.5,
		"sGradYear": 2023,
		"sDOB": "6/18/2000",
		"totalCredits": 60,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3006
	},
	{
		"userName": "Haleigh Fagge",
		"userEmail": "hfagge7@zdnet.com",
		"userPassword": "dJSRJuzSlG5S",
		"userPhone": "(579) 7406111",
		"userAddress": "019 Redwing Park",
		"userType": "Student",
		"sGPA": 1.8,
		"sGradYear": 2024,
		"sDOB": "1/7/1982",
		"totalCredits": 12,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3007
	},
	{
		"userName": "Glen Banbury",
		"userEmail": "gbanbury8@sciencedirect.com",
		"userPassword": "rI7DIcgnG",
		"userPhone": "(849) 6444667",
		"userAddress": "9 Mifflin Junction",
		"userType": "Student",
		"sGPA": 2.9,
		"sGradYear": 2025,
		"sDOB": "5/7/1994",
		"totalCredits": 44,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3008
	},
	{
		"userName": "Lauraine Elgie",
		"userEmail": "lelgie9@google.it",
		"userPassword": "CHwNFv5XlY",
		"userPhone": "(958) 1351809",
		"userAddress": "27534 Kropf Street",
		"userType": "Student",
		"sGPA": 2.5,
		"sGradYear": 2026,
		"sDOB": "2/3/2001",
		"totalCredits": 60,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3009
	},
	{
		"userName": "Trista Dwelley",
		"userEmail": "tdwelleya@dion.ne.jp",
		"userPassword": "TyT6NraeO",
		"userPhone": "(988) 2860553",
		"userAddress": "86164 Haas Plaza",
		"userType": "Student",
		"sGPA": 2,
		"sGradYear": 2017,
		"sDOB": "8/3/1988",
		"totalCredits": 68,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3010
	},
	{
		"userName": "Salvador Nerney",
		"userEmail": "snerneyb@quantcast.com",
		"userPassword": "lLneavvmFICN",
		"userPhone": "(343) 6964977",
		"userAddress": "7 Farmco Trail",
		"userType": "Student",
		"sGPA": 3.8,
		"sGradYear": 2018,
		"sDOB": "1/15/2003",
		"totalCredits": 64,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3011
	},
	{
		"userName": "Walker Ramsbotham",
		"userEmail": "wramsbothamc@jugem.jp",
		"userPassword": "3rSfQdrZRF",
		"userPhone": "(364) 9000133",
		"userAddress": "117 Talisman Way",
		"userType": "Student",
		"sGPA": 2.6,
		"sGradYear": 2019,
		"sDOB": "2/8/1993",
		"totalCredits": 28,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3012
	},
	{
		"userName": "Theodosia Franses",
		"userEmail": "tfransesd@addtoany.com",
		"userPassword": "QGciuP",
		"userPhone": "(646) 7899174",
		"userAddress": "241 Havey Circle",
		"userType": "Student",
		"sGPA": 2,
		"sGradYear": 2020,
		"sDOB": "4/22/1992",
		"totalCredits": 84,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3013
	},
	{
		"userName": "Alfie Kingsbury",
		"userEmail": "akingsburye@nba.com",
		"userPassword": "8CoKAixmi",
		"userPhone": "(104) 1035783",
		"userAddress": "796 Talisman Plaza",
		"userType": "Student",
		"sGPA": 3.9,
		"sGradYear": 2021,
		"sDOB": "7/6/1991",
		"totalCredits": 36,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3014
	},
	{
		"userName": "Anthiathia Tuminini",
		"userEmail": "atumininif@youtube.com",
		"userPassword": "X17VMEy4",
		"userPhone": "(429) 2225323",
		"userAddress": "9556 Summer Ridge Way",
		"userType": "Student",
		"sGPA": 2.9,
		"sGradYear": 2022,
		"sDOB": "3/15/1987",
		"totalCredits": 100,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3015
	},
	{
		"userName": "Christen Reckus",
		"userEmail": "creckusg@uol.com.br",
		"userPassword": "UXa2fP",
		"userPhone": "(867) 8475328",
		"userAddress": "03 Magdeline Junction",
		"userType": "Student",
		"sGPA": 3.9,
		"sGradYear": 2023,
		"sDOB": "6/17/2003",
		"totalCredits": 8,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3016
	},
	{
		"userName": "Junette Kissock",
		"userEmail": "jkissockh@discovery.com",
		"userPassword": "cdcuIEg",
		"userPhone": "(409) 1936677",
		"userAddress": "4 Claremont Lane",
		"userType": "Student",
		"sGPA": 2.7,
		"sGradYear": 2024,
		"sDOB": "10/19/1994",
		"totalCredits": 40,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3017
	},
	{
		"userName": "Gallagher Van der Velden",
		"userEmail": "gvani@dmoz.org",
		"userPassword": "V6eMmFoPn",
		"userPhone": "(105) 9137163",
		"userAddress": "168 Vermont Avenue",
		"userType": "Student",
		"sGPA": 3.4,
		"sGradYear": 2025,
		"sDOB": "6/4/1995",
		"totalCredits": 52,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3018
	},
	{
		"userName": "Katey Ubsdell",
		"userEmail": "kubsdellj@home.pl",
		"userPassword": "naGBdSJKxTN",
		"userPhone": "(663) 8570158",
		"userAddress": "95 Doe Crossing Junction",
		"userType": "Student",
		"sGPA": 3.5,
		"sGradYear": 2026,
		"sDOB": "11/3/1984",
		"totalCredits": 64,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3019
	},
	{
		"userName": "Alikee Sprull",
		"userEmail": "asprullk@symantec.com",
		"userPassword": "UtcymvN",
		"userPhone": "(592) 5926979",
		"userAddress": "9515 Burrows Park",
		"userType": "Student",
		"sGPA": 2.4,
		"sGradYear": 2017,
		"sDOB": "4/27/2002",
		"totalCredits": 112,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3020
	},
	{
		"userName": "Kiley Mazin",
		"userEmail": "kmazinl@tuttocitta.it",
		"userPassword": "TfftZqMQDs",
		"userPhone": "(204) 9051793",
		"userAddress": "96162 Hallows Place",
		"userType": "Student",
		"sGPA": 3.5,
		"sGradYear": 2018,
		"sDOB": "10/15/1993",
		"totalCredits": 36,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3021
	},
	{
		"userName": "Raff Gummory",
		"userEmail": "rgummorym@mapquest.com",
		"userPassword": "Ll0kblji",
		"userPhone": "(840) 5108222",
		"userAddress": "27 Truax Park",
		"userType": "Student",
		"sGPA": 3,
		"sGradYear": 2019,
		"sDOB": "4/11/1984",
		"totalCredits": 92,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3022
	},
	{
		"userName": "Amabelle Sirey",
		"userEmail": "asireyn@hubpages.com",
		"userPassword": "Con76eA6Ki5",
		"userPhone": "(893) 1432969",
		"userAddress": "78 Grayhawk Place",
		"userType": "Student",
		"sGPA": 2.3,
		"sGradYear": 2020,
		"sDOB": "4/25/1987",
		"totalCredits": 96,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3023
	},
	{
		"userName": "Clementius Ingliss",
		"userEmail": "cinglisso@tripod.com",
		"userPassword": "MflyyF",
		"userPhone": "(451) 6052708",
		"userAddress": "782 Cody Park",
		"userType": "Student",
		"sGPA": 3.9,
		"sGradYear": 2021,
		"sDOB": "4/22/1994",
		"totalCredits": 40,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3024
	},
	{
		"userName": "Alicia Gyford",
		"userEmail": "agyfordp@newyorker.com",
		"userPassword": "n97y9wtG3",
		"userPhone": "(669) 1289146",
		"userAddress": "82430 Lawn Place",
		"userType": "Student",
		"sGPA": 2.2,
		"sGradYear": 2022,
		"sDOB": "7/20/1988",
		"totalCredits": 112,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3025
	},
	{
		"userName": "Xymenes Pahlsson",
		"userEmail": "xpahlssonq@scribd.com",
		"userPassword": "tc96o1B3",
		"userPhone": "(265) 3140629",
		"userAddress": "173 Algoma Terrace",
		"userType": "Student",
		"sGPA": 2.3,
		"sGradYear": 2023,
		"sDOB": "2/8/2003",
		"totalCredits": 40,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3026
	},
	{
		"userName": "Monique Hunnable",
		"userEmail": "mhunnabler@mashable.com",
		"userPassword": "r8cFGFh",
		"userPhone": "(170) 6363638",
		"userAddress": "82085 Schlimgen Pass",
		"userType": "Student",
		"sGPA": 3.3,
		"sGradYear": 2024,
		"sDOB": "9/16/1989",
		"totalCredits": 104,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3027
	},
	{
		"userName": "Brant Hansie",
		"userEmail": "bhansies@mozilla.com",
		"userPassword": "gIks8zPC6lU",
		"userPhone": "(800) 9388912",
		"userAddress": "1 Lukken Terrace",
		"userType": "Student",
		"sGPA": 3.1,
		"sGradYear": 2025,
		"sDOB": "4/22/1989",
		"totalCredits": 96,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3028
	},
	{
		"userName": "Silvain Aleswell",
		"userEmail": "saleswellt@mail.ru",
		"userPassword": "LdDSVgjDb",
		"userPhone": "(767) 9101871",
		"userAddress": "907 Kipling Center",
		"userType": "Student",
		"sGPA": 2,
		"sGradYear": 2026,
		"sDOB": "9/3/2003",
		"totalCredits": 88,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3029
	},
	{
		"userName": "Jarred Bownass",
		"userEmail": "jbownassu@un.org",
		"userPassword": "H17CHCwo0",
		"userPhone": "(340) 8693870",
		"userAddress": "72999 Old Gate Junction",
		"userType": "Student",
		"sGPA": 2.3,
		"sGradYear": 2017,
		"sDOB": "7/16/1981",
		"totalCredits": 100,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3030
	},
	{
		"userName": "Danika Jiggen",
		"userEmail": "djiggenv@oracle.com",
		"userPassword": "A691SeGSC0",
		"userPhone": "(183) 7886453",
		"userAddress": "1239 Lillian Junction",
		"userType": "Student",
		"sGPA": 1.1,
		"sGradYear": 2018,
		"sDOB": "10/18/1996",
		"totalCredits": 68,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3031
	},
	{
		"userName": "Micki Camble",
		"userEmail": "mcamblew@usatoday.com",
		"userPassword": "aLCahz90P",
		"userPhone": "(214) 3774889",
		"userAddress": "09783 Towne Road",
		"userType": "Student",
		"sGPA": 2,
		"sGradYear": 2019,
		"sDOB": "8/8/2003",
		"totalCredits": 108,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3032
	},
	{
		"userName": "Douglass MacCaughey",
		"userEmail": "dmaccaugheyx@twitter.com",
		"userPassword": "gVS2FWtgfBq",
		"userPhone": "(154) 6284396",
		"userAddress": "639 Muir Plaza",
		"userType": "Student",
		"sGPA": 1.7,
		"sGradYear": 2020,
		"sDOB": "6/13/1982",
		"totalCredits": 24,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3033
	},
	{
		"userName": "Ethel Birmingham",
		"userEmail": "ebirminghamy@hubpages.com",
		"userPassword": "ZC3tbP0lfG",
		"userPhone": "(251) 3909612",
		"userAddress": "949 8th Court",
		"userType": "Student",
		"sGPA": 2.4,
		"sGradYear": 2021,
		"sDOB": "5/11/1985",
		"totalCredits": 48,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3034
	},
	{
		"userName": "Gayle Burkin",
		"userEmail": "gburkinz@zdnet.com",
		"userPassword": "F6RMR2Li93f",
		"userPhone": "(807) 6453789",
		"userAddress": "42 Oneill Plaza",
		"userType": "Student",
		"sGPA": 2.4,
		"sGradYear": 2022,
		"sDOB": "1/27/1986",
		"totalCredits": 12,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3035
	},
	{
		"userName": "Lesya Hendricks",
		"userEmail": "lhendricks10@shop-pro.jp",
		"userPassword": "OrV9wEtYR0",
		"userPhone": "(538) 6271302",
		"userAddress": "142 Portage Terrace",
		"userType": "Student",
		"sGPA": 3,
		"sGradYear": 2023,
		"sDOB": "10/11/1986",
		"totalCredits": 40,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3036
	},
	{
		"userName": "Natalya Jessel",
		"userEmail": "njessel11@eepurl.com",
		"userPassword": "hfuNAzd4rTQ",
		"userPhone": "(680) 8593344",
		"userAddress": "5809 Melody Parkway",
		"userType": "Student",
		"sGPA": 3.8,
		"sGradYear": 2024,
		"sDOB": "2/21/1996",
		"totalCredits": 116,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3037
	},
	{
		"userName": "Arron Tongue",
		"userEmail": "atongue12@is.gd",
		"userPassword": "1FlCy2rz",
		"userPhone": "(837) 7477156",
		"userAddress": "63899 Coolidge Street",
		"userType": "Student",
		"sGPA": 1.7,
		"sGradYear": 2025,
		"sDOB": "5/7/1991",
		"totalCredits": 64,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3038
	},
	{
		"userName": "Selle Kuller",
		"userEmail": "skuller13@bbc.co.uk",
		"userPassword": "qeLhFXw",
		"userPhone": "(314) 3563053",
		"userAddress": "21576 Merrick Trail",
		"userType": "Student",
		"sGPA": 3,
		"sGradYear": 2026,
		"sDOB": "5/14/1985",
		"totalCredits": 108,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3039
	},
	{
		"userName": "Hallie Bellringer",
		"userEmail": "hbellringer14@msn.com",
		"userPassword": "2Jra05qA",
		"userPhone": "(231) 2059737",
		"userAddress": "1691 Waywood Terrace",
		"userType": "Student",
		"sGPA": 3.1,
		"sGradYear": 2017,
		"sDOB": "9/25/2001",
		"totalCredits": 44,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3040
	},
	{
		"userName": "Baxter Rucklidge",
		"userEmail": "brucklidge15@newyorker.com",
		"userPassword": "mKQWOQT",
		"userPhone": "(165) 8682899",
		"userAddress": "516 Basil Plaza",
		"userType": "Student",
		"sGPA": 1.1,
		"sGradYear": 2018,
		"sDOB": "10/9/1983",
		"totalCredits": 56,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3041
	},
	{
		"userName": "Clare Leverett",
		"userEmail": "cleverett16@businessweek.com",
		"userPassword": "QD3wXb",
		"userPhone": "(730) 6020546",
		"userAddress": "8 Ludington Point",
		"userType": "Student",
		"sGPA": 3.4,
		"sGradYear": 2019,
		"sDOB": "4/12/1984",
		"totalCredits": 100,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3042
	},
	{
		"userName": "Douglas Fero",
		"userEmail": "dfero17@columbia.edu",
		"userPassword": "oOk3KTzHrt5",
		"userPhone": "(736) 6962639",
		"userAddress": "2929 Buell Place",
		"userType": "Student",
		"sGPA": 2.8,
		"sGradYear": 2020,
		"sDOB": "5/6/1980",
		"totalCredits": 100,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3043
	},
	{
		"userName": "Hermie Cabedo",
		"userEmail": "hcabedo18@economist.com",
		"userPassword": "86aXwA6kbOUC",
		"userPhone": "(630) 6024735",
		"userAddress": "61436 Ilene Crossing",
		"userType": "Student",
		"sGPA": 2.7,
		"sGradYear": 2021,
		"sDOB": "1/22/1996",
		"totalCredits": 20,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3044
	},
	{
		"userName": "Elvira Rintoul",
		"userEmail": "erintoul19@cdc.gov",
		"userPassword": "tgiM81kuUg",
		"userPhone": "(469) 7912564",
		"userAddress": "80 Blaine Hill",
		"userType": "Student",
		"sGPA": 3.9,
		"sGradYear": 2022,
		"sDOB": "3/13/1991",
		"totalCredits": 88,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3045
	},
	{
		"userName": "Barron Bisatt",
		"userEmail": "bbisatt1a@vkontakte.ru",
		"userPassword": "o3FDwblF",
		"userPhone": "(264) 6566145",
		"userAddress": "999 Vernon Street",
		"userType": "Student",
		"sGPA": 2.5,
		"sGradYear": 2023,
		"sDOB": "7/29/1984",
		"totalCredits": 4,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3046
	},
	{
		"userName": "Allyn Finnie",
		"userEmail": "afinnie1b@addthis.com",
		"userPassword": "Sk8mcAx2",
		"userPhone": "(765) 8357460",
		"userAddress": "7097 Northport Park",
		"userType": "Student",
		"sGPA": 3.1,
		"sGradYear": 2024,
		"sDOB": "7/22/1995",
		"totalCredits": 88,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3047
	},
	{
		"userName": "Feliza Maddocks",
		"userEmail": "fmaddocks1c@vinaora.com",
		"userPassword": "JgYCTq7K",
		"userPhone": "(252) 1962364",
		"userAddress": "88 Northport Parkway",
		"userType": "Student",
		"sGPA": 3.3,
		"sGradYear": 2025,
		"sDOB": "8/15/1995",
		"totalCredits": 8,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3048
	},
	{
		"userName": "Lorry Panton",
		"userEmail": "lpanton1d@nih.gov",
		"userPassword": "0BpHmGXEq",
		"userPhone": "(670) 8246752",
		"userAddress": "4 Autumn Leaf Way",
		"userType": "Student",
		"sGPA": 1.5,
		"sGradYear": 2026,
		"sDOB": "10/26/2000",
		"totalCredits": 100,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3049
	},
	{
		"userName": "Glenn Oxtiby",
		"userEmail": "goxtiby1e@theglobeandmail.com",
		"userPassword": "8YC85Guk",
		"userPhone": "(438) 9348992",
		"userAddress": "43699 Kings Junction",
		"userType": "Student",
		"sGPA": 2.3,
		"sGradYear": 2017,
		"sDOB": "5/19/1986",
		"totalCredits": 48,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3050
	},
	{
		"userName": "Sauveur Mecco",
		"userEmail": "smecco1f@mac.com",
		"userPassword": "IX20Y3Rj",
		"userPhone": "(865) 1580828",
		"userAddress": "45949 Dryden Avenue",
		"userType": "Student",
		"sGPA": 1.3,
		"sGradYear": 2018,
		"sDOB": "12/13/1988",
		"totalCredits": 96,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3051
	},
	{
		"userName": "Lucretia Pendlebury",
		"userEmail": "lpendlebury1g@amazonaws.com",
		"userPassword": "2baC8o2vQd",
		"userPhone": "(693) 6825113",
		"userAddress": "47 Eagle Crest Junction",
		"userType": "Student",
		"sGPA": 2.4,
		"sGradYear": 2019,
		"sDOB": "2/3/1998",
		"totalCredits": 72,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3052
	},
	{
		"userName": "Rozalin Laughren",
		"userEmail": "rlaughren1h@nymag.com",
		"userPassword": "2mMkEwj4",
		"userPhone": "(642) 1093992",
		"userAddress": "234 Pepper Wood Park",
		"userType": "Student",
		"sGPA": 2.4,
		"sGradYear": 2020,
		"sDOB": "5/25/2001",
		"totalCredits": 64,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3053
	},
	{
		"userName": "Moore Stonehewer",
		"userEmail": "mstonehewer1i@sitemeter.com",
		"userPassword": "e1lkVGuJUjTf",
		"userPhone": "(842) 7673725",
		"userAddress": "28983 Claremont Circle",
		"userType": "Student",
		"sGPA": 3.5,
		"sGradYear": 2021,
		"sDOB": "4/26/1986",
		"totalCredits": 116,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3054
	},
	{
		"userName": "Johann Bestwerthick",
		"userEmail": "jbestwerthick1j@tripadvisor.com",
		"userPassword": "d6XnxY5X",
		"userPhone": "(410) 3049822",
		"userAddress": "57956 Melody Street",
		"userType": "Student",
		"sGPA": 3,
		"sGradYear": 2022,
		"sDOB": "6/13/1998",
		"totalCredits": 112,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3055
	},
	{
		"userName": "Corbin Dedam",
		"userEmail": "cdedam1k@jimdo.com",
		"userPassword": "mMiRHe6numgn",
		"userPhone": "(292) 2114975",
		"userAddress": "33597 Hooker Lane",
		"userType": "Student",
		"sGPA": 1.5,
		"sGradYear": 2023,
		"sDOB": "12/13/1995",
		"totalCredits": 52,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3056
	},
	{
		"userName": "Phil Andrew",
		"userEmail": "pandrew1l@webmd.com",
		"userPassword": "QLnjcm8cFgY",
		"userPhone": "(169) 9789208",
		"userAddress": "4 Debra Lane",
		"userType": "Student",
		"sGPA": 2.4,
		"sGradYear": 2024,
		"sDOB": "2/22/1991",
		"totalCredits": 56,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3057
	},
	{
		"userName": "Claudetta Gilbody",
		"userEmail": "cgilbody1m@bbb.org",
		"userPassword": "xWizCblYKf",
		"userPhone": "(498) 8327997",
		"userAddress": "7 Aberg Center",
		"userType": "Student",
		"sGPA": 2,
		"sGradYear": 2025,
		"sDOB": "9/26/1995",
		"totalCredits": 48,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3058
	},
	{
		"userName": "Hermia Rowan",
		"userEmail": "hrowan1n@imageshack.us",
		"userPassword": "PBW9Xp",
		"userPhone": "(633) 2670299",
		"userAddress": "434 Straubel Junction",
		"userType": "Student",
		"sGPA": 2.6,
		"sGradYear": 2026,
		"sDOB": "9/2/1984",
		"totalCredits": 108,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3059
	},
	{
		"userName": "Uta Knutton",
		"userEmail": "uknutton1o@artisteer.com",
		"userPassword": "ZqHqMG",
		"userPhone": "(991) 7717391",
		"userAddress": "44 Hintze Junction",
		"userType": "Student",
		"sGPA": 3.1,
		"sGradYear": 2017,
		"sDOB": "4/30/2001",
		"totalCredits": 56,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3060
	},
	{
		"userName": "Maura Cockcroft",
		"userEmail": "mcockcroft1p@dropbox.com",
		"userPassword": "m7WEFNRS",
		"userPhone": "(557) 2130241",
		"userAddress": "5207 Eagan Junction",
		"userType": "Student",
		"sGPA": 1.3,
		"sGradYear": 2018,
		"sDOB": "2/6/1999",
		"totalCredits": 100,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3061
	},
	{
		"userName": "Burton Greatbatch",
		"userEmail": "bgreatbatch1q@dagondesign.com",
		"userPassword": "D1LpXMo",
		"userPhone": "(865) 3401532",
		"userAddress": "08 Melvin Junction",
		"userType": "Student",
		"sGPA": 3.9,
		"sGradYear": 2019,
		"sDOB": "9/15/2000",
		"totalCredits": 40,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3062
	},
	{
		"userName": "Nikoletta Salterne",
		"userEmail": "nsalterne1r@loc.gov",
		"userPassword": "RbqVNR4wg40n",
		"userPhone": "(916) 9326846",
		"userAddress": "972 Lake View Junction",
		"userType": "Student",
		"sGPA": 2,
		"sGradYear": 2020,
		"sDOB": "2/14/1993",
		"totalCredits": 44,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3063
	},
	{
		"userName": "Cyrill Hartles",
		"userEmail": "chartles1s@dyndns.org",
		"userPassword": "cewCL9HhK",
		"userPhone": "(405) 4275174",
		"userAddress": "3309 Tennessee Lane",
		"userType": "Student",
		"sGPA": 1.2,
		"sGradYear": 2021,
		"sDOB": "1/19/1998",
		"totalCredits": 60,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3064
	},
	{
		"userName": "Kristin Erdis",
		"userEmail": "kerdis1t@dailymotion.com",
		"userPassword": "Gb0CnfCKnO",
		"userPhone": "(555) 8785371",
		"userAddress": "5 Pierstorff Park",
		"userType": "Student",
		"sGPA": 1.3,
		"sGradYear": 2022,
		"sDOB": "3/24/1997",
		"totalCredits": 104,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3065
	},
	{
		"userName": "Nada Lavallie",
		"userEmail": "nlavallie1u@rediff.com",
		"userPassword": "RtkZwv",
		"userPhone": "(420) 2970698",
		"userAddress": "93752 Express Place",
		"userType": "Student",
		"sGPA": 3.7,
		"sGradYear": 2023,
		"sDOB": "5/8/1994",
		"totalCredits": 76,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3066
	},
	{
		"userName": "Allianora Ruppel",
		"userEmail": "aruppel1v@163.com",
		"userPassword": "CHnHtQrsvc",
		"userPhone": "(280) 1647916",
		"userAddress": "874 Mesta Street",
		"userType": "Student",
		"sGPA": 1.2,
		"sGradYear": 2024,
		"sDOB": "2/20/1983",
		"totalCredits": 24,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3067
	},
	{
		"userName": "Freemon Buckmaster",
		"userEmail": "fbuckmaster1w@indiegogo.com",
		"userPassword": "DDomHvHhzvY",
		"userPhone": "(373) 2815436",
		"userAddress": "34 Trailsway Crossing",
		"userType": "Student",
		"sGPA": 3.2,
		"sGradYear": 2025,
		"sDOB": "9/22/1981",
		"totalCredits": 20,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3068
	},
	{
		"userName": "Sonni McCorkindale",
		"userEmail": "smccorkindale1x@blogspot.com",
		"userPassword": "W1F3o3",
		"userPhone": "(159) 9448447",
		"userAddress": "2 Carberry Center",
		"userType": "Student",
		"sGPA": 2.4,
		"sGradYear": 2026,
		"sDOB": "6/22/1981",
		"totalCredits": 4,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3069
	},
	{
		"userName": "Fallon Bonde",
		"userEmail": "fbonde1y@ocn.ne.jp",
		"userPassword": "s2eRJuU4O",
		"userPhone": "(761) 2472971",
		"userAddress": "88543 Portage Park",
		"userType": "Student",
		"sGPA": 1.1,
		"sGradYear": 2017,
		"sDOB": "8/2/1988",
		"totalCredits": 24,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3070
	},
	{
		"userName": "Lianne MacSkeagan",
		"userEmail": "lmacskeagan1z@comcast.net",
		"userPassword": "OnY45S",
		"userPhone": "(380) 8024576",
		"userAddress": "93 Alpine Hill",
		"userType": "Student",
		"sGPA": 3.1,
		"sGradYear": 2018,
		"sDOB": "4/9/1996",
		"totalCredits": 104,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3071
	},
	{
		"userName": "Roxane Brownlie",
		"userEmail": "rbrownlie20@privacy.gov.au",
		"userPassword": "RopYSW",
		"userPhone": "(467) 6915869",
		"userAddress": "4 Ridgeview Junction",
		"userType": "Student",
		"sGPA": 2.7,
		"sGradYear": 2019,
		"sDOB": "8/7/1987",
		"totalCredits": 80,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3072
	},
	{
		"userName": "Stephana Treanor",
		"userEmail": "streanor21@canalblog.com",
		"userPassword": "pQuplIYAw",
		"userPhone": "(994) 3357303",
		"userAddress": "4685 Prairieview Lane",
		"userType": "Student",
		"sGPA": 2.2,
		"sGradYear": 2020,
		"sDOB": "9/8/1983",
		"totalCredits": 76,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3073
	},
	{
		"userName": "Juana Camblin",
		"userEmail": "jcamblin22@nhs.uk",
		"userPassword": "2P01J7A4",
		"userPhone": "(931) 5271144",
		"userAddress": "1 Quincy Lane",
		"userType": "Student",
		"sGPA": 2.2,
		"sGradYear": 2021,
		"sDOB": "5/21/1993",
		"totalCredits": 64,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3074
	},
	{
		"userName": "George Landman",
		"userEmail": "glandman23@japanpost.jp",
		"userPassword": "MSHzGP3",
		"userPhone": "(775) 5807583",
		"userAddress": "94 Ronald Regan Alley",
		"userType": "Student",
		"sGPA": 3.8,
		"sGradYear": 2022,
		"sDOB": "10/22/1995",
		"totalCredits": 76,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3075
	},
	{
		"userName": "Karlyn Freeth",
		"userEmail": "kfreeth24@over-blog.com",
		"userPassword": "1bDvSf",
		"userPhone": "(732) 1062705",
		"userAddress": "6934 Bellgrove Lane",
		"userType": "Student",
		"sGPA": 2.7,
		"sGradYear": 2023,
		"sDOB": "1/18/1982",
		"totalCredits": 88,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3076
	},
	{
		"userName": "Maxie Leftridge",
		"userEmail": "mleftridge25@loc.gov",
		"userPassword": "6AD5HfTNTdyk",
		"userPhone": "(343) 7628361",
		"userAddress": "199 Canary Trail",
		"userType": "Student",
		"sGPA": 1.3,
		"sGradYear": 2024,
		"sDOB": "10/9/1992",
		"totalCredits": 80,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3077
	},
	{
		"userName": "Renaud Rayman",
		"userEmail": "rrayman26@cnbc.com",
		"userPassword": "WBRstKAOdXZ",
		"userPhone": "(659) 4995878",
		"userAddress": "663 Summerview Park",
		"userType": "Student",
		"sGPA": 2.8,
		"sGradYear": 2025,
		"sDOB": "10/12/2002",
		"totalCredits": 48,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3078
	},
	{
		"userName": "Chen Venus",
		"userEmail": "cvenus27@bizjournals.com",
		"userPassword": "DHlxsv6ZN",
		"userPhone": "(568) 9845414",
		"userAddress": "38269 Evergreen Road",
		"userType": "Student",
		"sGPA": 2,
		"sGradYear": 2026,
		"sDOB": "5/1/2003",
		"totalCredits": 120,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3079
	},
	{
		"userName": "Claribel Baumann",
		"userEmail": "cbaumann28@github.io",
		"userPassword": "H3EBP7HH9Y",
		"userPhone": "(944) 2367848",
		"userAddress": "9084 Gina Hill",
		"userType": "Student",
		"sGPA": 2.6,
		"sGradYear": 2017,
		"sDOB": "11/11/1988",
		"totalCredits": 16,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3080
	},
	{
		"userName": "Gerti Gheorghescu",
		"userEmail": "ggheorghescu29@ucsd.edu",
		"userPassword": "7Bf9sErG0Mhg",
		"userPhone": "(816) 9972510",
		"userAddress": "4344 Delladonna Circle",
		"userType": "Student",
		"sGPA": 2.1,
		"sGradYear": 2018,
		"sDOB": "2/10/1995",
		"totalCredits": 64,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3081
	},
	{
		"userName": "Germain Balcock",
		"userEmail": "gbalcock2a@gizmodo.com",
		"userPassword": "QPWTOAN",
		"userPhone": "(910) 6651758",
		"userAddress": "41794 Independence Trail",
		"userType": "Student",
		"sGPA": 1.7,
		"sGradYear": 2019,
		"sDOB": "2/18/1985",
		"totalCredits": 100,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3082
	},
	{
		"userName": "Harvey O'Gormley",
		"userEmail": "hogormley2b@disqus.com",
		"userPassword": "nN5WE7Ov",
		"userPhone": "(290) 6726889",
		"userAddress": "9495 Petterle Hill",
		"userType": "Student",
		"sGPA": 2.5,
		"sGradYear": 2020,
		"sDOB": "8/11/1990",
		"totalCredits": 64,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3083
	},
	{
		"userName": "Torin Bostick",
		"userEmail": "tbostick2c@foxnews.com",
		"userPassword": "1tbISPK7yXT",
		"userPhone": "(368) 1403965",
		"userAddress": "797 Surrey Drive",
		"userType": "Student",
		"sGPA": 1.3,
		"sGradYear": 2021,
		"sDOB": "3/17/2001",
		"totalCredits": 116,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3084
	},
	{
		"userName": "Marena Baskerville",
		"userEmail": "mbaskerville2d@cnbc.com",
		"userPassword": "ol3yhiia",
		"userPhone": "(433) 8494892",
		"userAddress": "030 Farragut Circle",
		"userType": "Student",
		"sGPA": 1.8,
		"sGradYear": 2022,
		"sDOB": "5/7/1980",
		"totalCredits": 12,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3085
	},
	{
		"userName": "Marty Fozard",
		"userEmail": "mfozard2e@slideshare.net",
		"userPassword": "W8d0yj",
		"userPhone": "(724) 1425398",
		"userAddress": "493 Becker Drive",
		"userType": "Student",
		"sGPA": 2.7,
		"sGradYear": 2023,
		"sDOB": "10/18/1990",
		"totalCredits": 12,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3086
	},
	{
		"userName": "Karyl Valero",
		"userEmail": "kvalero2f@is.gd",
		"userPassword": "5xktcWkb0Ln6",
		"userPhone": "(738) 7985597",
		"userAddress": "3888 5th Terrace",
		"userType": "Student",
		"sGPA": 1.6,
		"sGradYear": 2024,
		"sDOB": "10/19/1987",
		"totalCredits": 104,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3087
	},
	{
		"userName": "Marion Kloss",
		"userEmail": "mkloss2g@unblog.fr",
		"userPassword": "NmxBiaGov",
		"userPhone": "(917) 2185761",
		"userAddress": "81926 Green Ridge Point",
		"userType": "Student",
		"sGPA": 2.3,
		"sGradYear": 2025,
		"sDOB": "3/30/1990",
		"totalCredits": 56,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3088
	},
	{
		"userName": "Shannan Greenley",
		"userEmail": "sgreenley2h@live.com",
		"userPassword": "XVkyDnL",
		"userPhone": "(504) 5964366",
		"userAddress": "126 Grayhawk Court",
		"userType": "Student",
		"sGPA": 1.7,
		"sGradYear": 2026,
		"sDOB": "5/26/1981",
		"totalCredits": 120,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3089
	},
	{
		"userName": "Kenton McNish",
		"userEmail": "kmcnish2i@economist.com",
		"userPassword": "vfvShbirRgSj",
		"userPhone": "(174) 2639206",
		"userAddress": "6333 Hanson Circle",
		"userType": "Student",
		"sGPA": 3.9,
		"sGradYear": 2017,
		"sDOB": "6/22/2000",
		"totalCredits": 100,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3090
	},
	{
		"userName": "Christoph Hughson",
		"userEmail": "chughson2j@behance.net",
		"userPassword": "8UEYYlxPrxsg",
		"userPhone": "(332) 9236324",
		"userAddress": "428 Stoughton Lane",
		"userType": "Student",
		"sGPA": 2.3,
		"sGradYear": 2018,
		"sDOB": "10/8/2000",
		"totalCredits": 40,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3091
	},
	{
		"userName": "Yehudit Stein",
		"userEmail": "ystein2k@cmu.edu",
		"userPassword": "RkCTd5igN",
		"userPhone": "(562) 7709120",
		"userAddress": "0535 Forest Run Pass",
		"userType": "Student",
		"sGPA": 1.3,
		"sGradYear": 2019,
		"sDOB": "10/21/1987",
		"totalCredits": 104,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3092
	},
	{
		"userName": "Werner Frankom",
		"userEmail": "wfrankom2l@miibeian.gov.cn",
		"userPassword": "dOpIn9Quo",
		"userPhone": "(279) 4153216",
		"userAddress": "8 Buena Vista Drive",
		"userType": "Student",
		"sGPA": 2.1,
		"sGradYear": 2020,
		"sDOB": "2/4/2001",
		"totalCredits": 24,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3093
	},
	{
		"userName": "Cletus Linggard",
		"userEmail": "clinggard2m@globo.com",
		"userPassword": "Fctnb74ayMm",
		"userPhone": "(859) 5173561",
		"userAddress": "2890 Montana Way",
		"userType": "Student",
		"sGPA": 2.4,
		"sGradYear": 2021,
		"sDOB": "4/12/1998",
		"totalCredits": 4,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3094
	},
	{
		"userName": "Ulrich Gretton",
		"userEmail": "ugretton2n@intel.com",
		"userPassword": "wzP8hP0tvpIZ",
		"userPhone": "(613) 2574132",
		"userAddress": "7 Hauk Alley",
		"userType": "Student",
		"sGPA": 3.2,
		"sGradYear": 2022,
		"sDOB": "11/26/2002",
		"totalCredits": 44,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3095
	},
	{
		"userName": "Farica Michele",
		"userEmail": "fmichele2o@quantcast.com",
		"userPassword": "SAEhhVX",
		"userPhone": "(421) 5857210",
		"userAddress": "59669 Arapahoe Park",
		"userType": "Student",
		"sGPA": 3.6,
		"sGradYear": 2023,
		"sDOB": "6/20/1990",
		"totalCredits": 96,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3096
	},
	{
		"userName": "Cordy Radborn",
		"userEmail": "cradborn2p@ustream.tv",
		"userPassword": "bUmvXV",
		"userPhone": "(894) 5900445",
		"userAddress": "96205 Jenna Park",
		"userType": "Student",
		"sGPA": 1.6,
		"sGradYear": 2024,
		"sDOB": "9/3/1988",
		"totalCredits": 80,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3097
	},
	{
		"userName": "Kaila Parysiak",
		"userEmail": "kparysiak2q@free.fr",
		"userPassword": "8jFv5RKv",
		"userPhone": "(516) 3072687",
		"userAddress": "33798 Thackeray Way",
		"userType": "Student",
		"sGPA": 2.4,
		"sGradYear": 2025,
		"sDOB": "1/15/2001",
		"totalCredits": 84,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3098
	},
	{
		"userName": "Nye Spadazzi",
		"userEmail": "nspadazzi2r@harvard.edu",
		"userPassword": "3EReOOtw",
		"userPhone": "(663) 6470476",
		"userAddress": "4799 Express Trail",
		"userType": "Student",
		"sGPA": 3.4,
		"sGradYear": 2026,
		"sDOB": "3/1/1984",
		"totalCredits": 40,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3099
	},
	{
		"userName": "Katina Serris",
		"userEmail": "kserris2s@ft.com",
		"userPassword": "8BRmFij6",
		"userPhone": "(455) 4378928",
		"userAddress": "8667 Rigney Place",
		"userType": "Student",
		"sGPA": 2.8,
		"sGradYear": 2017,
		"sDOB": "4/16/1998",
		"totalCredits": 32,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3100
	},
	{
		"userName": "Feodor Gaynes",
		"userEmail": "fgaynes2t@gizmodo.com",
		"userPassword": "QuGYOlNAnC38",
		"userPhone": "(578) 2876499",
		"userAddress": "474 Butternut Center",
		"userType": "Student",
		"sGPA": 3.5,
		"sGradYear": 2018,
		"sDOB": "9/13/2001",
		"totalCredits": 24,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3101
	},
	{
		"userName": "Caitlin Rowland",
		"userEmail": "crowland2u@amazon.co.uk",
		"userPassword": "jUuqzK",
		"userPhone": "(750) 6816131",
		"userAddress": "03 Sachs Hill",
		"userType": "Student",
		"sGPA": 1,
		"sGradYear": 2019,
		"sDOB": "6/12/1994",
		"totalCredits": 20,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3102
	},
	{
		"userName": "Cyrille Astbery",
		"userEmail": "castbery2v@rediff.com",
		"userPassword": "ZhUddUpRDqb",
		"userPhone": "(454) 7269358",
		"userAddress": "737 Ohio Trail",
		"userType": "Student",
		"sGPA": 3.7,
		"sGradYear": 2020,
		"sDOB": "10/26/1993",
		"totalCredits": 36,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3103
	},
	{
		"userName": "Quintin Lamburn",
		"userEmail": "qlamburn2w@cocolog-nifty.com",
		"userPassword": "APTLrVLXN1E",
		"userPhone": "(696) 4165841",
		"userAddress": "22 Cordelia Place",
		"userType": "Student",
		"sGPA": 1.3,
		"sGradYear": 2021,
		"sDOB": "5/22/2002",
		"totalCredits": 28,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3104
	},
	{
		"userName": "Zia Scholling",
		"userEmail": "zscholling2x@merriam-webster.com",
		"userPassword": "Ncuo4jqbu8se",
		"userPhone": "(221) 8670151",
		"userAddress": "0216 Mcbride Place",
		"userType": "Student",
		"sGPA": 2.5,
		"sGradYear": 2022,
		"sDOB": "10/23/1982",
		"totalCredits": 28,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3105
	},
	{
		"userName": "Kali Howsley",
		"userEmail": "khowsley2y@ucoz.com",
		"userPassword": "IV5FvboVUQ",
		"userPhone": "(257) 9734667",
		"userAddress": "7083 Moland Crossing",
		"userType": "Student",
		"sGPA": 2.7,
		"sGradYear": 2023,
		"sDOB": "10/10/2003",
		"totalCredits": 108,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3106
	},
	{
		"userName": "Wenona Whannel",
		"userEmail": "wwhannel2z@wikipedia.org",
		"userPassword": "72pVC9t9",
		"userPhone": "(487) 2577598",
		"userAddress": "0604 Straubel Hill",
		"userType": "Student",
		"sGPA": 2.2,
		"sGradYear": 2024,
		"sDOB": "1/12/1990",
		"totalCredits": 44,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3107
	},
	{
		"userName": "Bridgette Iannello",
		"userEmail": "biannello30@list-manage.com",
		"userPassword": "Y8RRnvi7uf",
		"userPhone": "(734) 4625635",
		"userAddress": "27846 Hauk Street",
		"userType": "Student",
		"sGPA": 1.6,
		"sGradYear": 2025,
		"sDOB": "4/27/1988",
		"totalCredits": 24,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3108
	},
	{
		"userName": "Shirl Woolgar",
		"userEmail": "swoolgar31@friendfeed.com",
		"userPassword": "qtC9GBOw",
		"userPhone": "(258) 5163870",
		"userAddress": "7 Old Shore Plaza",
		"userType": "Student",
		"sGPA": 2.6,
		"sGradYear": 2026,
		"sDOB": "3/5/1989",
		"totalCredits": 68,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3109
	},
	{
		"userName": "Alyosha Bourner",
		"userEmail": "abourner32@canalblog.com",
		"userPassword": "jMD0yAjnf",
		"userPhone": "(127) 1840605",
		"userAddress": "283 Linden Avenue",
		"userType": "Student",
		"sGPA": 3.8,
		"sGradYear": 2017,
		"sDOB": "11/3/1990",
		"totalCredits": 112,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3110
	},
	{
		"userName": "Kristen Stiller",
		"userEmail": "kstiller33@soup.io",
		"userPassword": "y15tsCH",
		"userPhone": "(443) 4534130",
		"userAddress": "8 Cambridge Plaza",
		"userType": "Student",
		"sGPA": 3.9,
		"sGradYear": 2018,
		"sDOB": "8/31/1996",
		"totalCredits": 52,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3111
	},
	{
		"userName": "Red Speerman",
		"userEmail": "rspeerman34@cdc.gov",
		"userPassword": "4SYqzuLvk5",
		"userPhone": "(196) 3973660",
		"userAddress": "3410 Laurel Parkway",
		"userType": "Student",
		"sGPA": 2.2,
		"sGradYear": 2019,
		"sDOB": "7/13/1985",
		"totalCredits": 108,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3112
	},
	{
		"userName": "Lillian Pennycook",
		"userEmail": "lpennycook35@dropbox.com",
		"userPassword": "Hka8c4J2",
		"userPhone": "(892) 8132047",
		"userAddress": "9588 Bultman Drive",
		"userType": "Student",
		"sGPA": 1.6,
		"sGradYear": 2020,
		"sDOB": "11/12/1998",
		"totalCredits": 4,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3113
	},
	{
		"userName": "Peta Menelaws",
		"userEmail": "pmenelaws36@alibaba.com",
		"userPassword": "xiQsyRXpWT",
		"userPhone": "(927) 4310938",
		"userAddress": "0172 Beilfuss Place",
		"userType": "Student",
		"sGPA": 1.5,
		"sGradYear": 2021,
		"sDOB": "11/29/1989",
		"totalCredits": 68,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3114
	},
	{
		"userName": "Ansell Plewes",
		"userEmail": "aplewes37@wix.com",
		"userPassword": "e0BqlTLgP",
		"userPhone": "(673) 9657983",
		"userAddress": "19642 Cherokee Place",
		"userType": "Student",
		"sGPA": 1.5,
		"sGradYear": 2022,
		"sDOB": "6/27/1997",
		"totalCredits": 76,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3115
	},
	{
		"userName": "Jaquenetta Bendel",
		"userEmail": "jbendel38@cbc.ca",
		"userPassword": "8A9qjnMd",
		"userPhone": "(865) 2535001",
		"userAddress": "163 Eliot Place",
		"userType": "Student",
		"sGPA": 1.4,
		"sGradYear": 2023,
		"sDOB": "6/6/1990",
		"totalCredits": 16,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3116
	},
	{
		"userName": "Reggie Gurery",
		"userEmail": "rgurery39@sfgate.com",
		"userPassword": "iIBdB33x",
		"userPhone": "(112) 5950504",
		"userAddress": "06 Linden Pass",
		"userType": "Student",
		"sGPA": 1.2,
		"sGradYear": 2024,
		"sDOB": "7/5/1981",
		"totalCredits": 60,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3117
	},
	{
		"userName": "Ely Tomczykowski",
		"userEmail": "etomczykowski3a@naver.com",
		"userPassword": "bRmkB8LlKe",
		"userPhone": "(798) 3349668",
		"userAddress": "4 Tennessee Terrace",
		"userType": "Student",
		"sGPA": 3.6,
		"sGradYear": 2025,
		"sDOB": "5/14/1997",
		"totalCredits": 64,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3118
	},
	{
		"userName": "Kipp Hannond",
		"userEmail": "khannond3b@bbc.co.uk",
		"userPassword": "Yus6H4pjW",
		"userPhone": "(885) 9647601",
		"userAddress": "0 Mariners Cove Way",
		"userType": "Student",
		"sGPA": 3.4,
		"sGradYear": 2026,
		"sDOB": "8/9/1982",
		"totalCredits": 52,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3119
	},
	{
		"userName": "Fanchette Simounet",
		"userEmail": "fsimounet3c@walmart.com",
		"userPassword": "Tw7aYGZTu",
		"userPhone": "(709) 4256485",
		"userAddress": "92413 Annamark Terrace",
		"userType": "Student",
		"sGPA": 1.4,
		"sGradYear": 2017,
		"sDOB": "8/9/2000",
		"totalCredits": 52,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3120
	},
	{
		"userName": "Lucho Hould",
		"userEmail": "lhould3d@smh.com.au",
		"userPassword": "pDpCxe",
		"userPhone": "(116) 8802548",
		"userAddress": "00 Crest Line Way",
		"userType": "Student",
		"sGPA": 1.9,
		"sGradYear": 2018,
		"sDOB": "6/17/1986",
		"totalCredits": 48,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3121
	},
	{
		"userName": "Tobin Janew",
		"userEmail": "tjanew3e@nps.gov",
		"userPassword": "F6mxMiJOuy",
		"userPhone": "(473) 7202904",
		"userAddress": "7 Lien Trail",
		"userType": "Student",
		"sGPA": 3.4,
		"sGradYear": 2019,
		"sDOB": "12/22/1997",
		"totalCredits": 88,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3122
	},
	{
		"userName": "Cherilynn Moralee",
		"userEmail": "cmoralee3f@homestead.com",
		"userPassword": "uulqTjB3",
		"userPhone": "(317) 6834281",
		"userAddress": "9 Thompson Junction",
		"userType": "Student",
		"sGPA": 2.5,
		"sGradYear": 2020,
		"sDOB": "6/12/1989",
		"totalCredits": 52,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3123
	},
	{
		"userName": "Fayth Hallgarth",
		"userEmail": "fhallgarth3g@nsw.gov.au",
		"userPassword": "lWfryqxEEY",
		"userPhone": "(659) 3516633",
		"userAddress": "14 International Hill",
		"userType": "Student",
		"sGPA": 1.9,
		"sGradYear": 2021,
		"sDOB": "10/17/2001",
		"totalCredits": 28,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3124
	},
	{
		"userName": "Dana Tocknell",
		"userEmail": "dtocknell3h@phpbb.com",
		"userPassword": "asOnThM90D0L",
		"userPhone": "(160) 5400109",
		"userAddress": "165 Arapahoe Drive",
		"userType": "Student",
		"sGPA": 2.1,
		"sGradYear": 2022,
		"sDOB": "7/2/1986",
		"totalCredits": 4,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3125
	},
	{
		"userName": "Letti Held",
		"userEmail": "lheld3i@cyberchimps.com",
		"userPassword": "eP4KlNXxr",
		"userPhone": "(808) 5830836",
		"userAddress": "42 Gulseth Alley",
		"userType": "Student",
		"sGPA": 1.8,
		"sGradYear": 2023,
		"sDOB": "5/15/1985",
		"totalCredits": 80,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3126
	},
	{
		"userName": "Gayelord Servis",
		"userEmail": "gservis3j@forbes.com",
		"userPassword": "zQKreoaY9A",
		"userPhone": "(816) 3289578",
		"userAddress": "24735 Harper Trail",
		"userType": "Student",
		"sGPA": 3.9,
		"sGradYear": 2024,
		"sDOB": "10/1/1994",
		"totalCredits": 92,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3127
	},
	{
		"userName": "Wang Poff",
		"userEmail": "wpoff3k@hhs.gov",
		"userPassword": "bT5ERh48G",
		"userPhone": "(378) 7718578",
		"userAddress": "1 Lakewood Gardens Hill",
		"userType": "Student",
		"sGPA": 3.5,
		"sGradYear": 2025,
		"sDOB": "10/6/1999",
		"totalCredits": 32,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3128
	},
	{
		"userName": "Hart MacNucator",
		"userEmail": "hmacnucator3l@photobucket.com",
		"userPassword": "5UDRpB",
		"userPhone": "(450) 6332169",
		"userAddress": "4133 Meadow Vale Trail",
		"userType": "Student",
		"sGPA": 1.7,
		"sGradYear": 2026,
		"sDOB": "5/31/1981",
		"totalCredits": 92,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3129
	},
	{
		"userName": "Eduino Valti",
		"userEmail": "evalti3m@prlog.org",
		"userPassword": "i3y7aZEZw",
		"userPhone": "(127) 7771151",
		"userAddress": "1 Ramsey Plaza",
		"userType": "Student",
		"sGPA": 3,
		"sGradYear": 2017,
		"sDOB": "12/16/1983",
		"totalCredits": 68,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3130
	},
	{
		"userName": "Donetta Fieller",
		"userEmail": "dfieller3n@lulu.com",
		"userPassword": "JDKAeltQsm",
		"userPhone": "(262) 6154939",
		"userAddress": "7050 Ridgeview Place",
		"userType": "Student",
		"sGPA": 1.2,
		"sGradYear": 2018,
		"sDOB": "7/23/1987",
		"totalCredits": 80,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3131
	},
	{
		"userName": "Gregor Leighfield",
		"userEmail": "gleighfield3o@youku.com",
		"userPassword": "vNiAegR",
		"userPhone": "(511) 6782775",
		"userAddress": "217 Carioca Street",
		"userType": "Student",
		"sGPA": 3.9,
		"sGradYear": 2019,
		"sDOB": "5/27/1987",
		"totalCredits": 72,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3132
	},
	{
		"userName": "Lil Lejeune",
		"userEmail": "llejeune3p@wix.com",
		"userPassword": "C5xmLFu",
		"userPhone": "(967) 7818456",
		"userAddress": "3 Pepper Wood Center",
		"userType": "Student",
		"sGPA": 2,
		"sGradYear": 2020,
		"sDOB": "11/9/1989",
		"totalCredits": 20,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3133
	},
	{
		"userName": "Shelli Isakovic",
		"userEmail": "sisakovic3q@histats.com",
		"userPassword": "brUB3Jga8o",
		"userPhone": "(192) 5957675",
		"userAddress": "29 Division Street",
		"userType": "Student",
		"sGPA": 2.5,
		"sGradYear": 2021,
		"sDOB": "6/13/1992",
		"totalCredits": 80,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3134
	},
	{
		"userName": "Haleigh Wrotham",
		"userEmail": "hwrotham3r@ft.com",
		"userPassword": "WzJtkZXOQ",
		"userPhone": "(111) 2867332",
		"userAddress": "52170 Lien Lane",
		"userType": "Student",
		"sGPA": 3.3,
		"sGradYear": 2022,
		"sDOB": "2/5/1984",
		"totalCredits": 8,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3135
	},
	{
		"userName": "Marve Di Nisco",
		"userEmail": "mdi3s@etsy.com",
		"userPassword": "8VojfP8fB",
		"userPhone": "(219) 8893846",
		"userAddress": "8963 Bonner Point",
		"userType": "Student",
		"sGPA": 1.5,
		"sGradYear": 2023,
		"sDOB": "12/7/1985",
		"totalCredits": 120,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3136
	},
	{
		"userName": "Clareta De Lascy",
		"userEmail": "cde3t@xing.com",
		"userPassword": "atUlBTU",
		"userPhone": "(737) 6363518",
		"userAddress": "0565 Morning Park",
		"userType": "Student",
		"sGPA": 2.5,
		"sGradYear": 2024,
		"sDOB": "7/24/1983",
		"totalCredits": 28,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3137
	},
	{
		"userName": "Hestia Kleszinski",
		"userEmail": "hkleszinski3u@reuters.com",
		"userPassword": "Om0w5fM",
		"userPhone": "(774) 1969385",
		"userAddress": "1434 Sheridan Lane",
		"userType": "Student",
		"sGPA": 2,
		"sGradYear": 2025,
		"sDOB": "10/19/2000",
		"totalCredits": 120,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3138
	},
	{
		"userName": "Cherish Flaherty",
		"userEmail": "cflaherty3v@pen.io",
		"userPassword": "kydoNf",
		"userPhone": "(667) 5086094",
		"userAddress": "9 Chive Trail",
		"userType": "Student",
		"sGPA": 2.4,
		"sGradYear": 2026,
		"sDOB": "3/1/1988",
		"totalCredits": 24,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3139
	},
	{
		"userName": "Jania Penney",
		"userEmail": "jpenney3w@google.co.uk",
		"userPassword": "hFccVSkOIx",
		"userPhone": "(208) 7659277",
		"userAddress": "7597 Service Avenue",
		"userType": "Student",
		"sGPA": 3.5,
		"sGradYear": 2017,
		"sDOB": "10/13/1980",
		"totalCredits": 28,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3140
	},
	{
		"userName": "Hubie Le Brum",
		"userEmail": "hle3x@ucsd.edu",
		"userPassword": "1Bz1ss8DDY",
		"userPhone": "(389) 2882606",
		"userAddress": "6 Meadow Vale Hill",
		"userType": "Student",
		"sGPA": 2.1,
		"sGradYear": 2018,
		"sDOB": "2/10/1989",
		"totalCredits": 44,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 4,
		"userID": 3141
	},
	{
		"userName": "Rudiger Tison",
		"userEmail": "rtison3y@pbs.org",
		"userPassword": "xa5Gow",
		"userPhone": "(763) 4926803",
		"userAddress": "8716 Riverside Place",
		"userType": "Student",
		"sGPA": 2.9,
		"sGradYear": 2019,
		"sDOB": "10/25/1983",
		"totalCredits": 104,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3142
	},
	{
		"userName": "Esmeralda Bastiman",
		"userEmail": "ebastiman3z@surveymonkey.com",
		"userPassword": "ndMWVea",
		"userPhone": "(715) 6534804",
		"userAddress": "752 Logan Alley",
		"userType": "Student",
		"sGPA": 2.1,
		"sGradYear": 2020,
		"sDOB": "3/24/1993",
		"totalCredits": 100,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3143
	},
	{
		"userName": "Kassi Tackell",
		"userEmail": "ktackell40@feedburner.com",
		"userPassword": "7YNY0WnbZn8",
		"userPhone": "(567) 6508690",
		"userAddress": "7627 Mallard Road",
		"userType": "Student",
		"sGPA": 3.6,
		"sGradYear": 2021,
		"sDOB": "4/14/1994",
		"totalCredits": 104,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3144
	},
	{
		"userName": "Kelila Monnery",
		"userEmail": "kmonnery41@mozilla.com",
		"userPassword": "kuM9lLD",
		"userPhone": "(320) 1930319",
		"userAddress": "6741 Forest Dale Center",
		"userType": "Student",
		"sGPA": 3.7,
		"sGradYear": 2022,
		"sDOB": "9/20/1989",
		"totalCredits": 52,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3145
	},
	{
		"userName": "Beale Brane",
		"userEmail": "bbrane42@virginia.edu",
		"userPassword": "zesFXGuDGEcd",
		"userPhone": "(995) 7636382",
		"userAddress": "87673 Portage Crossing",
		"userType": "Student",
		"sGPA": 3.3,
		"sGradYear": 2023,
		"sDOB": "3/13/1996",
		"totalCredits": 24,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3146
	},
	{
		"userName": "Courtnay McLennan",
		"userEmail": "cmclennan43@phoca.cz",
		"userPassword": "sfPMhQ",
		"userPhone": "(269) 1733816",
		"userAddress": "8523 Vermont Avenue",
		"userType": "Student",
		"sGPA": 2.8,
		"sGradYear": 2024,
		"sDOB": "6/16/1995",
		"totalCredits": 92,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3147
	},
	{
		"userName": "Hillie Clougher",
		"userEmail": "hclougher44@army.mil",
		"userPassword": "zbHXZz",
		"userPhone": "(175) 5809101",
		"userAddress": "8 Butternut Road",
		"userType": "Student",
		"sGPA": 2.9,
		"sGradYear": 2025,
		"sDOB": "10/14/2003",
		"totalCredits": 92,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": true,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3148
	},
	{
		"userName": "Wilbur Dory",
		"userEmail": "wdory45@webmd.com",
		"userPassword": "819YEo8aU",
		"userPhone": "(824) 8404617",
		"userAddress": "19172 Talmadge Road",
		"userType": "Student",
		"sGPA": 2.6,
		"sGradYear": 2026,
		"sDOB": "1/6/1998",
		"totalCredits": 68,
		"studentType": "undergraduate",
		"isFullTime": false,
		"tutionCost": "$2,000",
		"hasMealPlan": false,
		"maxCreditsAllowed": 11,
		"minCreditsAllowed": 4,
		"currentCredits": 11,
		"userID": 3149
	}
];
export default undergraduatePartTime;
