const department = [
	{
		deptID: 1,
		deptName: 'American Studies/Media & Communications',
		deptEmail: 'americanstudies@guptauniversity.edu',
		deptHeadIDNum: 6000,
		deptPhone: '(957) 4609480',
		deptManager: 'Evelina Beauchamp',
		roomIDNum: 1,
	},
	{
		deptID: 2,
		deptName: 'Biological Sciences',
		deptEmail: 'bioscience@guptauniversity.edu',
		deptHeadIDNum: 6001,
		deptPhone: '(589) 3785889',
		deptManager: 'Perceval Tremouille',
		roomIDNum: 2,
	},
	{
		deptID: 3,
		deptName: 'Chemistry and Physics',
		deptEmail: 'chemphysics@guptauniversity.edu',
		deptHeadIDNum: 6002,
		deptPhone: '(782) 5113580',
		deptManager: 'Bradford Peattie',
		roomIDNum: 3,
	},
	{
		deptID: 4,
		deptName: 'English',
		deptEmail: 'english@guptauniversity.edu',
		deptHeadIDNum: 6003,
		deptPhone: '(445) 5305094',
		deptManager: 'Kristi Jaszczak',
		roomIDNum: 4,
	},
	{
		deptID: 5,
		deptName: 'History & Philosophy',
		deptEmail: 'history@guptauniversity.edu',
		deptHeadIDNum: 6004,
		deptPhone: '(715) 1865478',
		deptManager: 'Clotilda Cluney',
		roomIDNum: 5,
	},
	{
		deptID: 6,
		deptName: 'Mathematics, Computer & Information Science',
		deptEmail: 'mathematics@guptauniversity.edu',
		deptHeadIDNum: 6005,
		deptPhone: '(784) 7678002',
		deptManager: 'Somerset Whimpenny',
		roomIDNum: 6,
	},
	{
		deptID: 7,
		deptName: 'Modern Languages',
		deptEmail: 'languages@guptauniversity.edu',
		deptHeadIDNum: 6006,
		deptPhone: '(216) 6358155',
		deptManager: 'Filmer Smart',
		roomIDNum: 7,
	},
	{
		deptID: 8,
		deptName: 'Politics, Economics & Law',
		deptEmail: 'politics@guptauniversity.edu',
		deptHeadIDNum: 6007,
		deptPhone: '(841) 8858723',
		deptManager: 'Freemon Rippen',
		roomIDNum: 8,
	},
	{
		deptID: 9,
		deptName: 'Psychology',
		deptEmail: 'psychology@guptauniversity.edu',
		deptHeadIDNum: 6008,
		deptPhone: '(918) 5497068',
		deptManager: 'Ced Mardle',
		roomIDNum: 9,
	},
	{
		deptID: 10,
		deptName: 'Public Health',
		deptEmail: 'healthdept@guptauniversity.edu',
		deptHeadIDNum: 6009,
		deptPhone: '(430) 2856981',
		deptManager: 'Pearce Gregson',
		roomIDNum: 10,
	},
	{
		deptID: 11,
		deptName: 'Sociology',
		deptEmail: 'sociologydept@guptauniversity.edu',
		deptHeadIDNum: 6010,
		deptPhone: '(966) 1496388',
		deptManager: 'Dougie Craigmyle',
		roomIDNum: 11,
	},
	{
		deptID: 12,
		deptName: 'Visual Arts',
		deptEmail: 'artsdept@guptauniversity.edu',
		deptHeadIDNum: 6011,
		deptPhone: '(672) 6447185',
		deptManager: 'Arabella Pursehouse',
		roomIDNum: 12,
	},
	{
		deptID: 13,
		deptName: 'Adolescence Education',
		deptEmail: 'educationdept@guptauniversity.edu',
		deptHeadIDNum: 6012,
		deptPhone: '(562) 3001057',
		deptManager: 'Raoul Tudge',
		roomIDNum: 13,
	},
	{
		deptID: 14,
		deptName: 'Accounting, Taxation & Business Law',
		deptEmail: 'businessdept@guptauniversity.edu',
		deptHeadIDNum: 6013,
		deptPhone: '(553) 7886132',
		deptManager: 'Doralia Aslum',
		roomIDNum: 14,
	},
	{
		deptID: 15,
		deptName: 'Management, Marketing & Finance',
		deptEmail: 'managementdept@guptauniversity.edu',
		deptHeadIDNum: 6014,
		deptPhone: '(566) 3960750',
		deptManager: 'Pyotr Hegarty',
		roomIDNum: 15,
	},
];
export default department;
