const researcher = [
	{
		"userName": "Law Hagart",
		"userEmail": "LHagart@GuptaUni.edu",
		"userPassword": "TxHtu4",
		"userPhone": "(528) 2497575",
		"userAddress": "75 Mcguire Place",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 190,
		"userID": 9500
	},
	{
		"userName": "Pollyanna Conrard",
		"userEmail": "PConrard@GuptaUni.edu",
		"userPassword": "nVwNbtqVTq58",
		"userPhone": "(979) 7364450",
		"userAddress": "7487 Spaight Point",
		"userType": "Researcher",
		"researchSalary": "$75,000 ",
		"researchOfficeNum": 190,
		"userID": 9501
	},
	{
		"userName": "Thornie Leuren",
		"userEmail": "TLeuren@GuptaUni.edu",
		"userPassword": "7z3IzHjGw",
		"userPhone": "(402) 5091845",
		"userAddress": "95274 Fieldstone Parkway",
		"userType": "Researcher",
		"researchSalary": "$75,000 ",
		"researchOfficeNum": 191,
		"userID": 9502
	},
	{
		"userName": "Chaim Vincent",
		"userEmail": "CVincent@GuptaUni.edu",
		"userPassword": "arzNAU4Jlai",
		"userPhone": "(196) 9980810",
		"userAddress": "40167 Mariners Cove Junction",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 191,
		"userID": 9503
	},
	{
		"userName": "Kari Quarless",
		"userEmail": "KQuarles@GuptaUni.edu",
		"userPassword": "QLnpmoxtxN",
		"userPhone": "(815) 5441431",
		"userAddress": "8 Northfield Plaza",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 192,
		"userID": 9504
	},
	{
		"userName": "Warren Bruin",
		"userEmail": "WBruin@GuptaUni.edu",
		"userPassword": "RwZhJ5",
		"userPhone": "(756) 9309824",
		"userAddress": "9 Scofield Way",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 192,
		"userID": 9505
	},
	{
		"userName": "Zebedee Gouny",
		"userEmail": "ZGouny@GuptaUni.edu",
		"userPassword": "tgoY5x",
		"userPhone": "(581) 2910043",
		"userAddress": "7015 Beilfuss Alley",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 193,
		"userID": 9506
	},
	{
		"userName": "Shamus Cushe",
		"userEmail": "SCushe@GuptaUni.edu",
		"userPassword": "rMONuy2XARf",
		"userPhone": "(466) 7452209",
		"userAddress": "8 Spohn Place",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 193,
		"userID": 9507
	},
	{
		"userName": "Gearalt Donald",
		"userEmail": "GDonald@GuptaUni.edu",
		"userPassword": "kFkAV1ViPQ7i",
		"userPhone": "(190) 8594361",
		"userAddress": "01384 Monica Alley",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 194,
		"userID": 9508
	},
	{
		"userName": "Rafferty Bayless",
		"userEmail": "RBayless@GuptaUni.edu",
		"userPassword": "Y2ssJgdp",
		"userPhone": "(313) 7966342",
		"userAddress": "4972 Fairview Hill",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 194,
		"userID": 9509
	},
	{
		"userName": "Christiane Lomansey",
		"userEmail": "CLomanse@GuptaUni.edu",
		"userPassword": "AGoqEMKCZF",
		"userPhone": "(925) 7367362",
		"userAddress": "311 Memorial Point",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 195,
		"userID": 9510
	},
	{
		"userName": "Karia Garfitt",
		"userEmail": "KGarfitt@GuptaUni.edu",
		"userPassword": "VEmO8K",
		"userPhone": "(140) 7223990",
		"userAddress": "986 Ronald Regan Circle",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 195,
		"userID": 9511
	},
	{
		"userName": "Candis Gammill",
		"userEmail": "CGammill@GuptaUni.edu",
		"userPassword": "Assl9iIXfT",
		"userPhone": "(168) 5902494",
		"userAddress": "63450 Talmadge Park",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 196,
		"userID": 9512
	},
	{
		"userName": "Ingrid Labbey",
		"userEmail": "ILabbey@GuptaUni.edu",
		"userPassword": "jJbiKy",
		"userPhone": "(104) 9776308",
		"userAddress": "60332 Summerview Way",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 196,
		"userID": 9513
	},
	{
		"userName": "Cyb Becken",
		"userEmail": "CBecken@GuptaUni.edu",
		"userPassword": "1ZzIh5",
		"userPhone": "(821) 2287291",
		"userAddress": "41929 Ryan Circle",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 197,
		"userID": 9514
	},
	{
		"userName": "Carry Tersay",
		"userEmail": "CTersay@GuptaUni.edu",
		"userPassword": "Z7DmVI",
		"userPhone": "(886) 9531073",
		"userAddress": "3 Vera Trail",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 197,
		"userID": 9515
	},
	{
		"userName": "Susy Rikkard",
		"userEmail": "SRikkard@GuptaUni.edu",
		"userPassword": "zdQ7Dxk58",
		"userPhone": "(194) 2581616",
		"userAddress": "34969 Maple Terrace",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 198,
		"userID": 9516
	},
	{
		"userName": "Denni Grzes",
		"userEmail": "DGrzes@GuptaUni.edu",
		"userPassword": "ln9HQ2bSG3I",
		"userPhone": "(255) 7009219",
		"userAddress": "02658 Prentice Terrace",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 198,
		"userID": 9517
	},
	{
		"userName": "Trina De Cruze",
		"userEmail": "TDe Cruz@GuptaUni.edu",
		"userPassword": "Sb6TiL",
		"userPhone": "(101) 5322051",
		"userAddress": "88935 Carberry Avenue",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 199,
		"userID": 9518
	},
	{
		"userName": "Erna Drummer",
		"userEmail": "EDrummer@GuptaUni.edu",
		"userPassword": "T6UFbh1",
		"userPhone": "(729) 8965731",
		"userAddress": "33093 Rutledge Place",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 199,
		"userID": 9519
	},
	{
		"userName": "Yule Cavilla",
		"userEmail": "YCavilla@GuptaUni.edu",
		"userPassword": "ortyVNQsrX3X",
		"userPhone": "(205) 9333072",
		"userAddress": "20 Gateway Trail",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 200,
		"userID": 9520
	},
	{
		"userName": "Missie Vairow",
		"userEmail": "MVairow@GuptaUni.edu",
		"userPassword": "evjRyiSMs",
		"userPhone": "(754) 2909860",
		"userAddress": "97 Fisk Terrace",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 200,
		"userID": 9521
	},
	{
		"userName": "Tamas Aslum",
		"userEmail": "TAslum@GuptaUni.edu",
		"userPassword": "w5W3Yu",
		"userPhone": "(104) 1129748",
		"userAddress": "7 Grim Parkway",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 201,
		"userID": 9522
	},
	{
		"userName": "Kylila McCaster",
		"userEmail": "KMcCaste@GuptaUni.edu",
		"userPassword": "vFNBRec6Ja",
		"userPhone": "(355) 7860471",
		"userAddress": "4224 Tennessee Place",
		"userType": "Researcher",
		"researchSalary": "$120,000 ",
		"researchOfficeNum": 201,
		"userID": 9523
	},
	{
		"userName": "Storm Stratz",
		"userEmail": "SStratz@GuptaUni.edu",
		"userPassword": "1RmmuoAWaJ5",
		"userPhone": "(228) 7170620",
		"userAddress": "7 Manufacturers Pass",
		"userType": "Researcher",
		"researchSalary": "$75,000 ",
		"researchOfficeNum": 201,
		"userID": 9524
	}
];
export default researcher;
